### ISSUE TITLE
Read JSON Formatted Contract Addresses From a File 

### ISSUE THREAD

**Issue by kendricktan** [omisego/elixir-omg#1017]
Currently the branch https://github.com/omisego/elixir-omg/tree/948-ald-deposit-tx-integration reads the contract address via an environment variable `RINKEBY_CONTRACT_ADDRESS` in a string with the following schema:

```
{
  "plasma_framework": "...",
  "eth_vault": "...",
  "erc20_vault": "...",
  "payment_exit_game": "..."
}
```

Escaping the strings in order to make it a JSON compatible string makes it less readable when specifying them as an environment variable (also it still doesn't work, throws an error `unexpected byte at position 0: 0x6D ('m')`, I'm not sure how `elixir` parses JSON encoded strings even after @InoMurko gave me a correct example), e.g.

```
RINKEBY_CONTRACT_ADDRESS: "{\"eth_vault\": \"0x0204a86ba48b0fbf53f39fac60e80fe5127d1448\", \"erc20_vault\": \"0xc38a99e5e32bcfe777fbfbe50c6be840ee973704\", \"plasma_framework\": \"0x4f61ae3f3725f009d0ebd767011ea796bc025ce1\", \"payment_exit_game\": \"0x0a195b76e3695558032559ef8be0d8d51e98cf0d\"}"
```

I propose either:

1. Write contract addresses to a `.json` file and have `elixir-omg` read it on startup and inject them into the application runtime.
2. Have them as individual environment variables, e.g.
```
RINKEBY_PLASMA_FRAMEWORK_ADDRESS: <addr>
RINKEBY_PLASMA_EXIT_GAME_ADDRESS: <addr>
RINKEBY_PLASMA_ETH_VAULT_ADDRESS: <addr>
RINKEBY_PLASMA_ERC20_VAULT_ADDRESS: <addr>
```

**Comment by jbunce** [comment]
What does the ENV inside of the container get set as at runtime? This may be due to how the `.yaml` definition is rendered.

**Comment by InoMurko** [comment]
This seems like an issue of an open PR. https://github.com/omisego/elixir-omg/pull/949#issuecomment-536866740

So it should be fixed there.

**Comment by pdobacz** [comment]
For future reference: JSON in ENV has been abandoned in #949 (and the subsequent #1021 PR).

Approach (2.) was taken.

However I think we should leave this open and eventually change the multitude of env variables to something proper, like a single json **file** as proposed above (1.)

**Comment by pdobacz** [comment]
A thread in `omg-js` up to here https://github.com/omisego/omg-js/issues/144#issuecomment-538333856 provides a nice alternative, which could potentially relieve us from passing multiple contract addresses around at least on the configuration side.

But let's think this through, I'm not sure yet this would work.
