### ISSUE TITLE
Flaky tests regarding OMG.DB and Postgres

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#1018]
I experience unpredictable tests failing on CI, e.g. https://circleci.com/gh/omisego/elixir-omg/20426?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Reruning circle-ci workflow usually helps.

**Comment by pdobacz** [comment]
yeah, it's very rare but happens to me as well, locally

**Comment by pnowosie** [comment]
Duplicate (#1025)
