### ISSUE TITLE
tests related to staring the webserver sometimes fails

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#1025]
```
OMG.ChildChainRPC.Web.Controller.FallbackTest

  * test returns error for non existing method  * test returns error for non existing method (0.00ms)


  1) test returns error for non existing method (OMG.ChildChainRPC.Web.Controller.FallbackTest)

     test/omg_child_chain_rpc/web/controllers/fallback_test.exs:22

     ** (EXIT from #PID<0.4214.0>) shutdown: failed to start child: OMG.ChildChainRPC.Web.Endpoint

         ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, OMG.ChildChainRPC.Web.Endpoint.HTTP}

             ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup

                 ** (EXIT) :badarg

```

We need to first invent some kind of decorator around test that will get called when the tests fails and print out all the configuration related to application :omg_child_chain_rpc so that we see which tests is leaking faulty configuration (:badarg)

**Comment by pnowosie** [comment]
Badarg got kind of hype. Was spotted also in WatcherRPC (random tests)
https://circleci.com/gh/omisego/elixir-omg/20651
https://circleci.com/gh/omisego/elixir-omg/20713
https://circleci.com/gh/omisego/elixir-omg/20426
(After closer look I can see I raise it in #1018 but with misleading title)
