### ISSUE TITLE
flaky byzantine events test

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#1031]
```
  * test time response for asking for exit data (51352.0ms)


  1) test time response for asking for exit data (OMG.Performance.ByzantineEventsTest)

     test/omg_performance/integration/byzantine_event_test.exs:28

     Assertion with == failed

     code:  assert error_exits == 0

     left:  108

     right: 0

     stacktrace:

       test/omg_performance/integration/byzantine_event_test.exs:47: (test)



```

https://app.circleci.com/jobs/github/omisego/elixir-omg/20935/parallel-runs/0/steps/0-107

**Comment by pdobacz** [comment]
yep, this happened to me locally, thx for reporting.

If this bites in the CI too, I have a quick fix. I suspect the cause is that the next phase of the test starts before the dust settles on the watcher after the preparation phase :(

**Comment by InoMurko** [comment]
If they're impossible to isolate within `integration` tests maybe we introduce a new tag?

**Comment by pdobacz** [comment]
I have poked around with the idea posted above and found that waiting around 2 seconds solves it.

For now, to bring the builds up, I'm going to patch with this, but then leave this issue for future investigation as it's quite interesting to see why this happens, esp. in case there's something serious going on.

The sleep I'm going to put around here https://github.com/omisego/elixir-omg/blob/master/apps/omg_performance/lib/omg_performance/byzantine_events.ex#L101

in a PR https://github.com/omisego/elixir-omg/pull/1034
