### ISSUE TITLE
A new table in watcher DB is needed to support ERC 20 tokens for Block Explorer

### ISSUE THREAD

**Issue by jrhite** [omisego/elixir-omg#1033]
We need to store the ERC20 symbol, name and contract address is the watcher DB so that we can support ERC20 tokens in the block explorer.

**Comment by pdobacz** [comment]
Wouldn't this belong in the block explorer? Sounds like a bit beyond the scope of Watcher.

(also maybe worth updating the title to be explicit it is about "support ERC20 in the explorer" :). Outside readers might conclude that ERC20 are generally not supported in the watcher).

**Comment by jrhite** [comment]
@pdobacz 

title updated :)

All the data the block explorer uses comes from the watcher database. There is no other database, so where will this data be stored.

Also see #1038 as we'll need a way to associate addresses with ERC tokens.

**Comment by pnowosie** [comment]
> There is no other database, so where will this data be stored.

@jrhite I believe there is also an option to extend the BlockExplorer and add whatever it needs to satisfy its requirements.

**Comment by jrhite** [comment]
@pnowosie sure, open to suggestions. We can extend the BlockExplorer functionality and I think that's the plan. I'm sure we'll discuss more this week and at the workshop.

I think there's 2 questions here.

1. Where does the code live to expose this data/functionality (eg: watcher, blockexplorer)? 
2. Where does the data for this functionality live? In the 'watcher' DB? In a new DB? Etc...

**Comment by unnawut** [comment]
My 2 cents...

1. I don't think we need the ERC20 symbol and name in `elixir-omg`. If this data needs to be fetched from outside and not used within `elixir-omg`'s core logic, then I think it's better to leave it out. External apps can get ERC20 symbol, name, etc. elsewhere.

2. However, the `txoutputs.currency` is owned by `elixir-omg` and will be required for API consumption. It's being stored as a binary so at some point it needs to be converted to the more convenient hex string, either right in database or at watcher's API return. So:
    - Any concern replacing the currency binary with hex strings instead? i.e. exactly `currency: "0xd26114cd6EE289AccF82350c8d8487fedB8A0C07"`
    - If storing hex string there is not ideal, the interim block explorer server can do the conversion :)

**Comment by jrhite** [comment]
I'm all for storing the values as hex strings instead of binary. Let's see what others say, because the convention has been to store as binary.

About getting the ERC 20 it could make our BE and MW laggy. That's why I was thinking it'd be best in the DB.

**Comment by unnawut** [comment]
> About getting the ERC 20 it could make our BE and MW laggy. That's why I was thinking it'd be best in the DB.

Using watcher DB replica is an interim solution and so eventually the blockexplorer will need its own DB. I think this can be the start of its own DB than having it on elixir-omg.

**Comment by jrhite** [comment]
Yeah. This is a bit of an implementation detail, but if we implement updating our system with new contracts via:

My initial thinking was:

> When a deposit comes in, start a new async process that will look up the contract address of the deposit and if it's not in our ERC20 table, then fetch the ERC20 symbol and data from somewhere. The deposit itself does not block and continues on as usual.

In this case the ERC20 data will end up in the live DB and soon get replicated to the replica. No biggie at all. We're shooting for eventual consistency here.

However, if another implementation choice is decided on, well then, we'l go from there :-)

**Comment by pnowosie** [comment]
> I'm all for storing the values as hex strings instead of binary.

I'd like to share the *against* point of view
- mixing the types in tables could be a nightmare in maintenance 
- ...and would make it harder to query
- hex here is only useful for *presentation* layer, and AFAIC all layers could en/decode from binary to hex and vice versa without any cost
- what if we'll decide to present currencies in [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) format?

**Comment by unnawut** [comment]
@pnowosie With those points I agree they should be remain binary as they are.

**Comment by jrhite** [comment]
@pnowosie agreed as well. 😄

**Comment by unnawut** [comment]
Given now we're handling bugs (although indirectly) from code and DB fields that are not being used, I'll close this DB-only issue so we don't need to maintain what we don't use.

Feel free to submit a new issue when a user story arises and is promoted into an engineering cycle!
