### ISSUE TITLE
Reflect ALD contracts changes regarding queueing exits by (vault id, token) pair

### ISSUE THREAD

**Issue by pgebal** [omisego/elixir-omg#1035]
PR that introduced changes in contracts: https://github.com/omisego/plasma-contracts/pull/324/files

Contract API changes:
1. `processExit` takes vault id as a new argument https://github.com/omisego/plasma-contracts/blob/dc3d60a72b814916902c343cea30e65f1e4144c3/plasma_framework/contracts/src/framework/ExitGameController.sol#L118
2. `addToken` function is removed, exit queues are created by calling `addExitQueue` instead https://github.com/omisego/plasma-contracts/blob/dc3d60a72b814916902c343cea30e65f1e4144c3/plasma_framework/contracts/src/framework/ExitGameController.sol#L63
3. `hasToken` is removed, use `hasExitQueue` instead https://github.com/omisego/plasma-contracts/blob/dc3d60a72b814916902c343cea30e65f1e4144c3/plasma_framework/contracts/src/framework/ExitGameController.sol#L52
4. `PaymentExitGame` now takes vault ids instead of vault addresses as arguments https://github.com/omisego/plasma-contracts/blob/dc3d60a72b814916902c343cea30e65f1e4144c3/plasma_framework/migrations/5_deploy_and_register_payment_exit_game.js#L54

Some of the events published by aforementioned functions have changed.

**Comment by pdobacz** [comment]
Thank you :pray:.

Question that came to mind - were these changes included in the nascent ALD-contract integration docs?

**Comment by pgebal** [comment]
@pdobacz Changes are included only in docs here: https://github.com/omisego/plasma-contracts/tree/master/plasma_framework/docs

**Comment by pdobacz** [comment]
solved in https://github.com/omisego/elixir-omg/pull/1046
