### ISSUE TITLE
store eth txn hashes for all utxos that are finalized via processExit

### ISSUE THREAD

**Issue by jrhite** [omisego/elixir-omg#1091]
This is to support BE and possibly MV. See: omisego/omg-block-explorer#28

**Comment by unnawut** [comment]
Given now we're handling bugs (although indirectly) from code and DB fields that are not being used, I'll close this DB-only issue so we don't need to maintain what we don't use.

Feel free to submit a new issue when a user story arises and is promoted into an engineering cycle!
