### ISSUE TITLE
plasma-deployer takes a very long time to deploy

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#1095]
I think the work @kendricktan did is awesome and it moves us into the right direction. But deploying the contracts in elixir-omg via `docker-compose up plasma-deployer` takes roughly 4 to 8 minutes. How can we make this faster?

Can we bake certain contracts into the storage of the Ethereum client (geth, ganache) and have them pre-deployed?

**Comment by kendricktan** [comment]
Seems like the reason why it's taking so long is because it has to redownload solidity compiler each time it does a deploy. If we bake the solidity compiler into `plasmaDeployer.dockerfile` it _should_ speed it up

**Comment by unnawut** [comment]
@InoMurko Can we close this with the use of the image now?

**Comment by InoMurko** [comment]
Depends... It's still slow as hell! 4+ mins :D 

I was thinking if there are other ways we could speed it up. Could we pack the storage folder of the Ethereum client, right after the contracts are deployed?

**Comment by InoMurko** [comment]
https://github.com/omisego/elixir-omg/pull/1175
