### ISSUE TITLE
Child chain error when running in docker

### ISSUE THREAD

**Issue by kevsul** [omisego/elixir-omg#1098]
The following error appears in the child chain logs:
```
childchain_1       | 2019-11-04 10:45:20.227 [error] module=gen_server function=error_info/7 ⋅GenServer OMG.ChildChain.BlockQueue.Server terminating
childchain_1       | ** (CaseClauseError) no case clause matching: {:error, %{"code" => -32000, "message" => "unknown account"}}
childchain_1       |     (omg_child_chain) lib/omg_child_chain/block_queue/core.ex:476: OMG.ChildChain.BlockQueue.Core.process_submit_result/3
childchain_1       |     (omg_child_chain) lib/omg_child_chain/block_queue.ex:185: OMG.ChildChain.BlockQueue.Server.submit/1
childchain_1       |     (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
childchain_1       |     (elixir) lib/enum.ex:769: Enum.each/2
childchain_1       |     (omg_child_chain) lib/omg_child_chain/block_queue.ex:153: OMG.ChildChain.BlockQueue.Server.handle_info/2
childchain_1       |     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
childchain_1       |     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
childchain_1       |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
childchain_1       | Last message: :check_ethereum_status⋅
```

## Steps to reproduce
1. In elixir-omg, `git checkout 403990c59f351f4fa46d11b288b50e2dd34bc03a`
2. `make docker-start-cluster`
3. Deposit some ETH into childchain, wait for it to show up in `account.get_utxos`
3. Submit a transaction spending the deposited utxo, it appears to succeed (no error message from watcher or childchain)
4. The above error appears in the childchain logs

It looks like it occurs when the childchain attempts to submit a block

**Comment by InoMurko** [comment]
Interesting. I think we either will, or will not encounter this soon on specs.
cc @achiurizo @chrishunt

**Comment by unnawut** [comment]
I'm suspecting it might be from this commit https://github.com/omisego/elixir-omg/commit/c280a8af7683bff721b6db9096e87941b129e7db that we now specify the addresses but geth might not be aware of them and hence return `%{"code" => -32000, "message" => "unknown account"}`

**Comment by kevsul** [comment]
I'm pretty sure that change worked.
I mean, creating the addresses before starting geth

**Comment by unnawut** [comment]
The keystore file passed to geth belongs to `DEPLOYER_ADDRESS` though. Should it be `AUTHORITY_ADDRESS`'s keystore?
