### ISSUE TITLE
Child chain should read MIN_EXIT_PERIOD from PlasmaFramework contract

### ISSUE THREAD

**Issue by kevsul** [omisego/elixir-omg#1101]
Currently the childchain's exit period is set via a configuration variable.
However, as discussed in Slack

```
unnawut  11 hours ago
Now that we're deeper into this. I wonder if there's any use case for an exit period on childchain longer than the plasma_contract's MIN_EXIT_PERIOD?

unnawut  11 hours ago
or if that should ever be allowed

Papa Paweł  11 hours ago
This is v good question! How much longer btw?

unnawut  11 hours ago
No idea at all. Just wondering what could happen if the config in elixir-omg and plasma-contracts misalign.
elixir-omg < plasma-contracts, I guess the contract will just safely reject the exit.
elixir-omg > plasma-contracts, it exits successfully, but just poorer UX from unneccessarily longer wait time? (edited) 

Papa Paweł  11 hours ago
I guess the contract will just safely reject the exit.
I don't think so contract knows nothing about elixir code so exit takes longer to finalize...
just poorer UX
Or security issue? - Watcher tells user there is still time to challenge where in fact... Oops
I wonder why elixir doesn't get the value calling the contract (edited) 
```

and here #1099  this could mean that the childchain is configured differently than the contracts.

A better solution would be for the childchain to get the value from the PlasmaFramework contract. It's a public member variable:
`PlasmaFramework.minExitPeriod`

**Comment by pdobacz** [comment]
For some background (might soon become irrelevant, but still is) - the reason why it didn't use the value from the contracts, is that the `elixir-omg` needed to take care of the early deployments of contracts, and as a consequence, feed `exit_period_seconds` to `plasma-contracts`. A bit of a chicken-egg problem.

CC @pnowosie

**Comment by InoMurko** [comment]
https://github.com/omisego/elixir-omg/pull/1099

**Comment by boolafish** [comment]
I thought current contract deployment is pretty independent from elixir-omg now(?) or there is still sth elixir-omg should take care of?

**Comment by InoMurko** [comment]
We're deploying in in our tests @boolafish. Hopefully soon that will stop as well!

**Comment by InoMurko** [comment]
done here https://github.com/omisego/elixir-omg/commit/fb4a75fff8954ffffc4b49f62124dda6e51913ba
