### ISSUE TITLE
Streamline (a bit of) `plasma-contracts` SHA upgrade

### ISSUE THREAD

**Issue by unnawut** [omisego/elixir-omg#1102]
To recap, upgrading `elixir-omg` to a newer `plasma-contracts` requires...

1. Bump [`elixir-omg/mix.lock`](https://github.com/omisego/elixir-omg/blob/master/mix.lock) to that SHA
2. Bump [`docker-elixir-omg/tester/Dockerfile.plasma_deployer`](https://github.com/omisego-images/docker-elixir-omg/pull/4) to that SHA (note: a different repo)
3. Ensure that the new docker image appears on [Docker Hub](https://hub.docker.com/r/omisegoimages/elixir-omg-tester/tags) before another docker-compose up or rerun a PR build

These steps can be streamlined a bit further by

1. Move `elixir-omg/Dockerfile.plasma_deployer` to `plasma-contracts/Dockerfile`
2. Add CI to autobuild an `omg-plasma-contracts` docker image for each new SHA

This way each upgrade needs to update only `mix.lock` and `docker-compose.yml` and can be done in one PR in one repo (`elixir-omg`).

Unknowns: Not sure if anything under `.circleci/*` needs to be updated or will prevent this from happening.

**Comment by unnawut** [comment]
Will start this after these are merged:
- https://github.com/omisego-images/docker-elixir-omg/pull/4
- https://github.com/omisego/elixir-omg/pull/1093
- https://github.com/omisego/elixir-omg/pull/1100
- https://github.com/omisego/elixir-omg/pull/1056

**Comment by InoMurko** [comment]
If you want to move that into `plasma-contracts/DOckerfile` you will need to move credentials there as well. Those in `omisego-images`

**Comment by unnawut** [comment]
Eh what credentials do you mean?

**Comment by unnawut** [comment]
@InoMurko Eh what credentials do you mean?

**Comment by InoMurko** [comment]
If you want to push the image to the repository...

**Comment by InoMurko** [comment]
The issue not relevant anymore with snapshot PR https://github.com/omisego/elixir-omg/pull/1175
