### ISSUE TITLE
Operator can update the fee tokens and amount without a restart

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#1115]
As an operator,
I want to update the fee tokens and corresponding amount without restarting the service,
So that my users will not suffer from any downtime.

**Comment by jbunce** [comment]
I'm fairly sure this is current behaviour. Would need to test.

**Comment by pdobacz** [comment]
> I'm fairly sure this is current behaviour. Would need to test.

confirm, this should be the case. An update to the fee specs file should be digested by the Child Chain instance and it should continue with the new specs from then on.

**Comment by InoMurko** [comment]
I presume this is sorted by the fee service @Pongch @T-Dnzt ?
if not, pls reopen.
