### ISSUE TITLE
Watcher EthereumEventListeners bound by PG speed

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#1130]
What was the reason that these two listeners (they're transforming events into postgres inserts) part of the same `EthereumEventListener` cluster of "security" properties of Watcher?

```
# this instance of the listener sends deposits to be consumed by the convenience API
      EthereumEventListener.prepare_child(
        service_name: :convenience_deposit_processor,
        synced_height_update_key: :last_convenience_deposit_processor_eth_height,
        get_events_callback: &Eth.RootChain.get_deposits/2,
        process_events_callback: fn deposits ->
          Watcher.DB.EthEvent.insert_deposits!(deposits)
          {:ok, []}
        end
      ),
# this instance of the listener sends exits to be consumed by the convenience API
      # we shouldn't use :exit_processor for this, as it has different waiting semantics (waits more)
      EthereumEventListener.prepare_child(
        service_name: :convenience_exit_processor,
        synced_height_update_key: :last_convenience_exit_processor_eth_height,
        get_events_callback: &Eth.RootChain.get_standard_exits/2,
        process_events_callback: fn exits ->
          exits |> Watcher.DB.EthEvent.insert_exits!()
          {:ok, []}
        end
      ),
```

**Cluster setup for watcher** is also important for this discussion.
```
def coordinator_setup do
    deposit_finality_margin = Application.fetch_env!(:omg, :deposit_finality_margin)
    finality_margin = Application.fetch_env!(:omg_watcher, :exit_finality_margin)

    %{
      depositor: [finality_margin: deposit_finality_margin],
      convenience_deposit_processor: [waits_for: [:depositor], finality_margin: deposit_finality_margin],
      block_getter: [
        waits_for: [depositor: :no_margin, convenience_deposit_processor: :no_margin],
        finality_margin: 0
      ],
      exit_processor: [waits_for: :depositor, finality_margin: finality_margin],
      convenience_exit_processor: [
        waits_for: [:convenience_deposit_processor, :block_getter],
        finality_margin: finality_margin
      ],
      exit_finalizer: [
        waits_for: [:depositor, :block_getter, :exit_processor],
        finality_margin: finality_margin
      ],
      exit_challenger: [waits_for: :exit_processor, finality_margin: finality_margin],
      in_flight_exit_processor: [waits_for: :depositor, finality_margin: finality_margin],
      piggyback_processor: [waits_for: :in_flight_exit_processor, finality_margin: finality_margin],
      competitor_processor: [waits_for: :in_flight_exit_processor, finality_margin: finality_margin],
      challenges_responds_processor: [waits_for: :competitor_processor, finality_margin: finality_margin],
      piggyback_challenges_processor: [waits_for: :piggyback_processor, finality_margin: finality_margin],
      ife_exit_finalizer: [
        waits_for: [:depositor, :block_getter, :in_flight_exit_processor, :piggyback_processor],
        finality_margin: finality_margin
      ]
    }
  end
```
@pdobacz @pnowosie inputs greatly appreciated 🙇

**Comment by pdobacz** [comment]
not sure what you mean by your question, but I can throw what I know on this.

So, the listeners weren't every properly divided into `security-oriented` and `informational-API-oriented` as this split has been not completed (in other words - there was no convenient way to turn off the informational API/Postgres part of the app).

I think, if you take them out and put somewhere else, maintaining the ordering of event processing that the `coordinator_setup` defines, it's going to make sense. The ordering is basically first deposits, second blocks, third exits.

Does this help?

**Comment by InoMurko** [comment]
You said:
> maintaining the ordering of event processing that the coordinator_setup defines, it's going to make sense. The ordering is basically first deposits, second blocks, third exits.

Why is this ordering enforced?

**Comment by InoMurko** [comment]
I thought so! Thanks! So this is a strong consistency vs. eventual consistency argument... even though If you try to spend a UTXO not yet created - child chain would stop you at that. 

The question is @unnawut (you’re looking at the split now), do we enforce strong consistency on the informational side as well or do we acknowledge that this would eventually converge in into the correct state. This is also where the product comes in (@Pongch )

**Comment by unnawut** [comment]
> do we enforce strong consistency on the informational side as well or do we acknowledge that this would eventually converge in into the correct state. This is also where the product comes in

Agree, I think this depends on the usage discussion in #1129 

But meanwhile, my 2 cents now would be to aim for informational API with eventual consistency. If it needs a strong consistency then I'd argue the informational API we have now should also be part the security properties.

**Comment by pdobacz** [comment]
> > you'll attempt to "spend" a UTXO not yet created.
> even though If you try to spend a UTXO not yet created

ah sorry, I maybe wrote that unclear, so just for clarity: by "spend" (in quotes) I meant do sth in the DB/state you're maintaining. So you'd attempt to say `UPDATE` a row that represents a deposit UTXO, without that row there, etc.

**Comment by InoMurko** [comment]
Solved by the split.
