### ISSUE TITLE
Bump plasma-contracts SHA to Nov 12

### ISSUE THREAD

**Issue by unnawut** [omisego/elixir-omg#1138]
Target SHA: https://github.com/omisego/plasma-contracts/commit/1c7cd867b1353ae72c825a6d15b2d382689f30ad

A bit of work to change the deployment interface as @boolafish pointed out:

- https://github.com/omisego/plasma-contracts/commit/db824055bb3037d2fc1034b8ec751494cbe1dd4b
- https://github.com/omisego/plasma-contracts/commit/43968f6fdab815fb5b46cfcf2d9803d3a26ea1e9

Build errors: https://circleci.com/workflow-run/856730f1-ada9-4c4c-9017-53a00806b033

TODOs:
- [x] Bump https://github.com/omisego-images/docker-elixir-omg/blob/master/tester/Dockerfile.plasma_deployer#L15
- [ ] Bump `elixir-omg` to new SHA
- [ ] Fix `elixir-omg` contracts deployment errors during tests (align with the 2 plasma-contracts commits above)
- [ ] Let devops know when `elixir-omg` PR with new contracts SHA is merged.

**Comment by boolafish** [comment]
I tracked to these two files from the error message:

https://github.com/omisego/elixir-omg/blob/master/apps/omg_eth/test/support/bundle_deployer.ex
https://github.com/omisego/elixir-omg/blob/master/apps/omg_eth/test/support/deployer.ex
