### ISSUE TITLE
Insufficient tx validation

### ISSUE THREAD

**Issue by thec00n** [omisego/elixir-omg#1163]
### Description 

`outputType` is not properly checked when a tx is sent on the child chain. Omitting the `outputType` when sending a tx is accepted by the child chain. Retrieving the created tx from the watcher shows that the child chain defaults to `outputType` 1 when the field is omitted. This could be problematic when other outputTypes are introduced but they are not compatible, yet the child chain defaults them to `outputType` 1.

```
{
  "transactionType": 1,
  "inputs": [
    {
      "blknum": 22000,
      "txindex": 0,
      "oindex": 0
    }
  ],
  "outputs": [
    {
      "outputGuard": "0xd42b31665b93c128541c8b89a0e545afb08b7dd8",
      "currency": "0x0000000000000000000000000000000000000000",
      "amount": 1
    }
  ],
  "metadata": "0x0000000000000000000000000000000000000000000000000000000000000000"
}


Transaction submitted:  0x689666b8cb5080c46d5bb2b5cfe0139e4b9cdb6fb6172713477ed5982b3545f6
```

`transactionType` is not checked at all and it can be omitted or set to something arbitrary and it's accepted by the child chain. 

```
{
  "transactionType": 1337,
  "inputs": [
    {
      "blknum": 23000,
      "txindex": 0,
      "oindex": 0
    }
  ],
  "outputs": [
    {
      "outputType": 1,
      "outputGuard": "0xd42b31665b93c128541c8b89a0e545afb08b7dd8",
      "currency": "0x0000000000000000000000000000000000000000",
      "amount": 1
    }
  ],
  "metadata": "0x0000000000000000000000000000000000000000000000000000000000000000"
}

Transaction submitted:  0xe18a0f5c86a07f2eafcc4042a31004959951d84e3a6a848114e3fc95a3b9a0af
```

**Comment by pdobacz** [comment]
Thanks, I admit I'm quite surprised this is the case. The child chain most definitely has those checks, in current implementation anything other than `1` should result in `malformed_transaction/outputs` or `unrecognized_output_type` error. It should even not be able to look up the respective code to dispatch further decoding to, if the type is other than `1`. (lemme double check this now)

Can you give the exact steps you're doing to reproduce this? What you've given doesn't resemble calls to the child chain API `transaction.submit`.

**Comment by pdobacz** [comment]
yeah, I checked against one of our deployments: child chain rejects transactions with either `transaction_type` or `output_type` (I sanity-checked that it does provide a post-decoding error in case I put correct values back in)

```
%{
  "data" => %{
    "code" => "submit:malformed_transaction",
    "description" => nil,
    "object" => "error"
  },
  "service_name" => "child_chain",
  "success" => false,
  "version" => "0.3.0+7e17772"
}
```

```
%{
  "data" => %{
    "code" => "submit:unrecognized_output_type",
    "description" => nil,
    "object" => "error"
  },
  "service_name" => "child_chain",
  "success" => false,
  "version" => "0.3.0+7e17772"
}
```

**Comment by thec00n** [comment]
Ok `transactionType` is currently hard coded in omg-js https://github.com/omisego/omg-js/blob/88e018aaff75c21b2e3edba3649cb1ae0c6bb83a/packages/omg-js-util/src/typedData.js#L77. That's what I am currently using. @nicholasmueller are you guys doing that because `transaction.create` does not return the `transactionType`?

**Comment by pdobacz** [comment]
@thec00n so this looks like a `omg-js` issue. If anything needs to be done on `elixir-omg` end, pls reopen/file a new issue
