### ISSUE TITLE
As a user I would like to be see both the creating and spending txhash of the utxos

### ISSUE THREAD

**Issue by thec00n** [omisego/elixir-omg#1167]
### Description 
There is no easy way to check which tx created a UTXO

### Suggested fix 
Included the information in the output of `account.get_utxos`

Add `creating_hash` and `spending_hash` fields

**Comment by unnawut** [comment]
Similar to https://github.com/omisego/elixir-omg/issues/1162 but this issue is for `/account.get_utxos` while the other one is for `/transaction.all`. Let's keep the issues separate for now.

**Comment by jrhite** [comment]
This is implemented.

Request
`curl -X POST "https://watcher-info.ropsten.v1.omg.network/account.get_utxos" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"address\":\"0xab1da73872242b33be1de8acca098e660531a28a\"}"`

Response
```
{
  "data": [
    {
      "amount": 100000000000,
      "blknum": 1000,
      "creating_txhash": "0x2c499b95ccb6bf7b923049b32b03a613d30882a448102136e544b302119eb722",
      "currency": "0x0000000000000000000000000000000000000000",
      "inserted_at": "2020-03-12T11:47:48Z",
      "oindex": 1,
      "otype": 1,
      "owner": "0xab1da73872242b33be1de8acca098e660531a28a",
      "spending_txhash": null,
      "txindex": 0,
      "updated_at": "2020-03-12T11:47:48Z",
      "utxo_pos": 1000000000001
    },
    {
      "amount": 499999900000000000,
      "blknum": 14000,
      "creating_txhash": "0xe98dd6a468135984f7298bea1b5a935ddb578a0bab851111e3ff48b58b0437dc",
      "currency": "0x0000000000000000000000000000000000000000",
      "inserted_at": "2020-03-12T13:36:50Z",
      "oindex": 0,
      "otype": 1,
      "owner": "0xab1da73872242b33be1de8acca098e660531a28a",
      "spending_txhash": null,
      "txindex": 0,
      "updated_at": "2020-03-12T13:36:50Z",
      "utxo_pos": 14000000000000
    }
  ],
  "service_name": "watcher_info",
  "success": true,
  "version": "0.4.5+a8b3bd4"
}

```

**Comment by thec00n** [comment]
@jrhite just looking at this again. `spending_txhash` will always be null in this case because if it is spent `/account.get_utxos` will not return it.

**Comment by jrhite** [comment]
@thec00n ah yes right of course.

This endpoint `/account.get_utxos` represents what you 'own' now. It filters by owner address **and** `not yet spent or exited` conditions (just revisited the code to confirm).

There is also the use case (and we already support it) of `get me my account` ledger which would also show spent utxos. This is covered in the api endpoint `/transaction.get_transactions` with an owner address passed in as a filter. And ultimately you can drill down and get to the UTXOs, both unspent and pent. mixing the two.

For clarity and correctness, let me change the wording back to its original form.
