### ISSUE TITLE
Watcher Info API: /block.all

### ISSUE THREAD

**Issue by okalouti** [omisego/elixir-omg#1168]
Block explorer includes the following user story. 

_As a user I would like to see a list of most recent blocks with their associated ETH `tx_hash`_

See BE [Issue 36](https://github.com/omisego/blockexplorer/issues/36)

For this, we will need a watcher endpoint `blocks.all` which returns an array of `Block` objects in order of recency.

It should be able to take two parameters for pagination: 

```
{
  "limit": 100,
  "page": 2
}
```

**Sample Response:** 

```
{
  "success": "true",
  "data":  [
   {
    "blknum": 123000,
    "plasma_hash": "0x2frrvghbt2343256hntynyd50f23cd1fdf....",
    "eth_hash": "0x2733e50f526ec2fa19a22b31e8ed50f23cd1fdf....", 
    "timestamp": "1234567981"
  } , ...
],
  "data_paging": {
    "page": 1,
    "limit": 200
  }, 

}
```

**Comment by jrhite** [comment]
depends on https://github.com/omisego/elixir-omg/issues/931

**Comment by unnawut** [comment]
Let's try not to block everything, we can have `/block.all` without the txn hash and add when #931 is ready.

**Comment by jrhite** [comment]
Yeah, agreed. A reference to the dependency is enough here.
