### ISSUE TITLE
Watcher Info API: /block.get

### ISSUE THREAD

**Issue by okalouti** [omisego/elixir-omg#1169]
Block explorer includes the following user story. 

_As a user I would like to navigate to a block detail page by clicking on a block in the block list. Block details will contain the list of transactions that occurred in the block and the eth txn hash that the block was created with._ 

See BE [Issue 35](https://github.com/omisego/blockexplorer/issues/35)

For this, we will need a watcher endpoint `block.get` which returns a `Block` object for a given Plasma `hash`

It should be able to take an `hash` query parameter corresponding to the Plasma hash. 

```
{
  "hash": "0x0017372421f9a92bedb7163310918e623557ab5310befc14e67212b660c33bec"
}
```

The response should include the `eth` transaction hash that the block was created with. 

**Sample Response:** 

```
{
  "success": true,
  "data": {
    "blknum": 123000,
    "eth_hash": "0x2733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981f",
    "plasma_hash": "0x0017372421f9a92bedb7163310918e623557ab5310befc14e67212b660c33bec", 
     "timestamp": "1234567981",
     "transactions": [
       Transaction {}
    ]
  }
}
```

Transaction object should include **tx_hash** and **timestamp**. 

It should also include a way to calculate transaction value. This can be with something along the lines of the existing `results` key summing value by currency in `/transaction.all`: 

```
 "results": [
        {
          "currency": "0x0000000000000000000000000000000000000000",
          "value": 499999999999992300
        }
      ],
```

Alternatively, one could derive this from inputs and outputs. 

Input and output objects would only need to include an `amount` for each `currency` for this purpose.

Will leave  this decision to `elixir-omg` team!

**Comment by Pongch** [comment]
At first glance, I believe this functionality is more or less offered on the child chain `block.get` API, except for a few things missing from this story:

1. eth-hash is currently not available for plasma block
2. transactions are in their hex-encoded format
3. summation of transaction values

**Comment by okalouti** [comment]
@Pongch Correct. 

@unnawut and I thought this should exist in the watcher informational API but feel free to challenge there.

**Comment by jrhite** [comment]
> eth-hash is currently not available for plasma block
Correct. Please see: https://github.com/omisego/elixir-omg/issues/931 for this.
