### ISSUE TITLE
As a user I would like to know when the watcher considers the child chain byzantine

### ISSUE THREAD

**Issue by thec00n** [omisego/elixir-omg#1172]
### Description 
At the moment the watcher does not explicitly signal when it considers the child chain byzantine. 

### Suggested Fix 
Add a timestamp field `byzantine` to response of `/status.get` that contains the timestamp when the watcher considers the child chain byzantine. The field is empty if the child chain is not byzantine.

**Comment by pdobacz** [comment]
:+1: also let's be wary of the related https://github.com/omisego/elixir-omg/issues/811 and whatever changes to the API that might bring.

**Comment by InoMurko** [comment]
Hey @thec00n 
do you think this is a huge blocker? 😉

**Comment by jrhite** [comment]
the `timestamp` will be the earliest block that has an byzantine event that actually makes the chain byzantine. not all byzantine events mean the chain is byzantine.

@thec00n, can you please add a link to where this is documented?

thank you.

**Comment by thec00n** [comment]
I think we can close this issue. Additionally to the operator triggered byzantine events any unchallenged exit from the user raises now an event (see https://github.com/omisego/elixir-omg/pull/1493). The events signal that that chch is byzantine and that users should exit. 

Updated docs:
https://github.com/omisego/elixir-omg/blob/master/docs/exit_validation.md#unchallenged_exit-condition
https://github.com/omisego/elixir-omg/blob/master/docs/api_specs/status_events_specs.md
