### ISSUE TITLE
Lock down the dependencies for chch / watcher

### ISSUE THREAD

**Issue by thec00n** [omisego/elixir-omg#1173]
### Description 
The chch / watcher are critical components of the OMG network. As we are getting closer to running production grade services there is a need to evaluate the current dependencies from a security perspective and lock them down.

### Suggested Fix
- Review all current dependencies 
- Lock down required dependencies 
- Decide on a upgrade process

**Comment by InoMurko** [comment]
1. Code owners for mix.lock (that would summon all devs - more eyes more security?)
2. `DependABot` (review for dependecy bumps)
3. Security review of current dependencies 
4. Review if we really need all dependencies for production builds (try and lower these!) -> Prioritize review of dependencies (smaller to bigger - for example, cowboy is a dependency used a lot by the community)

**Comment by InoMurko** [comment]
@thec00n awaiting your input.

**Comment by thec00n** [comment]
Consider using  https://github.com/mirego/mix_audit

**Comment by okalouti** [comment]
Structuring the components of this issue a little bit: 
- [ ] Review and implement automated dependency checking: [Dependabot](https://dependabot.com/)
- [ ] Review and implement automated dependency checking: [mix_audit](https://hexdocs.pm/mix_audit/readme.html)
- [ ] Identify list of dependencies used in release (versus ones for testing/development) to prioritise for scrutiny
- [ ] Identify any production dependencies that can be removed.
- [ ] Discuss and - if agreed - implement [CODEOWNERS](https://help.github.com/en/enterprise/2.15/user/articles/about-code-owners) for `mix.lock` and `mix.exs`

**Comment by okalouti** [comment]
Closing following thread with Piotr: https://omisego.slack.com/archives/C9KNA675J/p1585058472388200
