### ISSUE TITLE
API to return service_name: "watcher" or "watcher_info" based on the started mode

### ISSUE THREAD

**Issue by unnawut** [omisego/elixir-omg#1201]
As an API user I want to check the response's `"service_name"` to know whether I'm talking to the security-critical watcher API or the informational one.

Original conversation: https://github.com/omisego/elixir-omg/pull/1193#issuecomment-564222621

## Actual behaviour

Both `watcher` and `watcher_info` return `"service_name": "watcher"`.

```json
{
  "data": {
    "some_key": "some value"
  },
  "service_name": "watcher",
  "success": true,
  "version": "0.3.0+94d24f0"
}
```

## Expected behaviour

- `watcher` return `"service_name": "watcher"`
- `watcher_info` return `"service_name": "watcher_info"`
- The value is determined by the start mode, not where the endpoint belongs now. This is because `watcher_info`'s API specs will eventually include all security-critical endpoints.

**Comment by jrhite** [comment]
Is this just a temporary issue because of the split? Won't a request know which service it's talking to based on the request it made?

**Comment by jrhite** [comment]
> Is this just a temporary issue because of the split? Won't a request know which service it's talking to based on the request it made?

Ah, ignore my comment. Understood now. 👍

**Comment by InoMurko** [comment]
FYI https://github.com/omisego/elixir-omg/blob/master/priv/apps/itest/test/itest/service_name_test.exs#L25-L32
