### ISSUE TITLE
Watcher Informational API service name

### ISSUE THREAD

**Issue by jbunce** [omisego/elixir-omg#1204]
The informational Watcher API returns: `"service_name":"watcher"`, which is the same as the security critical service. Consider adding `watcher_info` to the informational Watcher.

**Comment by unnawut** [comment]
Dupe of https://github.com/omisego/elixir-omg/issues/1201

**Comment by unnawut** [comment]
Although, is any devops component relying on this returned value at the moment? Otherwise it's not yet prioritized.

**Comment by jbunce** [comment]
No infra relies on this
