### ISSUE TITLE
RocksDB dependency issue when running tests and using Make

### ISSUE THREAD

**Issue by okalouti** [omisego/elixir-omg#1248]
As I work on the Informational Watcher API, two key elements of the development process are the following: 

* **Testing**: I write tests and run them with `mix test`

* **Visualising API changes:** If I write code to modify the API response, I would like to visualise this with `Insomnia` or `Postman`. To reflect changes on containers that were started with `docker-compose up`, I run `make docker-update-watcher_info`. 

This flow is hampered by `:rocksdb`. 

If I run tests, I will get the following error when I run `make docker-update-watcher_info`: 

```
** (Mix) Could not compile dependency :rocksdb, "/home/elixir-omg/.mix/rebar3 bare compile --paths "/app/_build/prod/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile rocksdb", update it with "mix deps.update rocksdb" or clean it with "mix deps.clean rocksdb"

```
Running `mix deps.clean --all` followed by `mix deps.get` will fix the issue, but then I will get the above error if I try to run tests. 

The result is that much time is lost cleaning and re-installing dependencies.

A fix would allow me to test and (re)build containers concurrently without this dependency issue as I work on `watcher_info`

N.B. @unnawut explains that this due to the dependency cache being shared - and that separate dependency caches may sort the issue.

**Comment by unnawut** [comment]
Expanding on

> due to the dependency cache being shared - and that separate dependency caches may sort the issue.

It's this line https://github.com/omisego/elixir-omg/blob/master/Makefile#L244:

```makefile
docker run --rm -it \
  ...
  -v $(IMAGE_BUILD_DIR)/deps:/app/deps \
  ...
```

And because rocksdb is compiled from source, it's incompatible between the host's MacOS and docker container's linux, so the deps can't be shared.

**Comment by InoMurko** [comment]
Yep exactly that @unnawut . Container mounts the local volume and it leaves compilations in the mounted volume. Containers are linux, host is osx and compilation outputs are not compatible.

Idk if there's a solution to this... if you go back and forth many times I suggest you use baremetal cluster.
```
make start-services
make start-child_chain
make start-watcher
```

**Comment by InoMurko** [comment]
@okalouti would that work? ^^

**Comment by InoMurko** [comment]
Thought of something:
There must be a way to redirect dependency build directories. So we could push rocksdb into
`/tmp/rocksdb/_docker_build`
`/tmp/rocksdb/_build`
and that should know where to get the build from based on OS.

On the other hand, you need to have separate folders for `<root_proj>/_build` dir as well.

**Comment by okalouti** [comment]
Hi @Ino. Above would work if there is no simpler solution!

**Comment by jrhite** [comment]
> Yep exactly that @unnawut . Container mounts the local volume and it leaves compilations in the mounted volume. Containers are linux, host is osx and compilation outputs are not compatible.
> 
> Idk if there's a solution to this... if you go back and forth many times I suggest you use baremetal cluster.
> 
> ```
> make start-services
> make start-child_chain
> make start-watcher
> ```

@InoMurko multi-stage docker builds solve the problem, by not leaving compilations on the local mounted volume. I'd recommend you have a look into this it might be useful.

I had a working PR of this I can dig up if you'd be interested in seeing it again.

**Comment by pdobacz** [comment]
> There must be a way to redirect dependency build directories. So we could push rocksdb into

Totally unsure, if this is something we'd want to venture into, but technically speaking `mix.exs` does allow one to customize those paths. 

```
      build_path: "../../_build",
      deps_path: "../../deps",
```

**Comment by InoMurko** [comment]
> > There must be a way to redirect dependency build directories. So we could push rocksdb into
> 
> Totally unsure, if this is something we'd want to venture into, but technically speaking `mix.exs` does allow one to customize those paths.
> 
> ```
>       build_path: "../../_build",
>       deps_path: "../../deps",
> ```

oh look! that's even easier!

**Comment by InoMurko** [comment]
Lets try this approach. If not we can reopen and revert.
