### ISSUE TITLE
drop SubscriptionWorker support for new Heads

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#1255]
From what I've observed now I don't think having subscriptions for newHeads (getting `ethereum_height` - new block numbers) really makes much sense.

Why?
If we make RPC calls, it really is 1 RPC call per estimated 12-15 seconds. That's really not that much.
Second Why?
Monitoring of newHeads (did a newHeads event really arrive when it should - every 12-15 seconds) would need to be added. I don't have definitive proof it happened in deployed environment,... but I guess it COULD happen.
Third Why?
Code Simplification.

//discuss 
[
![image](https://user-images.githubusercontent.com/2582555/72284104-7cedfd80-3640-11ea-94df-9395df8c5fbd.png)
](url)

**Comment by InoMurko** [comment]
@achiurizo @pdobacz

**Comment by pdobacz** [comment]
not 100% sure how far the "dropping" you're suggesting goes - does it include dropping getting the `newHeads` from a ws connection to Eth node altogether and reverting to polling?

If yes, I'm for it. I've always been a fan of doing those RPC calls for simplicity sake. Note though, that you have a block every 12-15 seconds, there would be more RPC calls involved to poll effectively (still not that much IMHO)

**Comment by InoMurko** [comment]
I would revert to poll at the same interval as `ETHEREUM_EVENTS_CHECK_INTERVAL_MS`.

At least what we gained from this exercise is that each of the components doesn't poll for themselves, they would still go through the same interface (one genserver that represents the ethereum height - `OMG.Eth.EthereumHeight`) and others get the height from this process.

Monitoring of this polling still needs to be done though. You still need to make sure you're actually fetching "new" values and raising alarms. But it's one less protocol you need to make sure it works.

**Comment by pdobacz** [comment]
ah, kind of an aggregate poll, got it. This sounds very reasonable

For low-level monitoring - true that. There's also #814, which will solve the top-level/user-facing/end-result monitoring, I think there's an option to defer (at least some) low-level monitoring facilities and still have our back covered by the user-facing #814

**Comment by pdobacz** [comment]
another reason to go through with this - at 1st glance, it seems `geth` 1.9.x doesn't play ball with `websockex`: [bullet number 3 here](https://github.com/omisego/elixir-omg/issues/879)

**Comment by jbunce** [comment]
Data from the mainnet deployment over the past month:

```
eth_getLogs
23,354,200 48.62%
eth_call
21,145,703 44.02%
eth_getBlockByNumber
1,429,76 2 2.98%
eth_syncing
1,429,255 2.98%
eth_getTransactionByHash
501,8771.04%
eth_getTransactionReceipt
172,116 0.36%
eth_sendRawTransaction
692 0.00%
eth_getCode
497 0.00%
eth_blockNumber
416 0.00%
net_version
94 0.00%
```

**Comment by jbunce** [comment]
Total (01/01/20 -> 28/01/20) 46,770,663

**Comment by InoMurko** [comment]
Thanks for the data @jbunce ! What was the ETHEREUM_EVENTS_CHECK_INTERVAL_MS setting for the data above?

**Comment by jbunce** [comment]
`./bin/variables:export ETHEREUM_EVENTS_CHECK_INTERVAL_MS=800`

**Comment by InoMurko** [comment]
Oh cool. There’s room for improvement. We can 10x that value to 8000!

**Comment by jbunce** [comment]
deffo

**Comment by jbunce** [comment]
Top by bandwidth usage:

```
eth_getBlockByNumber
5.49GB 50.95%
eth_call
2.47GB 22.95%
eth_getLogs
1.55GB 14.35%
eth_getTransactionByHash
1.11GB 10.28%
eth_getTransactionReceipt
162.1MB 1.47%
```

**Comment by pdobacz** [comment]
`eth_getBlockByNumber` is an interesting case, it's used for `status.get` only, from what I see. It's usage is modest in terms of count, but significant in terms of bandwith :thinking:.

**Comment by InoMurko** [comment]
./remind me to ask for statistics a month from now

**Comment by jbunce** [comment]
@InoMurko give me a shout when you're free and I'll show you how to get them
