### ISSUE TITLE
Naming convention not followed for UTXO attribute

### ISSUE THREAD

**Issue by thec00n** [omisego/elixir-omg#1269]
### Description 

Querying the endpoint `/account.get_utxos` returns all UTXOs for an address. One of the attributes is called `owner`. This attribute is called `outputGuard` according to the Payment Transaction spec: https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/docs/integration-docs/integration-doc.md#payment-transction-eip-712-signing. A mixed naming convention is confusing and can lead to errors, it should therefore be changed to `outputGuard`.

**Comment by jrhite** [comment]
I'd like to add on an additional nitpick to this request. Throughout this repo in the code, the `outputGuard` is also called `address` and `owner`. The actual DB table/column being filtered on is `txoutputs.owner`.

I'd recommend renaming the variable to `owner_address` throughout the code, but no need to change the DB column name. There is likely a reason behind the name `outputGuard` which I'm unaware of, but it would make sense to  me to also change this name to `owner_address`.

**Comment by unnawut** [comment]
Dup of https://github.com/omisego/elixir-omg/issues/1237
