### ISSUE TITLE
docker dependency on localchain_contract_addresses.env

### ISSUE THREAD

**Issue by kevsul** [omisego/elixir-omg#1272]
docker-compose.yml references the `localchain_contract_addresses.env` file which means that none of the docker commands or make targets that use docker will work if this file hasn't been generated yet.

The way to generate it is to call `make init_test` which is not very intuitive if you're not running tests.
For example, the README says that to bring the entire system up, run `docker-compose up` but this doesn't work if you haven't run `make init_test` first.

**Comment by InoMurko** [comment]
I have used one of my open PR's to quickly edit the README on the front page: https://github.com/omisego/elixir-omg/blame/master/README.md#L41
This slipped me when I introduced snapshots. 

What would make this more process more intuitive? It seems to me we should rewrite our documentation that reference docker-compose commands and use just Makefile. At least in our docs we would be able to maintain a flow that works.

**Comment by unnawut** [comment]
I havn't tried but I think it's possible to somehow include the file generation with `docker-compose up`. 

One unelegant idea is a short live container that checks & generates the file on `up`.

**Comment by jrhite** [comment]
We're using a Makefile as script, a bit odd, but about the issue, since
we're using a Makefile can't we use it for its strength in this case?

Makefile

target: target_dependency_1 target_dependency_2
    do stuff after dependencies are done first

Whatever commands require the env file, just add init_test Makefile target
as a dependency.

Would that work?
