### ISSUE TITLE
Potential Dos on account.get_utxo because it doesn't have limit

### ISSUE THREAD

**Issue by jarindr** [omisego/elixir-omg#1274]
account.get_utxo endpoint doesn't have limit on numbers of items returned. this can break the whole watcher when get dos on an account that has high number of utxo

**Comment by unnawut** [comment]
Relates to https://github.com/omisego/elixir-omg/issues/1257

**Comment by pnowosie** [comment]
IMHO there is no link between #1257 and this #1274, info’s get_utxos and security’s get_exitable_utxo are different endpoints

**Comment by unnawut** [comment]
> IMHO there is no link between #1257 and this #1274, info’s get_utxos and security’s get_exitable_utxo are different endpoints

Ah sorry I didn't put why I thought they're related. Yup agree that they're different endpoints.

The only relation is that the discussions that took place were on utxos retrieval but there are actually 2 separate places to fix. So adding a relation here so we don't mistake fixing only one issue being "the utxos retrieval issue is solved"

I've added this reasoning to my old comment above. Thanks!

**Comment by unnawut** [comment]
Fixed by https://github.com/omisego/elixir-omg/pull/1436
