### ISSUE TITLE
Watcher UX: status after deleting IFE

### ISSUE THREAD

**Issue by nicholasmueller** [omisego/elixir-omg#1279]
scenario:
- bob starts ife
- nobody piggybacks, wait for first phase of challenge period to pass
- call deleteNonPiggybackedInFlightExit on paymentExitGame contract
- bob gets his bond back, ife is cleared, calling process exits confirms that no exits exist in the queue

issue:
`status.get` still shows the IFE. shouldn't the exit be cleared from the `in_flight_exits` array?

reference:
"One can call this to release the bond back to its owner and clean up the state of in-flight exit. "
https://github.com/omisego/plasma-contracts/blob/914b6ebf7897826872eb684db40db0081b4d3abb/plasma_framework/docs/integration-docs/integration-doc.md#delete-an-in-flight-exit

**Comment by pdobacz** [comment]
Yep, thanks for raising this. This is a known issue, from before the times when `deleteNonPiggybacked...` was around. See https://github.com/omisego/elixir-omg/issues/811#issuecomment-523951102 

> An IFE that is started but never piggybacked will timeout tacitly and hence remain in the report forever (I think same happens if the piggyback is done but challenged)

I think we can track this particular effort in this issue. I'll make the respective notes in #811

**Comment by thec00n** [comment]
Additionally the watcher informs that deleted IFEs can be piggy backed.

**Comment by pdobacz** [comment]
Let's track in here pls. I think the gist of this here is tracking `deleted` state of an IFE which would suppress all the response data about this IFE:
 - piggyback available
 - in flight exit
 - invalid piggybacks
 - canonicity challenges required

**Comment by pdobacz** [comment]
I think this should be tackled in conjunction with #1318 - IFE being deleted should just be modeled explicitly as yet another state of an IFE.
