### ISSUE TITLE
The watcher does not recognize when an IFE is deleted 

### ISSUE THREAD

**Issue by thec00n** [omisego/elixir-omg#1300]
IFEs can be deleted with `PaymentExitGame.deleteNonPiggybackedInFlightExit()` if they are not piggybacked in time so that a user may get his bond back. The watcher does not recognize the event consistently and reports that deleted IFEs are ongoing when querying the `/status.get`. IFEs are listed in the `in_flight_exits` and `byzantine_events` sections of the response.

**Comment by pdobacz** [comment]
duplicate of https://github.com/omisego/elixir-omg/issues/1279
