### ISSUE TITLE
insert_all_chunked fails with high txn volumes

### ISSUE THREAD

**Issue by jrhite** [omisego/elixir-omg#1355]
`OMG.WatcherInfo.DB.Repo.insert_all_chunked/3` fails when there is a high number of txns per block and the block is inserted into postgres. There error is:

`(Postgrex.QueryError) postgresql protocol can not handle 80010 parameters, the maximum is 65535`

Two new columns were added to each table, `inserted_at` and `updated_at`, and they are not taken into account when the chunk size is calculated. Relevant code is here:

https://github.com/omisego/elixir-omg/blob/v0.4.3/apps/omg_watcher_info/lib/omg_watcher_info/db/repo.ex#L35-L44

The inserted chunks then exceed postgres limits and insertion fails.

**Comment by jrhite** [comment]
Just to link things up this regression was caused by https://github.com/omisego/elixir-omg/pull/1322

**Comment by pnowosie** [comment]
Since PR #1356 is merged I'm closing the issue. Reopen if needed.
