### ISSUE TITLE
Watcher-info error when applying blocks with large number of transactions

### ISSUE THREAD

**Issue by kevsul** [omisego/elixir-omg#1378]
During load testing, blocks with ~50K transactions were created. 
The watcher-info got errors when adding them to its DB

Error logs here:
https://app.datadoghq.com/logs?cols=core_host%2Ccore_service&event&from_ts=1583403960000&index=main&live=false&messageDisplay=inline&query=host%3A%2Astress%2A+service%3Awatcher_info&saved_view=80142&stream_sort=desc&to_ts=1583404080000

**Comment by pdobacz** [comment]
Thanks for reporting this.

```
  | Mar 05 11:27:54.924 | ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
```
and

```
  | Mar 05 11:27:54.826 | 2020-03-05 10:27:54.825 [error] module=DBConnection.Connection function=disconnect/2 ⋅Postgrex.Protocol (#PID<0.2178.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.13007.9> timed out because it queued and checked out the connection for longer than 60000ms
```
Seem to be the most relevant lines there.

Posting the entire log for search-ability and in case DD prunes those logs.

```
Mar 05 11:27:54.925 | 2020-03-05 10:27:54.924 [info] module=OMG.WatcherInfo.BlockApplicationConsumer function=init/1 ⋅Started OMG.WatcherInfo.BlockApplicationConsumer⋅
-- | --
  | Mar 05 11:27:54.925 | Last message: {:internal_event_bus, :block_received, %OMG.Watcher.BlockGetter.BlockApplication{eth_height: 7458996, eth_height_done: true, hash: <<30, 193, 91, 27, 152, 231, 164, 76, 213, 201, 183, 43, 222, 213, 90, 14, 92, 177, 161, 49, 53, 208, 46, 205, 95, 142, 1, 232, 158, 136, 23, 169>>, number: 3044000, timestamp: 1583403962, transactions: [%OMG.State.Transaction.Recovered{signed_tx: %OMG.State.Transaction.Signed{raw_tx: %OMG.State.Transaction.Payment{inputs: [{:utxo_position, 3043000, 12227, 0}], metadata: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, outputs: [%OMG.Output{amount: 76, currency: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, output_type: 1, owner: <<247, 194, 56, 215, 4, 38, 138, 67, 55, 75, 170, 99, 119, 115, 210, 165, 28, 4, 204, 55>>}, %OMG.Output{amount: 1, currency: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, output_type: 1, owner: <<107, 204, 0, 231, 10, 10, 116, 55,
  | Mar 05 11:27:54.925 | (stdlib) timer.erl:181: :timer.tc/2
  | Mar 05 11:27:54.925 | (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
  | Mar 05 11:27:54.925 | (ecto_sql) lib/ecto/adapters/sql.ex:887: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
  | Mar 05 11:27:54.925 | (omg_watcher_info) lib/omg_watcher_info/db/block.ex:206: anonymous fn/4 in OMG.WatcherInfo.DB.Block.insert_with_transactions/1
  | Mar 05 11:27:54.924 | (elixir) lib/enum.ex:769: Enum.each/2
  | Mar 05 11:27:54.924 | (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
  | Mar 05 11:27:54.924 | (ecto_sql) lib/ecto/adapters/sql.ex:551: Ecto.Adapters.SQL.execute/5
  | Mar 05 11:27:54.924 | (ecto_sql) lib/ecto/adapters/sql.ex:618: Ecto.Adapters.SQL.raise_sql_call_error/1
  | Mar 05 11:27:54.924 | ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
  | Mar 05 11:27:54.924 | 2020-03-05 10:27:54.911 [error] module=gen_server function=error_info/7 ⋅GenServer OMG.WatcherInfo.BlockApplicationConsumer terminating
  | Mar 05 11:27:54.827 | ⋅
  | Mar 05 11:27:54.827 | (ecto_sql) lib/ecto/adapters/postgres/connection.ex:80: Ecto.Adapters.Postgres.Connection.execute/4
  | Mar 05 11:27:54.827 | (db_connection) lib/db_connection.ex:596: DBConnection.execute/4
  | Mar 05 11:27:54.827 | (db_connection) lib/db_connection.ex:1255: DBConnection.run_execute/5
  | Mar 05 11:27:54.827 | (db_connection) lib/db_connection/holder.ex:277: DBConnection.Holder.holder_apply/4
  | Mar 05 11:27:54.827 | (postgrex) lib/postgrex/protocol.ex:1652: Postgrex.Protocol.bind_execute/4
  | Mar 05 11:27:54.827 | (postgrex) lib/postgrex/protocol.ex:1759: Postgrex.Protocol.recv_bind/3
  | Mar 05 11:27:54.827 | (postgrex) lib/postgrex/protocol.ex:2706: Postgrex.Protocol.msg_recv/4
  | Mar 05 11:27:54.827 | :prim_inet.recv0/3
  | Mar 05 11:27:54.826 | #PID<0.13007.9> was at location:
  | Mar 05 11:27:54.826 | 2020-03-05 10:27:54.825 [error] module=DBConnection.Connection function=disconnect/2 ⋅Postgrex.Protocol (#PID<0.2178.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.13007.9> timed out because it queued and checked out the connection for longer than 60000ms
  | Mar 05 11:26:56.959 | 2020-03-05 10:26:56.900 [info] module=OMG.Watcher.BlockGetter function=handle_continue/2 trace_id=7191031133078255436 ⋅Applied block: #3045000, from eth height: 7458997 with 304 txs⋅
  | Mar 05 11:26:56.624 | 2020-03-05 10:26:56.620 [info] module=OMG.Watcher.BlockGetter function=handle_continue/2 trace_id=7191031133078255436 ⋅Applied block: #3044000, from eth height: 7458996 with 53606 txs⋅
  | Mar 05 11:26:36.298 | 2020-03-05 10:26:36.296 [info] module=OMG.Eth.EthereumHeight function=handle_info/2 ⋅Got a newHeads event for new Ethereum height 7459000. (log every 1000)⋅
  | Mar 05 11:26:19.154 | 2020-03-05 10:26:19.153 [info] module=OMG.Watcher.BlockGetter.Core function=log_downloading_blocks/2 trace_id=6203027363742441436 ⋅Child chain seen at block #3046000. Downloading blocks [3045000]⋅
  | Mar 05 11:26:16.009 | 2020-03-05 10:26:16.008 [info] module=OMG.Watcher.BlockGetter.Core function=log_downloading_blocks/2 trace_id=444212641843487053 ⋅Child chain seen at block #3045000. Downloading blocks [3044000]⋅
  | Mar 05 11:26:04.072 | 2020-03-05 10:26:04.071 [info] module=OMG.Watcher.BlockGetter function=handle_continue/2 trace_id=1031929842573222801 ⋅Applied block: #3043000, from eth height: 7458993 with 12528 txs⋅
  | Mar 05 11:26:00.642 | 2020-03-05 10:26:00.641 [info] module=OMG.Watcher.BlockGetter function=handle_continue/2 trace_id=1031929842573222801 ⋅Applied block: #3042000, from eth height: 7458993 with 9071 txs⋅

```

**Comment by jrhite** [comment]
Here is the data view I saved.

https://app.datadoghq.com/logs/patterns?cols=service%2Chost%2C%40env&from_ts=1583403855601&index=main&live=false&messageDisplay=inline&query=host%3A%2Astress%2A+-service%3Ablockexplorer&saved_view=82904&stream_sort=desc&to_ts=1583404060347

For CC, I don't see any problems outside itself and Elixir runtime errors, CPU usage and mem usage looked ok.

For watcher-info, the gce-proxy shows dropped connections would might explain the watcher-info issues.

**Comment by jrhite** [comment]
@jbunce could someone on devops help us take a look at this.

In DD, I saw gce-proxy reset the connection 2 or 3 times during heavy load: `2020/03/05 10:25:49 Instance omisego-development:asia-southeast1:stress-e043a92-ropsten-01-pg closed connection`

It seems like it might be related to the DB connection errors.

Thanks.

**Comment by boolafish** [comment]
This happens often to our another test too. With 1000 concurrency hitting watcher info by calling some radom account related apis and then `/transaction.create` + `/transaction.submit_typed`.

This test is not that aggresive but still brings the error quite often

**Comment by jbunce** [comment]
I believe it's a similar condition to https://github.com/elixir-ecto/ecto/issues/1658

**Comment by jbunce** [comment]
@kevsul @pdobacz were you able to replicate by changing the timeout values in the Watcher?

**Comment by jbunce** [comment]
On `0.4.7+c9b5371"` with a load test at 2000 TPS this exception was experienced again:

```
Postgrex.Protocol (#PID<0.3787.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.3789.0> timed out because it queued and checked out the connection for longer than 60000ms
#PID<0.3789.0> was at location:
    (ecto 3.3.4) lib/ecto/query/planner.ex:550: anonymous fn/6 in Ecto.Query.Planner.traverse_cache/4
    (ecto 3.3.4) lib/ecto/query/planner.ex:1442: anonymous fn/3 in Ecto.Query.Planner.traverse_exprs/4
    (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.3.4) lib/ecto/query/planner.ex:545: Ecto.Query.Planner.plan_cache/3
    (ecto 3.3.4) lib/ecto/query/planner.ex:202: Ecto.Query.Planner.plan/3
    (ecto 3.3.4) lib/ecto/query/planner.ex:118: Ecto.Query.Planner.query/5
    (ecto 3.3.4) lib/ecto/repo/queryable.ex:176: Ecto.Repo.Queryable.execute/4
    (elixir 1.10.2) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
```

@InoMurko says:

```
client #PID<0.17666.0> timed out because it queued and checked out the connection for longer than 60000ms
means that the client (a process) took a connection from the pool and hold on it for more then 60 seconds, but the pool demands that the connection is returned in less then 60 seconds.
```

To replicate: run 2000 TPS for 15 minutes.

**Comment by InoMurko** [comment]
What is the postgres and elixir node hardware setup @jbunce ?

**Comment by jbunce** [comment]
Details in https://github.com/omisego/security-issues/issues/37

**Comment by pnowosie** [comment]
I did some further optimization effort in #723, but in the midst of more important changes PR haven't gone through. 

More thoughts 
- we finally splitted Watcher & Watcher-Info, which mean previous assumptions might be outdated.
- it might have no sense to chase a few more micro-optimizations, but otherwise rethink the task again

**Comment by pgebal** [comment]
@pnowosie why did you stated in #723 that `Improvement observed by test are not significant enough to risk a change.`? What is the risk?

**Comment by pnowosie** [comment]
We're risking to introduce bugs. At the time the PR was evaluated it was considered not worth to merge. I think it was good decision as now we're in the position we can rethink our options instead of pushing just another optimization.
(Right now data import is done outside of Watcher's `BlockGetter.apply_block`)

**Comment by pgebal** [comment]
We could do without the atomic writes in Watcher Info. To do things in non-atomic way we have to:
- solve issue https://github.com/omisego/security-issues/issues/42, we need to make sure that a block and transactions are eventually inserted into the database. That is not straightforward to solve (for me, all ideas how to solve that are welcomed)
- accept a tradeoff of having inconsistent replies from Watcher Info. Unless a block and all its transactions and utxos are saved in the db we can have API responses where for example: block is returned but utxos or transactions are not available yet(that should be a short period of time)

Second option is to try to optimize the code (as in Papa Paweł's old PR).
@T-Dnzt @pnowosie @InoMurko

**Comment by InoMurko** [comment]
So two days of looking at this issue, I don’t think a solution exists (in code) that would somehow optimize the query and increase the performance by 1000% or whatever we need. Inserts are not really slow, the `TxOutput.spend_utxos` which performs a lot of updates.

If anyone is thinking about indexes, indexes actually slow down the update, because it needs to rebalence the index every delete+insert (update).
I don't have much knowledge about Postgres so if someone else feels confident, take another look.

On the other hand, #42 is more easily solvable. The consumer receives blocks from the bus and puts the whole block in the DB into a queue. Another consumer step by step takes blocks from this queue and does the `insert_with_transactions`.
