### ISSUE TITLE
Deposit recognized but can not be spent

### ISSUE THREAD

**Issue by thec00n** [omisego/elixir-omg#1394]
### Description 
In the current audit env, I have created three deposits but only one (2000000000000) can be spent for user 0xd42b31665b93c128541c8b89a0e545afb08b7dd8, the other two (1000000000,2000000000) return an error `utxo_not_found` . This might be related to https://github.com/omisego/elixir-omg/issues/1392.

**Comment by InoMurko** [comment]
EHM, #1392 is only to relation to Datadog. Ethereum event listeners would be unaffected by #1392.

**Comment by kevsul** [comment]
The childchain didn't see the first 2 deposits that were sent at 
 `Mar-16-2020 06:55:54 AM +UTC` and `Mar-16-2020 06:56:39 AM +UTC`. 

https://ropsten.etherscan.io/tx/0x44f156081fdc7238fe77f8281e11b9f1d81b63cd873618b554972591c0d1ebb1,
https://ropsten.etherscan.io/tx/0xf430a36e481334f373729238bda8256eab5fcd97aac9ad3209e1dd2af2782045

However, it looks like the childchain was in the process of starting at that time - is it possible that you sent the deposits before the childchain started?

@unnawut  If that ☝️  happened, should the childchain check past deposit events, or does it assume that there are no deposits before it starts?

**Comment by InoMurko** [comment]
ChildChain and Watcher start processing blocks **from** the block height that the rootchain contract were deployed.

**Comment by kevsul** [comment]
Hmm, then in that case I don't know why it missed the deposits from those 2 transactions. Any ideas?

**Comment by InoMurko** [comment]
I can take a look tomorrow if @unnawut doesn't beat me to it.

**Comment by kevsul** [comment]
More info.

The childchain started twice. On the first start, there's this log:
```
Started OMG.EthereumEventListener for depositor, synced_height: 7528576
```
The contracts were deployed at block `7527732`
From the code here https://github.com/omisego/elixir-omg/blob/6a4c2bcc6d0989b8a1f771b95d107c741af06abf/apps/omg/lib/omg/ethereum_event_listener.ex#L92-L117
it looks like `synced_height` should be the same as `contract_deployment_height` (because it's the first start of the child chain) but it's not.

So the first question is, is that the problem or am I misunderstanding the code?


On the second childchain start (30 mins later) we see
```
Started OMG.EthereumEventListener for depositor, synced_height: 7528713
```

The missing deposit txs were at blocks `7528688` and `7528692`, which was in between the 2 starts.

For an added twist, the watcher_info *did* recognize the first of these deposits, but neither the childchain nor the watcher did.

**Comment by pdobacz** [comment]
Re the first oddity you mention @kevsul 



I think there has been a start before that:

```
2020-03-16 05:56:01.053 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Started OMG.EthereumEventListener for depositor, synced_height: 7527721⋅
```

> The childchain started twice. On the first start, there's this log:
> 
> ```
> Started OMG.EthereumEventListener for depositor, synced_height: 7528576
> ```
> 
> The contracts were deployed at block `7527732`

**Comment by InoMurko** [comment]
Which cluster are we looking at?
`audit-a69c763`
or
`gke-audit-7c3f796-r`

**Comment by InoMurko** [comment]
PS: This naming is truly exceptional.

**Comment by pdobacz** [comment]
One more thing I pick up is that the missed deposit (the latter *8692 one) should have been recognized at height *8702 - 10 blocks of `deposit_finality_margin` later.

This seems to be [this](https://ropsten.etherscan.io/block/7528702) mined at Mar-16-2020 06:58:59 AM +UTC.

The restart seems to have come _after_ then: `2020-03-16 07:04:51.881 [info] ⋅SIGTERM received - shutting down`

So the logs/recognition should have been seen before this restart.

`watcher-info` recognized those after a restart, it seems went offline earlier and the *8792 block recognition came after. Not sure if this means anything though...

**Comment by pdobacz** [comment]
> Which cluster are we looking at?
> `audit-a69c763`

I'm looking at this one :), I think Kevin too

**Comment by pdobacz** [comment]
another find (not yielding any cause of the problem though):

https://ropsten.etherscan.io/block/7528723 this block is timed Mar-16-2020 07:04:00 AM +UTC which is when the chch restarted. This minus 10 blocks of margin is where the `depositor` left off on restart, as seen from:



> On the second childchain start (30 mins later) we see
> 
> ```
> Started OMG.EthereumEventListener for depositor, synced_height: 7528713
> ```

so this makes sense. The chch didn't recognize the 2 events but marked this portion of the blockchain as synced up to before the restart.

**Comment by kevsul** [comment]
> I think there has been a start before that:
> 
> ```
> 2020-03-16 05:56:01.053 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Started OMG.EthereumEventListener for depositor, synced_height: 7527721⋅
> ```

I do not see that log anywhere?!

> 
> Also the contracts were deployed at 7527721 https://ropsten.etherscan.io/tx/0xb030d74ee7302458aaf83434af5fff38b2061cb144bfb278fef175665c8f0a25, maybe you're picking up the deployment of some auxiliary contract (vault?)

Yes, I'm looking at the vault

**Comment by InoMurko** [comment]
```
{"application":"omg","erlang_pid":"#PID<0.1674.0>","file":"lib/omg/root_chain_coordinator.ex","function":"handle_continue/2","level":30,"line":79,"module":"Elixir.OMG.RootChainCoordinator","msg":"Starting Elixir.OMG.RootChainCoordinator service.","name":"elixir-omg","pid":1,"time":"2020-03-16T07:05:34.769Z","v":0}
{"application":"omg","erlang_pid":"#PID<0.1674.0>","file":"lib/omg/root_chain_coordinator.ex","function":"handle_continue/2","level":30,"line":91,"module":"Elixir.OMG.RootChainCoordinator","msg":"Started OMG.RootChainCoordinator","name":"elixir-omg","pid":1,"time":"2020-03-16T07:05:34.770Z","v":0}
{"application":"omg","erlang_pid":"#PID<0.1676.0>","file":"lib/omg/ethereum_event_listener.ex","function":"handle_continue/2","level":30,"line":99,"module":"Elixir.OMG.EthereumEventListener","msg":"Starting OMG.EthereumEventListener for depositor.","name":"elixir-omg","pid":1,"time":"2020-03-16T07:05:34.770Z","v":0}
{"application":"omg","erlang_pid":"#PID<0.1677.0>","file":"lib/omg/ethereum_event_listener.ex","function":"handle_continue/2","level":30,"line":99,"module":"Elixir.OMG.EthereumEventListener","msg":"Starting OMG.EthereumEventListener for in_flight_exit.","name":"elixir-omg","pid":1,"time":"2020-03-16T07:05:34.771Z","v":0}
{"application":"omg","erlang_pid":"#PID<0.1678.0>","file":"lib/omg/ethereum_event_listener.ex","function":"handle_continue/2","level":30,"line":99,"module":"Elixir.OMG.EthereumEventListener","msg":"Starting OMG.EthereumEventListener for piggyback.","name":"elixir-omg","pid":1,"time":"2020-03-16T07:05:34.771Z","v":0}
{"application":"omg","erlang_pid":"#PID<0.1679.0>","file":"lib/omg/ethereum_event_listener.ex","function":"handle_continue/2","level":30,"line":99,"module":"Elixir.OMG.EthereumEventListener","msg":"Starting OMG.EthereumEventListener for exiter.","name":"elixir-omg","pid":1,"time":"2020-03-16T07:05:34.771Z","v":0}
{"application":"omg","erlang_pid":"#PID<0.1676.0>","file":"lib/omg/ethereum_event_listener.ex","function":"handle_continue/2","level":30,"line":116,"module":"Elixir.OMG.EthereumEventListener","msg":"Started OMG.EthereumEventListener for depositor, synced_height: 7528713","name":"elixir-omg","pid":1,"time":"2020-03-16T07:05:34.771Z","v":0}
{"application":"omg","erlang_pid":"#PID<0.1677.0>","file":"lib/omg/ethereum_event_listener.ex","function":"handle_continue/2","level":30,"line":116,"module":"Elixir.OMG.EthereumEventListener","msg":"Started OMG.EthereumEventListener for in_flight_exit, synced_height: 7528713","name":"elixir-omg","pid":1,"time":"2020-03-16T07:05:34.771Z","v":0}
{"application":"omg","erlang_pid":"#PID<0.1679.0>","file":"lib/omg/ethereum_event_listener.ex","function":"handle_continue/2","level":30,"line":116,"module":"Elixir.OMG.EthereumEventListener","msg":"Started OMG.EthereumEventListener for exiter, synced_height: 7528713","name":"elixir-omg","pid":1,"time":"2020-03-16T07:05:34.771Z","v":0}
{"application":"omg","erlang_pid":"#PID<0.1678.0>","file":"lib/omg/ethereum_event_listener.ex","function":"handle_continue/2","level":30,"line":116,"module":"Elixir.OMG.EthereumEventListener","msg":"Started OMG.EthereumEventListener for piggyback, synced_height: 7528713","name":"elixir-omg","pid":1,"time":"2020-03-16T07:05:34.771Z","v":0}
```

ChildChain started syncing: `7528713`. Deposits happened: 7528688, 7528702 (25 and 11 blocks before CHCH started syncing).
Contracts were deployed 7527721.
Chronologically:
Contracts were deployed `7527721`.
Deposits happened: 7528688, 7528702.
ChildChain started syncing: `7528713`.

**Comment by kevsul** [comment]
But that was the fourth restart of the childchain @InoMurko 

First the child chain started syncing at `7527721`, then again at `7528576` and again at `7528606 `

**Comment by InoMurko** [comment]
Indeed Kevin, my mistake, I did not look at the whole logs:
![Screen Shot 2020-03-19 at 12 17 04](https://user-images.githubusercontent.com/2582555/77062147-9e21f000-69db-11ea-8db0-9f560a576a49.png)

**Comment by InoMurko** [comment]
The chain of events:
```
First start:
2020-03-16 05:56:01.053 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Started OMG.EthereumEventListener for depositor, synced_height: 7527721⋅
Shutdown:
2020-03-16 06:34:44.061 [info] ⋅SIGTERM received - shutting down
Re-Start:
2020-03-16T06:37:39.724Z Started OMG.EthereumEventListener for depositor, synced_height: 7528576
Shutdown:
2020-03-16T06:42:51.208Z SIGTERM received - shutting down
Re-Start:
2020-03-16 06:43:50.814 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Started OMG.EthereumEventListener for depositor, synced_height: 7528606⋅
Deposit 1:
Mar-16-2020 06:55:54 AM +UTC https://ropsten.etherscan.io/tx/0x44f156081fdc7238fe77f8281e11b9f1d81b63cd873618b554972591c0d1ebb1 
Block 7528688 
Deposit 2:
Mar-16-2020 06:56:39 AM +UTC https://ropsten.etherscan.io/tx/0xf430a36e481334f373729238bda8256eab5fcd97aac9ad3209e1dd2af2782045
Block: 7528692
Shutdown:
2020-03-16 07:04:51.881 [info] ⋅SIGTERM received - shutting down
Restart:
2020-03-16T07:05:34.771Z Started OMG.EthereumEventListener for depositor, synced_height: 7528713

```
At this point, we’re already pass deposit eth height and they were not recognized.

**Comment by InoMurko** [comment]
```
startup 1
2020-03-16 05:55:59.554 [info] module=OMG.Eth.Application function=start/2 ⋅Started OMG.Eth.Application, config used: [txhash_contract: "0xb030d74ee7302458aaf83434af5fff38b2061cb144bfb278fef175665c8f0a25", contract_addr: %{erc20_vault: "0xfd3ea082b457c91f513f4a21f9c0dbad3fb30090", eth_vault: "0x712a9a97f4c1902c917a7000eca78f2ec8ceefa0", payment_exit_game: "0x63927b5fcd0edcaab407dc5a8f0b99e3cee0d822", plasma_framework: "0x3d7d6c1a3240a1d3bccd3572e1ce3a2f42d5b656"}, authority_addr: "0xe3223a891a752177e395ff21805387740e04d0d3"]⋅
startup 2
Started OMG.Eth.Application, config used: [contract_addr: %{erc20_vault: "0xfd3ea082b457c91f513f4a21f9c0dbad3fb30090", eth_vault: "0x712a9a97f4c1902c917a7000eca78f2ec8ceefa0", payment_exit_game: "0x63927b5fcd0edcaab407dc5a8f0b99e3cee0d822", plasma_framework: "0x3d7d6c1a3240a1d3bccd3572e1ce3a2f42d5b656"}, txhash_contract: "0xb030d74ee7302458aaf83434af5fff38b2061cb144bfb278fef175665c8f0a25", authority_addr: "0xe3223a891a752177e395ff21805387740e04d0d3"]
startup 3
2020-03-16 06:43:48.458 [info] module=OMG.Eth.Application function=start/2 ⋅Started OMG.Eth.Application, config used: [txhash_contract: "0x71610c61d6d6e699ad4748de7dd476d9ea21be3ce23cb137b12f362d09ed3eef", authority_addr: "0xf4a7870cc9856d5033ff59d319dcb2b1e79da49d", contract_addr: %{erc20_vault: "0xb3eb0a1908ed43dcedf4595702469571bf5e6926", eth_vault: "0xe925830bcbc4504de39c40b8501f96f80172f27c", payment_exit_game: "0x2f99c57a0b96293e21824680c930c80a01bb4e17", plasma_framework: "0x93aad6e19ad694d83116caf7f645911e1bcce878"}]⋅
startup 4
Started OMG.Eth.Application, config used: [authority_addr: "0xe3223a891a752177e395ff21805387740e04d0d3", contract_addr: %{erc20_vault: "0xfd3ea082b457c91f513f4a21f9c0dbad3fb30090", eth_vault: "0x712a9a97f4c1902c917a7000eca78f2ec8ceefa0", payment_exit_game: "0x63927b5fcd0edcaab407dc5a8f0b99e3cee0d822", plasma_framework: "0x3d7d6c1a3240a1d3bccd3572e1ce3a2f42d5b656"}, txhash_contract: "0xb030d74ee7302458aaf83434af5fff38b2061cb144bfb278fef175665c8f0a25"]
startup 1 eth vault
eth_vault: “0x712a9a97f4c1902c917a7000eca78f2ec8ceefa0”
startup 2 eth vault
eth_vault: “0x712a9a97f4c1902c917a7000eca78f2ec8ceefa0"
startup 3 eth vault
eth_vault: “0xe925830bcbc4504de39c40b8501f96f80172f27c”
startup 4 eth vault
 eth_vault: “0x712a9a97f4c1902c917a7000eca78f2ec8ceefa0"
```

**Comment by unnawut** [comment]
@InoMurko So this will be protected after https://github.com/omisego/elixir-omg/pull/1382 is deployed. And for these 2-3 specific deposits, the depositor should IFE their deposits out?

**Comment by InoMurko** [comment]
Yeah 1382 solves this. I’m not sure exactly which exit... SE or IFE.

**Comment by pdobacz** [comment]
SE if no signed spending transactions for that deposit were broadcast.

IFE if any signed spending transactions were broadcast, which I think was the case here.

Also SE if the user has a lot of trust towards the operator :).

**Comment by kevsul** [comment]
These deposits were not spent because they were never recognised by the childchain.
So you can standard exit them, @thec00n

**Comment by kevsul** [comment]
> IFE if any signed spending transactions were broadcast, which I think was the case here.

Oh, you're right @pdobacz - a signed tx was broadcast. 
So yeah, depends on if you trust the operator or not @thec00n 😄

**Comment by unnawut** [comment]
So with the solution from @pdobacz and @kevsul above there's no further stuff to be done on elixir-omg so closing this issue 🎉
