### ISSUE TITLE
Add additional information to the invalid_exit event

### ISSUE THREAD

**Issue by thec00n** [omisego/elixir-omg#1425]
Presently the `invalid_exit` event provides the following information.

```
 [
  {
    "details": {
      "amount": 999999999999997,
      "currency": "0x0000000000000000000000000000000000000000",
      "eth_height": 7585115,
      "name": "invalid_exit",
      "owner": "0x48731f77ef0f0abb324dcbc1768bc75510ab47cf",
      "utxo_pos": 25000000000000
    },
    "event": "invalid_exit"
  }
]
```

It is recommended to add the following information to the event:

- finalization time: At which point in time can a user finalize the exit and process the exit. The time should be provided as timestamp.
- spending tx hash on the plasma chain: the plasma tx that spends the UTXO
- spending tx on the root chain: the Ethereum tx that starts the SE 

This will considerably improve the UX around investigating invalid exits as well as make it easier for auto challenge tools to operate.

**Comment by okalouti** [comment]
Closing and referring to #1480, #1481 and #1482
