### ISSUE TITLE
ignore duplicate events, break down events

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#1426]
Events consumed from Ethereum Event Listeners pushed ontu the OMG Bus, consumed by `OMG.Watcher.DatadogEvent.ContractEventConsumer` and it's sibling in Child Chain can come in bulk.
For example `BlockSubmitted` events can have a list of blocks, that were validated
```
[%{blknum: 150000, eth_height: 9735388, event_signature: "BlockSubmitted(uint256)", log_index: 8, root_chain_txhash: "0x060f9502ed7bad7565a1a668700ff1201f25cbd47c129ae4eba39365be1deaf7"}, %{blknum: 151000, eth_height: 9735415, event_signature: "BlockSubmitted(uint256)", log_index: 67, root_chain_txhash: "0x440f28117a14e55ae373108594c3bb224167f8023241696bf432d39e887fb192"}, %{blknum: 152000, eth_height: 9735447, event_signature: "BlockSubmitted(uint256)", log_index: 72, root_chain_txhash: "0xf1a910b6373f32a96c860c32ad227182d4a6b79a7b06e87cc3d2b3333d0af08a"}]
```

We should break these down into separate events being sent to Datadog, but also keep a local list of events that were also received.

**Comment by pnowosie** [comment]
> For example BlockSubmitted events can have a list of blocks, that were validated

Just clarification. Usually `BlockSubmitted` is a single event. However due to gas price changes, previous block could not be spotted before next one is ready. Then Ch-ch sends both with a higher gas.

**Comment by unnawut** [comment]
@InoMurko So Souradeep is about to start the event dedup part. Something like this?

- Use `root_chain_txhash` as the unique id
- Store the `root_chain_txhash` locally somewhere. This is not super critical so within a genserver state should be enough?
- On new event received, compare the new event with the local store before deciding to push

**Comment by souradeep-das** [comment]
Also, Is there any history of duplicated events that we have received?

**Comment by unnawut** [comment]
Interesting I'm not seeing any log with "*Timestamp:*". I'm looking into it a bit more.

**Comment by souradeep-das** [comment]
@unnawut Do you mean duplicate logs?

**Comment by unnawut** [comment]
Actually I'm not seeing any logs from this code at all

**Comment by souradeep-das** [comment]
Summing up the discussions with O -
- A lot of duplicate events show up in datadog i.e. events about the same activity with only differing timestamp
- Could potentially be an issue with the ethereum event listeners or the OMG bus from where the events are consumed.
- Considering the number of event listeners combined ( around 10+10+4 ), it could be the entity which is producing these hundreds of duplicate events.
- If that is the case, de-duplicating before publishing to DataDog might not be the best approach, since it is among the last consumers of the system.

**Comment by souradeep-das** [comment]
Break down events, fixed in https://github.com/omisego/elixir-omg/pull/1472
Created a new issue to decide on the duplicate events problem: https://github.com/omisego/elixir-omg/issues/1501
So, closing this one.
