### ISSUE TITLE
adapting our code style to new findings

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#1438]
The purpose of this change is to increase readability and testability, reduce complexity and code coupling. As well as our enjoyment of using the codebase (for example, using search in your preferred IDE).
I would like to propose the following amendments to our current code style:
### GenServer complexity
Our current approach in the codebase has been:
- Genserver module
-- Core state module extension
Where the Core module served as an extension of the process state.
This increased testability to a certain point, but not as much as it could.

Proposed change:
- Genserver module
-- Domain specific extensions

* In this case, the domain specific extension module functions do NOT accept full state arguments (struct that represents process state).
* each of the domain specific extensions has a matching test file (without integration tests!) if test are complex enough. If they're rather simple - keep them in the same module as `doctests`
* unless needed because of multiple function headers or binaries, we do not pattern match in function definitions (like breaking up a keyword or map)
* domain specific extension modules must remain pure 
* unless there's no other option, the domain specific extension modules are not to be called core

### Increase the current readability of modules
The Core modules that act as an extension of the process state currently do enjoy particular affection from engineers. I would propose the following ground rules with which we can increase readability:
```
  @doc """
  Marks that child chain block published on `eth_height` was processed
  """
  @spec apply_block(t(), BlockApplication.t()) :: {t(), non_neg_integer(), list()}
  def apply_block(%__MODULE__{} = state, %BlockApplication{
        number: blknum,
        eth_height: eth_height,
        eth_height_done: eth_height_done
      }) do
    _ = Logger.debug("\##{inspect(blknum)}, from: #{inspect(eth_height)}, eth height done: #{inspect(eth_height_done)}")

    if eth_height_done do
      # final - we need to mark this eth height as processed
      state = %{state | synced_height: eth_height}
      {state, eth_height, [{:put, :last_block_getter_eth_height, eth_height}]}
    else
      # not final - this applied child block doesn't wrap up any eth height
      {state, state.synced_height, []}
    end
  end
```
I propose, that we write functions as above like this:
```
  @doc """
  Marks that child chain block published on `eth_height` was processed
  """
  @spec apply_block(t(), BlockApplication.t()) :: {t(), non_neg_integer(), list()}
  def apply_block(state, block_application)) do
    _ = Logger.debug("\##{inspect(block_application.number)}, from: #{inspect(block_application.eth_height)}, eth height done: #{inspect(block_application.eth_height_done)}")

    if block_application.eth_height_done do
      # final - we need to mark this eth height as processed
      state = %{state | synced_height: block_application.eth_height}
      {state, block_application.eth_height, [{:put, :last_block_getter_eth_height, block_application.eth_height}]}
    else
      # not final - this applied child block doesn't wrap up any eth height
      {state, state.synced_height, []}
    end
  end
```

This keeps the functions more concise. Note that there's no reason to re-assure us that specific arguments are of a certain type (and by that, increase clutter). If you would like to be so kind (and I think you should be) and want to help the reader reason about the types - provide him with dialyzer spec!
_Dialyzer specs are not just for the tool - dialyzer, but also for the reader._

### Not a single integration test (referring to massive fixtures) is to be added this point forward. Cabbage is an acceptance criteria.

Timeline cannot be an excuse. The codebase looks like it does and if you're delaying work now, it'll bite you later. Cabbage complexity (learning curve, missing tooling) now needs to be calculated in estimations.
If this proposal is not accepted... we cannot split the codebase in any meaningful way. We cannot introduce elixir 1.10 and we're generally inefficient when it comes to refactoring, rearchitecting, and generally having bad and slow test coverage.

I would like to get votes from team leaders and above: @kasima @T-Dnzt @achiurizo @unnawut @kevsul

**Comment by InoMurko** [comment]
### Processes do not directly access configuration
The pattern I've been pushing throughout the codebase is that process configuration is always passed top to bottom. From one supervisor, to another, from supervisor to the worker process.
DO (we're looking at Supervisor child specification):
```
    exit_processor_sla_margin = Configuration.exit_processor_sla_margin()
    exit_processor_sla_margin_forced = Configuration.exit_processor_sla_margin_forced()
    metrics_collection_interval = Configuration.metrics_collection_interval()
    deposit_finality_margin = OMG.Configuration.deposit_finality_margin()
    min_exit_period_seconds = OMG.Eth.Configuration.min_exit_period_seconds()
    ethereum_block_time_seconds = OMG.Eth.Configuration.ethereum_block_time_seconds()
    
[
      {ExitProcessor,
       [
         exit_processor_sla_margin: exit_processor_sla_margin,
         exit_processor_sla_margin_forced: exit_processor_sla_margin_forced,
         metrics_collection_interval: metrics_collection_interval,
         min_exit_period_seconds: min_exit_period_seconds,
         ethereum_block_time_seconds: ethereum_block_time_seconds
       ]}
]
```
DO not:

```
def init(:ok) do
exit_processor_sla_margin = Application.get_env(:omg_watcher, exit_processor_sla_margin)
ethereum_block_time_seconds = Application.get_env(:omg_watcher, ethereum_block_time_seconds)

ethereum_block_time_seconds = Application.get_env(:omg_watcher, ethereum_block_time_seconds)

    {:ok, db_exits} = DB.exit_infos()
    {:ok, db_ifes} = DB.in_flight_exits_info()
    {:ok, db_competitors} = DB.competitors_info()

    :ok =
      Core.check_sla_margin(
        exit_processor_sla_margin,
        exit_processor_sla_margin_forced,
        min_exit_period_seconds,
        ethereum_block_time_seconds
      )

    {:ok, processor} = Core.init(db_exits, db_ifes, db_competitors, exit_processor_sla_margin)
    {:ok, _} = :timer.send_interval(Application.get_env(:omg_watcher, metrics_collection_interval), self(), :send_metrics)

    _ = Logger.info("Initializing with: #{inspect(processor)}")
    {:ok, processor}
  end
```

The pattern I'm proposing is reducing our exposure to shared resources (application is a global ets table), reducing clutter in the genserver implementation and generally provides better patterns for testing.

### Async testing of processes
Only one named process (with the same name) can exist in the VM. So if we were strict about that all tests testing processes would need to be synchronous. We can avoid that very simply by doing the following:
```
def start_link(args) do
  GenServer.start_link(__MODULE__, args, name: Keyword.get(args, :name,__MODULE__))
end
``` 
This allows us that in unit testing, multiple instances of the process can exist. Better and faster testing!

**Comment by pnowosie** [comment]
IMHO this is very unfortunate that "modules readability" topic is included among the other very important and valid points. I'll constrain myself to refer to the this as it can fade out and distract from the codebase maintainability topic.

I'm suggesting to move the readability topic to the separate issue as the decision on pattern-matching vs struct accessor has minimal or no impact on elixir 1.10 adoption or overall efficiency or testability.

WDYT?
