### ISSUE TITLE
IFEs still in /status.get response after having been processed

### ISSUE THREAD

**Issue by okalouti** [omisego/elixir-omg#1452]
### Description 
The `in_flight_exits` part from `/status.get` still contains IFEs that are already processed and are not no longer in the IFE exit map nor in their receptive token priority queue. I am wondering why they are kept and if there is any value for the client to see past IFEs?

**Comment by pnowosie** [comment]
I can recall a bug in one of the environments where syncing component has failed hence outdated events were still displayed in `/status.get`

I don’t think live system behaves like described in the issue. We have a test shows that after IFE is processed it's not longer available in `/status.get`

https://github.com/omisego/elixir-omg/blob/a75308794c876b080b8d06108b5de878924dce62/apps/omg_watcher/test/omg_watcher/integration/in_flight_exit_test.exs#L222

**Comment by thec00n** [comment]
https://github.com/omisego/security-issues/issues/32

**Comment by InoMurko** [comment]
Addressed in security.
