### ISSUE TITLE
Watcher Info persists in-flight exit events as :standard_exit type

### ISSUE THREAD

**Issue by okalouti** [omisego/elixir-omg#1520]
This came up as I was running the cabbage tests and seeing how exit events were being persisted in the `watcher_info` DB. 

The `ExitConsumer` inserts all exits using  `EthEvent.insert_exits!(data)`. See [here](https://github.com/omisego/elixir-omg/blob/master/apps/omg_watcher_info/lib/omg_watcher_info/exit_consumer.ex).

However, this method takes an `event_type` argument that defaults to `:standard_exit`. See [here](https://github.com/omisego/elixir-omg/blob/7e4a23198d6634140bde90ed18b70439f8464794/apps/omg_watcher_info/lib/omg_watcher_info/db/eth_event.ex#L111).

However, no differentiation is made in the ExitConsumer.

cc: @pnowosie

**Comment by pnowosie** [comment]
Thanks @okalouti 
It slipped out despite [the tests](https://github.com/omisego/elixir-omg/blob/a72aa5102d2fe29baa3a2ebcb2887a63fb003108/apps/omg_watcher_info/test/omg_watcher_info/db/eth_event_test.exs#L280) which makes me think that we should expose `TxOutput`'s `events` from `/transaction.get` 🤔 (or smth else) to allow us to test it properly.

**Comment by okalouti** [comment]
I think the most straightforward fix is to differentiate in the exit consumer?

**Comment by okalouti** [comment]
Because insert_exits is behaving as it was designed to. Though we could perhaps remove the default argument.
