### ISSUE TITLE
Allow overriding docker-compose variables with .env file

### ISSUE THREAD

**Issue by kartsims** [omisego/elixir-omg#1552]
The way env variables are currently passed through `docker-compose*.yml` files doesn't allow to override ETH adresses and variables in general via a `.env` file

This feature would be convenient for instance if we wanted to keep the repo up-to-date while without altering the docker-compose file.

In my case I would like to be able to specify another authority address, without changing the `docker-compose-watcher.yml` file (to use the [last known connection details](https://docs.omg.network/network-connection-details)) .

The way this could be done would be by using bash substition syntax:

```
    environment:
...
      - ETHEREUM_NETWORK=${OMG_ETHEREUM_NETWORK:-ROPSTEN}
      - AUTHORITY_ADDRESS=${OMG_AUTHORITY_ADDRESS:-0xecec123f5cdbc0046a3e4d94223bb120dd3cb7b9}
```

**Comment by kartsims** [comment]
should have tested the behavior of docker-compose vars before submitting this issue, this is not necessary, sorry

**Comment by unnawut** [comment]
Also you may want to consider the more idiomatic [`docker-compose.override.yml`](https://docs.docker.com/compose/extends/#multiple-compose-files)
