### ISSUE TITLE
Problem with Browser interaction with Childchain and Watcher due to CORS issue

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#156]
I got the following errors, 

`Failed to load http://localhost:4000/account/utxo?address=0x0b547a50e73f3b91741539ede4474ed1d36522e9: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.`

It appears CORS is not setup on the server side, so the browser cannot query the watcher.

Got same problem locally on my machine as well as the staging server

**Comment by pnowosie** [comment]
Hey @Pongch 
reason we intentionally didn't included CORS headers in wallet provider's responses is we see it as plasma chain validator at first. 
Can you see a usecase which we should consider regarding cors?
Thanks!

**Comment by pnowosie** [comment]
As agreed [here](https://github.com/omisego/elixir-omg/pull/264#discussion_r234138227) we will implement CORS support for Watcher. I'm creating chore for it.
