### ISSUE TITLE
Watcher not showing available UTXOs for deposits to Plasma contract

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#157]
After following the steps within `demo_01` to depositing ETH on Plasma, UTXOs are not showing as available upon queries on the watcher until the initial transaction is made on the Plasma chain

**Comment by kevsul** [comment]
@pnowosie What's the status of this issue?
We have a workaround for it in the omg-js lib at the moment, but we're going to publish this lib soon and it would be nice not to have to include the workaround in the code.

**Comment by kasima** [comment]
This is in flight in Pivotal Tracker.
