### ISSUE TITLE
Watcher API responses redefinition

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#266]
I'd like to start a discussion to redefine data WatcherAPI returns to make it align better for new database structure.

**Proposed changes**
 * Added Plasma's `Block` definition
 * Changed `Transaction` definition for 4in/4out and reuse other definitions
 * New definition of `TransactionItem` - list of transaction items with less data
 * Changed `Utxo` definition - added `owner` and removed `txbytes`

You can take a look at swagger definition changes in [commit](https://github.com/omisego/elixir-omg/commit/b672df4537c10f29418a6c2c4cb0f694e91c029d) or review it in [SwaggerUI](https://petstore.swagger.io/?url=https%3A%2F%2Fs3-eu-west-1.amazonaws.com%2Fwatcher-api%2Fswagger.json#/)

**Comment by jarindr** [comment]
I love this, some question before we go further:
- why do we choose to rename `transaction` to `transactionItem`

**Comment by pnowosie** [comment]
Yeah - sorry it's a little hard to think of it from git-diff. 
So `Transaction` is there as well and contains mostly the same data but nicely structured.
`TransactionItem` is a new structure for items of the list of transactions (e.g.: `/transactions?address=`) and is limited to most important data.

**Comment by kevsul** [comment]
I understand that you want to reduce the amount of data returned for each transaction in the list, but I wonder if the reduced data is useful at all?

I can think of 2 reasons you would want to get a list of txs for an account: a BlockExplorer and a Wallet. In both cases you would want to show the value (and currency) of the tx, and whether it's incoming or outgoing
e.g. [0x742d35cc6634c0532925a3b844bc454e4438f44e](https://etherscan.io/address/0x742d35cc6634c0532925a3b844bc454e4438f44e)

It's a lot of traffic if the client has to make separate call for each transaction to get the missing details...

You _could_ try to calculate the value in the watcher and add that to TransactionItem. But I'd be inclined to just send the entire Transaction and let the client do it.

**Comment by pnowosie** [comment]
I can agree to the point that whether transaction list is filtered by particular account address, at least direction currency and amount of value (sent/received) by address is the interesting part.
However in more general case with *n-inputs* and *k-outputs* this is probably a waste of throughput as we couldn't present these data on the list.

**Comment by kevsul** [comment]
Ok, so if the address is passed in, then the server can calculate `value`, `currency` and `direction` and include them in the returned data. `value` is the amount sent or received by the address.

If the address isn't passed in then `direction` is meaningless, and `value` is the sum of all the outputs.

Note that `value` is slightly different in each case...

**Comment by pnowosie** [comment]
Yeah, what adds even more complexity here is there could be different currencies used in the inputs & outputs - so summing them up isn't possible...

**Comment by pnowosie** [comment]
Closing as API specification already defines data for the Watcher endpoints
