### ISSUE TITLE
Watcher does not apply blocks

### ISSUE THREAD

**Issue by pik694** [omisego/elixir-omg#284]
After running watcher for a couple of hours it then stops to sync. It fails to apply one block. 

The investigation showed that is is caused by the fact that submission of the block is missing.

**Comment by pik694** [comment]
This is caused by: 
https://github.com/ethereum/go-ethereum/issues/18198

**Comment by paulperegud** [comment]
We should consider running separate geth instances for operator and watcher.

**Comment by pdobacz** [comment]
didn't manifest itself after some upgrades (new geth, changes to watcher etc.). No way to track more.

Note for self: see OMG-323 internally for details
