### ISSUE TITLE
Cannot create an authority address

### ISSUE THREAD

**Issue by myvidster** [omisego/elixir-omg#332]
Getting error when attempting to create an authority address.

mix run --no-start -e  '
   contents = OMG.Eth.DevHelpers.prepare_env!() |> OMG.Eth.DevHelpers.create_conf_file()
   "~/config.exs" |> Path.expand() |> File.write!(contents)
 '

** (MatchError) no match of right hand side value: {:ok, %{"blockHash" => "0x9c6fddc0789f756fa796bc3119fe411e49150410e1557d4da16e4eccf4597a82", "blockNumber" => "0xcbb", "contractAddress" => "0xf13d901d39c263cac2a63dc5c2d0c0c9cd6f93f1", "cumulativeGasUsed" => "0x3fc820", "from" => "0x43f9925f9e7775e974524953cbc28df7c6876b9c", "gasUsed" => "0x3fc820", "logs" => [], "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status" => "0x0", "to" => nil, "transactionHash" => "0xf6751a93fed5c4ae6a85786df5d7f68f52424bb45cc23226f01e877d07bc9f95", "transactionIndex" => "0x0"}}
    test/support/dev_helpers.ex:98: OMG.Eth.DevHelpers.transact_sync!/1
    test/support/dev_helpers.ex:107: OMG.Eth.DevHelpers.deploy_sync!/1
    test/support/dev_helpers.ex:49: OMG.Eth.DevHelpers.prepare_env!/1
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:411: :erl_eval.expr/5
    (stdlib) erl_eval.erl:449: :erl_eval.expr/5
    (stdlib) erl_eval.erl:126: :erl_eval.exprs/5
    (elixir) lib/code.ex:232: Code.eval_string/3
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (mix) lib/mix/tasks/run.ex:142: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2

I also had to change the tree id for the plasma contract branch, I used the tree id: f2f0b4793a1ee07a5a2aeb86fe4d8f1df83a86aa by updating elixir-omg/mix.lock with the new id.  If this is causing my issue then which id should i use?  The existing one was failing the build.

**Comment by myvidster** [comment]
The docker install appear to work.

 docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                          PORTS                                                    NAMES
4c25adee799a        elixir-omg:dockercompose             "/bin/bash -c './lauâ¦"   31 minutes ago      Restarting (1) 25 seconds ago                                                            elixiromg_watcher_1
b4b8db67c4e6        elixir-omg:dockercompose             "/bin/bash -c './lauâ¦"   31 minutes ago      Restarting (1) 27 seconds ago                                                            elixiromg_childchain_1
4420eb9674f1        jakebunce/contractexchanger:v0.0.1   "./server.py"            31 minutes ago      Up 31 minutes                   0.0.0.0:5000->5000/tcp                                   elixiromg_contractexchanger_1
417804ec39c8        omisego/ewallet:latest               "/bin/bash -c 'mix lâ¦"   31 minutes ago      Up 2 seconds                    4369/tcp, 6900-6909/tcp, 0.0.0.0:4001->4000/tcp          elixiromg_ewallet_1
e68bf11c5f37        ethereum/client-go:v1.8.20           "/bin/sh -c 'geth --â¦"   31 minutes ago      Up 31 minutes                   8546/tcp, 0.0.0.0:8545->8545/tcp, 30303/tcp, 30303/udp   elixiromg_geth_1
42d84ea39938        postgres                             "docker-entrypoint.sâ¦"   31 minutes ago      Up 20 minutes                   0.0.0.0:5432->5432/tcp                                   elixiromg_childchain_db_1
745bd478a982        postgres                             "docker-entrypoint.sâ¦"   31 minutes ago      Up 31 minutes                   0.0.0.0:5433->5432/tcp                                   elixiromg_watcher_db_1

I have never used docker containers before and I want to play with the child chain server's APIs.  How do I do this?

**Comment by myvidster** [comment]
I notice that the elixiromg_watcher_1 and elixiromg_childchain_1 docker status are always restarting, I cannot attach to the container.

**Comment by jbunce** [comment]
Check there's no other instance of `geth` already running

**Comment by myvidster** [comment]
Only one instance of geth running.  I took at deeper look at the logs and the ewallet service cannot connect to the postres service on port 5432.  The docker images cannot content and communicate with each other.  Is there a way to allow this?

ewallet log:
State: Postgrex.Protocol
** (Mix) The database for LocalLedgerDB.Repo couldn't be created: an exception was raised:
    ** (DBConnection.ConnectionError) tcp connect (docker.for.mac.localhost:5432): connection refused - :econnrefused
        (db_connection) lib/db_connection/connection.ex:163: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

**Comment by myvidster** [comment]
I notice that I was using the 'mac' version for docker-compose I switched the -linux version, but I am still having the same issues with services on docker not connecting to each other.

** (Mix) The database for LocalLedgerDB.Repo couldn't be created: an exception was raised:
    ** (DBConnection.ConnectionError) tcp connect (0.0.0.0:5432): connection refused - :econnrefused
        (db_connection) lib/db_connection/connection.ex:163: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

**Comment by jbunce** [comment]
A lot of us use Macs for development and I haven't tested this on a Linux laptop. The above PR should fix this for you though.

Give yourself a fresh Docker environment by remove any dangling containers, networks, and images via `docker system prune -a` 

Pull the HEAD of `master`  via `git pull`

Build and run the services via `docker-compose up -f docker-compose.linux.yml --build`. The Childchain will be on http://127.0.0.1:9656, and the Watcher http://127.0.0.1:7434

It's also helpful when raising issues if you can tell us which service you received the exception from. In this case I was able to tell but it's not always apparent.

**Comment by myvidster** [comment]
I did a refresh install on a centos 7 VS server with the same results, I do have a mac mini I can try it on that device as well.  I have hardware for all platforms.  I will try your advice and report back.  Sorry the error in the last msg posted was from elixir-omg_watcher_1 it was trying to connect to childchain_db.  If you please show me your `sudo docker ps` resutlts, I think that can help me.

**Comment by jbunce** [comment]
Hi @myvidster 

There's been a few changes to the docker-compose files. Please can you:

1) Get rid of existing containers and networks via `docker-system prune -a`

2) Get the latest HEAD of master via `git pull`

3) Try to stand up the services via `docker-compose -f docker-compose-yml -f docker-compose-non-mac.yml up`

Make sure you don't have any `geth` or `postgres` instances before attempting to start the services or the containers won't start. Let me know how you get on.

Cheers

Jake

**Comment by myvidster** [comment]
Your last command did not work, but I assumed you might this:
docker-compose -f docker-compose-non-mac.yml up

Got this error after running:
ying to pull repository docker.io/library/elixir-omg ... 
ERROR: repository docker.io/elixir-omg not found: does not exist or no pull access

**Comment by jbunce** [comment]
If you think there's an problem please feel free to submit a PR. As you can make an API call I'm closing this for now.
