### ISSUE TITLE
Elixir 1.8 Exceptions in test

### ISSUE THREAD

**Issue by jbunce** [omisego/elixir-omg#401]
https://circleci.com/gh/omisego/elixir-omg/665

In stage Integration Test & Coveralls there are several exceptions. Please determine the cause and verify if it's safe to move to Elixir 1.8.

**Comment by jbunce** [comment]
Additionally in Dialyzer stage:

```
apps/omg_rpc/lib/client.ex:26: Type specification 'Elixir.OMG.RPC.Client':get_block(binary()) -> {'ok',map()} | {'error',{'malformed_response',any()} | {'client_error',any()} | {'server_error',any()}} is a supertype of the success typing: 'Elixir.OMG.RPC.Client':get_block(binary()) -> {'error',{'client_error',_} | {'malformed_response','false' | 'nil' | 'true' | binary() | [any()] | number() | map()} | {'server_error',_}} | {'ok',map()}
apps/omg_rpc/lib/client.ex:42: Type specification 'Elixir.OMG.RPC.Client':submit(binary()) -> {'ok',map()} | {'error',{'malformed_response',any()} | {'client_error',any()} | {'server_error',any()}} is a supertype of the success typing: 'Elixir.OMG.RPC.Client':submit(binary()) -> {'error',{'client_error',_} | {'malformed_response','false' | 'nil' | 'true' | binary() | [any()] | number() | map()} | {'server_error',_}} | {'ok',map()}
apps/omg_watcher/lib/web/endpoint.ex:15: Expression produces a value of type 'error' | 'excluded' | 'ignored' | 'unsampled' | {'ok',binary() | pid() | #{'__struct__':='Elixir.Task', 'owner':='nil' | pid(), 'pid':='nil' | pid(), 'ref':='nil' | reference()}}, but this value is unmatched
```

**Comment by jbunce** [comment]
https://circleci.com/workflow-run/27637506-e6b7-41b6-89f2-fabe81c9a128

**Comment by pthomalla** [comment]
- integration test exception was from test, where the exception was tested (at this point there were added capter logs to this in master)
- Dialyzer change that why it has errors ( https://github.com/omisego/elixir-omg/pull/390#pullrequestreview-196396595 <- branch where dialyzer was fixed)

**Comment by pdobacz** [comment]
re the "red error logs" in `Test & Coveralls` - yes they were reduced recently by a fix to `capture_logs` as @pthomalla mentions, but some still remain, we'll look into, meanwhile they don't break the tests so likely they're just failures of teardown. This has nothing to do with Elixir 1.8 (albeit it appears to not have bitten in the build @pthomalla mentions).

**Comment by pdobacz** [comment]
taking the liberty to close this, as we're on 1.8 since long
