### ISSUE TITLE
invalid json requests grill the http-rpc APIs

### ISSUE THREAD

**Issue by pdobacz** [omisego/elixir-omg#416]
Run this query to a watcher instance:

```
~c(echo '{"address": yolo}' | http POST localhost:7434/account.get_utxos) |>  :os.cmd()
```

returns:
```
'<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="utf-8">\n    <title>Plug.Parsers.ParseError at POST /account.get_utxos</title>\n    <meta name="viewport" content="width=device-............
```

same with the child chain api

commit 815c50052251e2ce38dd673517ca5f132fd20c8f

**Comment by pthomalla** [comment]
`'{"address": yolo}'`  is not a JSON value `yolo` should be a string or number

**Comment by pnowosie** [comment]
I have no hope it will change much, however we can try with debug page [switched off](https://github.com/omisego/elixir-omg/blob/c9c8a62167dc42e5b2927d0a41d4a938d01e458f/apps/omg_watcher/config/dev.exs#L12)

`debug_errors: false`
