### ISSUE TITLE
Fix child chain servers gas price selection mechanism

### ISSUE THREAD

**Issue by pdobacz** [omisego/elixir-omg#436]
It seems to be behaving as intended but the cadence of reducing/bumping the gas price seems to be wrong, see childchain's logs around any block submission. They follow the pattern:
1/ gas price goes down to minimal during doing nothing (probably when "no txs->no blocks" happen, which was not the case when the gas price mechanism was implemented)
2/ when there's time to submit, every 500ms the gas price doubles, quickly reaching maximum

It seems that the spot where the gas price recalculation takes place in `block_queue.ex` is not the right one. We probably want to make the logic of that more explicit, and rely less on the cadence of stuff from `BlockQueue.Core` being called by the `handle_infos` there.

**Comment by jbunce** [comment]
Blocks aren't getting written to the rootchain: https://imgur.com/a/oxuypRG

https://rinkeby.etherscan.io/address/0xeac4eedfb51c682f6eb2082093ee81791dfa9bc7

**Comment by pdobacz** [comment]
rinkeby.etherscan.io seems to be having problems so I can't check that, but from what I recall, what you've described @jbunce was an etherscan problem, not "blocks aren't getting written to the rootchain" problem

Etherscan uses to show the very first instance of a particular transaction (for a nonce) it sees. I've seen it register the low gas price transaction, which comes in first and because of that be blind to the correct gas price transactions that come immediately afterwards.

However it seemed to be only manifested on etherscan, and the blocks **did** got written to the root chain (e.g. Watchers picked them up correctly and without delay)

The problem is caused by this issue here, but blocks are getting written to the rootchain - I'm watchin our Child chain server's logs vs Watcher logs and all submissions appear for the watcher the moment after the expected delay (eth block interval)

**Comment by pthomalla** [comment]
fix in commit e363b2f87c87dda5b40db3a496a578df6b3f4882
