### ISSUE TITLE
Usability of IFE-related endpoints in the Watcher

### ISSUE THREAD

**Issue by pgebal** [omisego/elixir-omg#494]
List of recognized issues:
 - [ ] When calling status.get available piggybacks are reported as byzantine events
 - [ ] IFE's that are never piggybacked, don't have a notion of being finalized. Will always show up in `in_flight_exits` and `available_piggybacks`

**Comment by pdobacz** [comment]
Thanks! closing in favor of the other bucket-issue #811, that one has more intel
