### ISSUE TITLE
`/transaction.submit` change proposition: remove the need to RLP encode signatures

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#526]
We wanted to change [Child chain](https://omisego.github.io/elixir-omg/docs-ui/?url=operator_api_swagger.json#/ChildChain/submit) and corresponding [Watcher's](https://omisego.github.io/elixir-omg/docs-ui/?url=watcher_api_swagger.json#/Transaction/submit) `/transaction.submit` endpoint to receive:
* transaction - RLP & HEX encoded bytes of (raw) transaction
* signatures - array of HEX encoded bytes of signatures

:exclamation: Endpoint version which accepts just `transaction` will be removed :exclamation: 

Currently these endpoints receive transaction with signatures together, RLP-encoded.

__Reason for change:__ 
We've currently introduced [Informational Watcher helper](https://omisego.github.io/elixir-omg/docs-ui/?url=informational_api_swagger.json#/Transaction/createTransaction) `/transaction.create` which can help clients to compose transaction for a provided payment order. Helper will respond with RLP-encoded transaction bytes which is ready to sign by the UTXO owner(s).  
If the client could just produce signatures (2 standard crypto operations) and not be forced to bind the transaction & signatures together, it would simplify the tech stack on client side.

More versatile clients who needs more control over UTxOs being used in transaction have to still produce correct transaction (which includes RLP encoding). However they could save to not RLP encode transaction & signatures together.

__Rollout plan__
We would introduce parameter `signatures` to :point_up: endpoints, so there will be: 
1. possibility to send full RLP-encoded transaction with signatures using just `transaction` request field,
2. send raw transaction and signatures separately using `transaction` and `signatures` fields in the request body.

As we believe the 2nd version is better and is still the time to move, we will opt for **obsolete and remove 1st version** for the `v1.0`.

I looking forward for any feedback. Thanks :exclamation:

**Comment by Pongch** [comment]
Hey @pnowosie, here's my 2 cents:

I think having two classes of clients is a great idea. Ideally client responsibility should be reduced to simply signing and submitting transaction without the overheads of building + RLP encoding (which thus far has taken quite an effort to implement). This will also mean more client libraries implementations in the future 💯 

My concern around client w/o RLP capability, is that for these types of clients- the user *may have no idea* what exactly it is that they are signing. Say Alice wants to make a 10 Gwei transaction to Bob, she calls the Watcher to make an RLP encoded transactions, a malicious watcher response with a transactions sending 10 ETH to it's address as opposed to 10 Gwei to Bob, Alice takes the payload and sign it unknowingly. While a more responsible & complete client could decode it first ensuring that the transaction built by Watcher is correct, if it isn't then it won't call the `/transaction.submit`.

Other than that, the Rollout plan above makes sense.

Let me know if what you think 🙏

**Comment by pdobacz** [comment]
[EIP-712](http://eips.ethereum.org/EIPS/eip-712) just surfaced in one of our conversations. Please scan through and see if there's any relation between this here and EIP-712. Seems like this could potentially tackle the security issue Pong mentions

**Comment by kevsul** [comment]
I've been looking into EIP-712 these past couple of days, and I absolutely think we should support it.
It will allow users to use the same key management system (MetaMask, Trezor, etc.) for both the root chain and the child chain, which would be an enormous win from a usability point of view.

**Comment by pdobacz** [comment]
> EIP-712

it still can be rejected though, no? Not meaning that we should not look into supporting it because of that risk.

**Comment by kevsul** [comment]
I guess it could, but there seems to be a lot of momentum behind it and it's already implemented in Geth and Metamask

**Comment by chriskohlhoff** [comment]
On first impressions I liked the idea of moving the signature out, as the existing double-encode felt a little inelegant to me. However, here are a couple of concerns...

* Could you please clarify what your intention for the signature array is, if for example i'm only populating the 1st and 3rd inputs of the transaction. Do we always send 4 signatures, just leaving the 2nd and 4th as null signatures?

* The existing transaction is represented as a self-contained message in RLP message format, and this is more or less agnostic of the application message layer (e.g. JSON) that carries it. With this new change a higher level transaction structure exists (the tuple of transaction fields and signatures) and this must also be represented in some message format, which in the API is currently JSON. We now have to represent a transaction across two different formats.

This leads to a possibly stupid question if I follow this line of thought... What is the motivation for representing the transaction on the wire in RLP at all? Could you just send the transaction as a JSON object with all transaction fields exposed separately, and simply define the signature algorithm in terms of an RLP encoding of the fields?

**Comment by pdobacz** [comment]
> the 1st and 3rd inputs of the transaction

We're in the process of making gaps in inputs/outputs illegal, to reduce the number of moving parts and open ground for some optimizations, see #531 

> What is the motivation for representing the transaction on the wire in RLP at all?

good point. The original motivation to have a single RLP-encoded entry was that it allowed to put these exact bytes into a block directly. This makes both ways a tx is sent over the wire (1/ on `submit(tx)` and 2/ within a block) the same. 

Also it was the efficient and ethereum-compatible encoding, and we were keeping at the back of our heads the possibility of stripping down the JSON part.

So actually, moving away from a single RLP-encoded entry containing both the tx body and signatures is a move away from the two above benefits, and an argument against this proposition. Hm... :thinking:

**Comment by chriskohlhoff** [comment]
> We're in the process of making gaps in inputs/outputs illegal, to reduce the number of moving parts and open ground for some optimizations, see #531

Oh, that's a shame as it will make our settlement logic ever so slightly more complicated :)
We had fixed the first two inputs to be the buy side of a trade (first input was always the traded amount, and the second was any amount remaining open), and the second two inputs likewise for the sell side. I'm sure we can work around it though.

**Comment by pnowosie** [comment]
Wow - guys thanks for the comments :pray: - I really appreciate all inputs here :exclamation: 

As this discussion exploded in so many topics, let me first clarify the main idea of the change. Then I'll follow up to some concerns around the topic.

The proposed change of `transaction.submit` assumes support of 2 versions of response bodies:

> 1. send full RLP-encoded transaction with signatures using just transaction request field:

:point_right: This is as is currently
```javascript
{
    	"transaction": "0xf9010ff843b84122695...0080"
}
```

> 2. send raw transaction and signatures separately using transaction and signatures fields in the request body.

:point_right: This version we want to introduce. 
```javascript
{
    	"transaction": "0xf9010ff843b84122695...ac9f",
    	"signatures": [
    	    	"0xbd18564dac9fc9ac...8080c",
    	    	"0xbd18564dac9fc9ac...8080c",
    	]
}
```
`transaction` field contains RLP encoded _raw_ transaction: `{inputs, outputs, metadata}`. The exact bytes that are being hashed and signed in signing operation. 
`signatures` contains of signature of transaction's hash by each of the owners private keys.

:bulb: So comparing version 2 of the request body with 1. (old one) is just __bringing the signatures outside of the encoded form__. 

Rollback plan assumes supporting both :point_up: versions for the `v0.2` (and maybe longer). Then depreciate version 1. and finally remove it from the future version.

**Comment by pnowosie** [comment]
__Concerns:__

> 1. client w/o RLP capability, the user may have no idea what exactly it is that they are signing

This is the issue of trust to `/transaction.create` which simple client may want to use. Clients with RLP capability would make RLP-encoded transaction on their owns. (This form is needed for signing process). And then send this RLP-encoded transaction and signatures separately. Which simplifies also here as they don't need to bind signatures into transaction.
@Pongch (@pdobacz , @kevsul )

> 2. What is the motivation for representing the transaction on the wire in RLP at all? Could you just send the transaction as a JSON object with all transaction fields exposed separately

I agree this would be more friendly to the user (:man:  humans). However it does not help software clients as @chriskohlhoff pointed out - signing process requires the transaction to be expressed in standard, RLP-encoded form. So having the transaction represented as a JSON object we require all clients to be `RLP capable`. That is basically __this change is proposed against__ :fire: To allow simple clients to avoid RLP complexity.

> We're in the process of making gaps in inputs/outputs illegal,

I'm sorry hearing this change thwart the plans, but transaction with gaps may behave incorrectly processed by the `plasma contract` code. E.g. to save the gas we iterate through not empty inputs, stopping on first empty one etc. It is safer for us to introduce this restriction as `solidity` programming requires many trade-offs. Does it sounds reasonable  @chriskohlhoff :question: 

:point_right: I'm omitting the `EIP-712` thing as nice to have future. 

Please let me know, if this clarifies the proposition a little :question: 
__Thanks!__

**Comment by kevsul** [comment]
@pnowosie I think it makes sense from the user's point of view - to remove that extra step of assembling and RLP-encoding the signed transaction.

@pdobacz raised the question of efficiency though - the childchain will now have to do that tx assembly if the client doesn't. Is that going to be have a big impact? Is the trade off for client ease-of-use worth it? We probably need to measure this somehow...

> we were keeping at the back of our heads the possibility of stripping down the JSON part.
Not sure what you meant by this @pdobacz ? Do you mean removing the JSON part of the JSON-RPC API?

I also think that EIP-712 is something we should seriously look into supporting, but not in this issue...

**Comment by pdobacz** [comment]
> raised the question of efficiency though - the childchain will now have to do that tx assembly if the client doesn't.

Hm, maybe I misspoke. The child chain is doing a disassembly now, it would need to do the assembly if we go down this path, I'd say more or less evening out. 

I mentioned that RLP is just _an_ efficient encoding scheme, that could potentially work stand-alone (this is the JSON-stripping part). E.g. a high-profile client could be streaming RLP-encoded bytes with no JSON-RPC/HTTP cruft etc. But after some discussions here it is both utopic and not that much of an issue.

> Not sure what you meant by this @pdobacz ? Do you mean removing the JSON part of the JSON-RPC API?

more or less, see above paragraph

> I also think that EIP-712 is something we should seriously look into supporting, but not in this issue...

absolutely - I only posted here, to make sure whatever changes we consider **here**, aren't prohibiting doing EIP-712 later.

**Comment by pnowosie** [comment]
Closing as 698 is done.
