### ISSUE TITLE
Deposit to child chain not working

### ISSUE THREAD

**Issue by imVinayPandya** [omisego/elixir-omg#528]
I have recently started exploring this project. and gone through setup and its working fine for me.
i have used docker, docker-compose for starting server on local machine.

i am using latest code from master branch. (i hope that Master branch is stable, if it is not stable then which branch is stable?)

i am executing following example https://github.com/omisego/elixir-omg/blob/master/docs/demo_01.md

but when i execute following line 

```
deposit_blknum = DepositHelper.deposit_to_child_chain(alice.addr, 10)
```
it is giving me following error. 
```
** (MatchError) no match of right hand side value: []
    lib/root_chain.ex:724: OMG.Eth.RootChain.deposit_blknum_from_receipt/1
```

this is happening because in this file **apps/omg_eth/lib/root_chain.ex** the function
**deposit_blknum_from_receipt**, the params/map %{logs => logs} is an empty list [].

and this logs coming as empty list from this function

file: apps/omg_api/test/support/integration/deposit_helper.ex
```
 def deposit_to_child_chain(to, value, @eth) do
```
if i do **IO.inspect** receipt in above function

```
%{
  "blockHash" => "0xbef4f10a52509aed801709f5679281bb8ad75288c099bdfd0217bbac5872c4d4",
  "blockNumber" => 1729,
  "contractAddress" => nil,
  "cumulativeGasUsed" => "0x6658",
  "from" => "0xe62c3d91689e3ca9b34431063bd1c566c3b799e0",
  "gasUsed" => "0x6658",
  "logs" => [],
  "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status" => "0x1",
  "to" => "0x5506dc9e672633af38c4fd07c2dc02b4e9bc268d",
  "transactionHash" => "0xa56b4ba0bb2c592420fd2299371dc1217cec727f3b5ad1363a7af5fc799baea4",
  "transactionIndex" => "0x0"

```

again logs is empty list. :(

**Comment by pdobacz** [comment]
Hello Vinay and thank you for a comprehensive report.

The issue that you're encountering seems to be that the deposit transaction succeeded but there were no logs emitted, which is in fact strange, as every successful deposit should [emit as here](https://github.com/omisego/plasma-contracts/blob/ce4a23d75b8c5f9cc4526f50bde4968908fc258d/contracts/RootChain.sol#L318)

I'll try to reproduce, just one troubleshooting question: 

after checking out the repo, did you modify the contract code locally in any way or make changes to the `mix.exs`/`mix.lock` files to point to a different revision of contracts?

I'm asking because even if you've undone your changes and then got your result, it might be the case that the modified version got "stuck" somewhere, and your deposit transaction was trying to talk to that.

**Comment by imVinayPandya** [comment]
@pdobacz i havn't done any changes.

 i have just cloned the repo. initially i have checkout v0.1.2 tag/commit. i have started server i got some errors. so i came back to master branch, taken a pull for latest code and started server.

**Comment by pdobacz** [comment]
UPDATE: I've not yet had a chance sit down to try to reproduce the issue, but the symptoms would indicate that the deposit was made to an address that didn't hold any contract - hence transaction succeeds but no logs get emitted.

I cannot see how that could happen, it might be some glitch in our setup procedures, when for example it would be fed an old contract address, after the `dev` chain has already been reset from scratch (?)

**Comment by imVinayPandya** [comment]
okay i'll do one thing, i will try to clone fresh repo, and will try again the same demo let's see it will works or not. 

one more thing, is master branch is stable? or should i use latest release (e.g. v0.1.2)?

and Thank you for your reply. i really appreciate it.

**Comment by pdobacz** [comment]
> one more thing, is master branch is stable? or should i use latest release (e.g. v0.1.2)?

`v0.1.2` might be slightly more stable than `master`, because it moves much less now. We have a number of CI checks that verify that `master` is operational, but still some breakage might slip in there.

Mind however, that both are still quite alpha stage.

The main difference is that `master` uses a different protocol (contract, transaction format) than `v0.1.2`, so one cannot switch between the two without starting a fresh child chain.

Lastly, `v0.1.x` is likely to be discontinued within ~1 month or so, in favor of `v0.2` which is in the making on `master`.

Hope this helps and please report any issues that you encounter, thank you! :bowing_man:

**Comment by imVinayPandya** [comment]
okay go it now, may be the switching branch from v0.1.2 to master this may cause the issue. so tomorrow i will try with fresh master branch, then i will let you know that is working or not.

Thank you again @pdobacz

**Comment by imVinayPandya** [comment]
Hello @pdobacz i have removed old code and cloned fresh repo. still i am getting same issue.

i have just run these commands
```
> mix deps.get

> docker-compose -f docker-compose.yml -f docker-compose-non-mac.yml up
```

```
> docker ps

CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                    PORTS                    NAMES
83219b594e0d        elixir-omg:dockercompose             "/bin/bash -c './lau…"   5 minutes ago       Up 5 minutes (healthy)                             elixir-omg_watcher_1_de16227a4506
597b0df209f0        elixir-omg:dockercompose             "/bin/bash -c './lau…"   5 minutes ago       Up 5 minutes (healthy)                             elixir-omg_childchain_1_d9d5af9928bf
16ce355eeec1        jakebunce/contractexchanger:v0.0.2   "./server.py"            5 minutes ago       Up 5 minutes (healthy)                             elixir-omg_contractexchanger_1_bb0715fe9156
fed5d5eaaa5a        ethereum/client-go:v1.8.21           "/bin/sh -c 'apk add…"   6 minutes ago       Up 5 minutes (healthy)                             elixir-omg_geth_1_96c3649f5982
83c4de9036fc        postgres                             "docker-entrypoint.s…"   7 days ago          Up 19 minutes (healthy)   0.0.0.0:5432->5432/tcp   elixir-omg_childchain_db_1_c14396ee8429
fb01c98616b0        postgres                             "docker-entrypoint.s…"   7 days ago          Up 19 minutes (healthy)   0.0.0.0:5433->5432/tcp   elixir-omg_watcher_db_1_7256c903b6d7
```

**Comment by pnowosie** [comment]
Hey @imVinayPandya I was able to make it work on my very unsuccessful macbook (only geth_1 & childchain_1 containers were up, and no logs were shown).
Apologize for the laconic explanations - it's a quite late when I'm writing this.

## 1. make sure geth & ch-ch are responding
```
> geth attach http://localhost:8545
Welcome to the Geth JavaScript console!
...
(ctrl+d) # to detach from geth

> http localhost:9656/
...
"data": {
        "code": "operation:not_found",
        "description": "Operation cannot be found. Check request URL.",
        "object": "error"
    }
```

## 2. prepare config file
Ask contract_exchanger about details of deployed contract
```
> http localhost:5000/get_contract
{
    "authority_addr": "0x80dbd3d021bf012ebeb337ba7f402348a7055cd1",
    "contract_addr": "0xa0760eaaef1113986c9026cf0f0fda19f47ff6b4",
    "txhash_contract": "0x94ad426aff82146cb8c9400cfd78647a53d4361272e2c6eb073e537abd84d71a"
}
```

create a file, named e.g. ~/docker_config.exs and fill it with the info ☝️ file should looks like this
```
> cat ~/docker_config.exs 
use Mix.Config
config :omg_eth,
  contract_addr: "0xa0760eaaef1113986c9026cf0f0fda19f47ff6b4",
  txhash_contract: "0x94ad426aff82146cb8c9400cfd78647a53d4361272e2c6eb073e537abd84d71a",
  authority_addr: "0x80dbd3d021bf012ebeb337ba7f402348a7055cd1"
``` 

## 3. Start elixir REPL
Open terminal, navigate to repository root and run `iex -S mix run --no-start --config ~/docker_config.exs` 

You probably need to fetch deps and compile it first if you've never done this before (from repo root)
`mix do deps.get, compile`

Now you can follow steps from [demo 1](https://github.com/omisego/elixir-omg/blob/master/docs/demo_01.md)
if you get an error running a line `...DepositHelper.deposit_to_child_chain(...` looking like
```
** (ArgumentError) argument error
    :erlang.binary_to_existing_atom({:system, "ETH_NODE", "geth"}, :utf8)
```
please run  `Application.put_env(:omg_eth, :eth_node, "geth")` & repeat `deposit_to_child_chain` step

I was able to finish demo 1. Please let us know about your experience. I'm looking forward hearing from you ❗️ Thank you for your interest in this project.

**Comment by imVinayPandya** [comment]
@pnowosie thank you for your reply, i follow your steps and it is working fine.

one more thing i haven't run this command 
`Application.put_env(:omg_eth, :eth_node, "geth")
but still it is working. i don't know why.
i guess that issue was with ETH_NODE env right?

**Comment by pnowosie** [comment]
It went well because we recently fix demo :trollface: , issue was that deferred config wasn't populated with `DeferredConfig.populate(:omg_eth)`

**Comment by imVinayPandya** [comment]
Nice good good. feel free to close this issue. again Thank you @pnowosie @pdobacz.

**Comment by pnowosie** [comment]
You’re welcome @imVinayPandya. Thanks for contributing to demos quality.
