### ISSUE TITLE
MacOS Mojave setup instruction (w/o docker)

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#535]
# Environment

MacOS Mojave 10.14.3

Elixir
```
> elixir --version
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```

Solidity
```
> solc --version
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Darwin.appleclang
```

## Elixir-omg compilation
Clone latest master into directory of you choice.
Fetch dependencies with `mix deps.get`

Compilation of dependencies should go well, probably you would need to install some requirements (e.g. openssl, automake...) your system is missing, but installing latest version should do the trick.

Only exception to above is `eleveldb` which is not maintained for some time now.
For this you need to add commandline tools (c++ includes) ❓ 
Replace also all occurence of `10.8` to `10.7` in `<repo_root>\deps/eleveldb/c_src/leveldb/build_config.mk`
Then try to compile eleveldb with
```
> CXXFLAGS=-stdlib=libc++ CPATH=/Library/Developer/CommandLineTools/CommandLineTools/usr/include/c++/v1 mix deps.compile eleveldb
```

**Comment by pik694** [comment]
As said in #555, for now macOS users can simply apply the following patch:
https://drive.google.com/file/d/1JRuR2_nuJnxhFoZNCIBXafZGYRbncuOZ/view?usp=sharing
