### ISSUE TITLE
Additional application metrics

### ISSUE THREAD

**Issue by kasima** [omisego/elixir-omg#549]
Count and measure times for:
- transactions
  - success
  - failure
- block submits
- deposits
  - deposit amount
- exits
  - standard
    - started
    - challenged
    - success
  - in-flight
    - started
    - challenged
    - success

This list is not necessarily comprehensive. Feel free to add other things to measure.

**Comment by achiurizo** [comment]
@pthomalla where can we find these metrics?

**Comment by achiurizo** [comment]
Chatted with @jbunce but want to add on to this issue about getting additional [metrics into Datadog](https://www.datadoghq.com/apm/). I think we can expand this issue to include these as well.

**Comment by pdobacz** [comment]
For future reference: some preliminary work using AppSignal here: https://github.com/omisego/elixir-omg/pull/640. PR closed due to pending datadog work

**Comment by achiurizo** [comment]
Closing this issue for now and letting https://github.com/omisego/devops/issues/79 capture this.

**Comment by achiurizo** [comment]
Actually resurrecting this issue instead and breaking out asks from omisego/devops#79
