### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by kasima** [omisego/elixir-omg#550]
Pulling from @jbunce's comment in https://www.pivotaltracker.com/story/show/159842559/comments/199927466

Applications:

- How long does it take to create a Plasma block, how large is the block queue? Does the block queue have the potential to lead to a memory leak and data loss if a pod goes out of memory?
- What's the I/O from LevelDB for writing blocks to disc?
- What's the impact of moving from LevelDB to RocksDB?
- Crypto operations like timing hash functions

Database:

- Block write latency to Postgres
- UTXO set read latency

Etheruem:

- How long does it take to broadcast a block to Ethereum? 
- How would a change of Ethereum client impact our services?

**Comment by pdobacz** [comment]
experimental AppSignal metrics delivered in #616
