### ISSUE TITLE
EIP-712 signing support

### ISSUE THREAD

**Issue by kasima** [omisego/elixir-omg#551]
[ERC-712](http://eips.ethereum.org/EIPS/eip-712) support would allow metamask to sign our child chain transactions from a web3 application.

Open question: do we want to support the current signing method _in addition_ to ERC-712? Or do we want to migrate all signing to ERC-712?

**Comment by pnowosie** [comment]
As of current Metamask version (6.3.1) arrays are not supported in structured data (https://github.com/MetaMask/metamask-extension/issues/6106). Having a possibility to sign transactions with metamask is huge benefit, so it is worth for 1st version to unwind inputs and outputs.

So the `message` of signed data will looks like this
```
{
                input0: { blknum: 1001, txindex: 0, oindex: 0},
                input1: { blknum: 1002, txindex: 0, oindex: 0},
                input2: { blknum: 2000, txindex: 0, oindex: 0},
                input3: { blknum: 2000, txindex: 1, oindex: 0},
                output0: { owner: "0x2258a5279850f6fb78888a7e45ea2a5eb1b3c436", currency: "0x0000000000000000000000000000000000000000", amount: 50 },
                output1: { owner: "0x2258a5279850f6fb78888a7e45ea2a5eb1b3c436", currency: "0x0000000000000000000000000000000000000000", amount: 50 },
                output2: { owner: "0x2258a5279850f6fb78888a7e45ea2a5eb1b3c436", currency: "0x0000000000000000000000000000000000000000", amount: 50 },
                output3: { owner: "0x2258a5279850f6fb78888a7e45ea2a5eb1b3c436", currency: "0x0000000000000000000000000000000000000000", amount: 50 },                                 
                metadata: "0x0000000000000000000000000000000000000000000000000000000000000000"
            }
```

**Comment by pnowosie** [comment]
During analysis of the change we fount out it has significant impact on the contract code (new signing schema does not require RLP at all). To limit the scope of the change we could use only new signing schema but for transport and use contract would represent transaction as they are now.
So we would need to adjust only signature verification code. it could go like this:
* decode RLP encoded transaction
* calculate structure hash (precisely calculate: `encodedData` & hash with constants)
* verify the signature with this hash

**Comment by pnowosie** [comment]
[Scope limitation] For this :issue: I will use Eip-712's domain parameters constant (from `Ari`):
```
chain_id = 4 (rinkeby)
verifying_contract = 0x44de0ec539b8c4a4b530c78620fe8320167f2f74
```

To extent it further we will need
* support `chain_id` parameter in contract code (ECRecover) \#todo :issue:
* inject contract address & chain_id values during deployment #621 

(CC: @pdobacz , @kasima )

**Comment by pnowosie** [comment]
Regarding multiple signing methods support - imho we'd rather support just eip-712 and depreciate old one. Thoughts @kasima , @pdobacz

**Comment by pdobacz** [comment]
> Regarding multiple signing methods support - imho we'd rather support just eip-712 and depreciate old one.

:+1: with the remark that architecture-wise it should be rather straightforward to swap `EIP-712` for something different, which I believe was true now, but let's double check. I guess this comprises of naming and emphasizing the code responsible for producing a `txhash` flavor dedicated to being signed/recovered. Should we need to swap this implementation for anything new (or revert), we need know how to tackle that.

**Comment by pdobacz** [comment]
contd. 

Let me also summon @Pongch @whoisjeremylam to weigh in from product perspective, and maybe also @paulperegud from the DEX-y perspective - note that the structured signing would then consistently be applied to orders and other tx-types.

**Comment by Pongch** [comment]
I agree with @pnowosie on just having a support for eip-712 and start deprecating. The risk though is that 712 is still an EIP and there seems to be a few more steps needed before it's final.
