### ISSUE TITLE
Expose application alarms

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#558]
@jbunce said:
Elixir Alarm -> ElasticSearch -> Graphs/Times/Dashboard -> Alert to Slack.
Log to STDOUT and it'll get picked up by fluentd.
The alarms are in :omg_status.

**Comment by InoMurko** [comment]
Application side is probably done. Need verification from devops.

**Comment by InoMurko** [comment]
TBD: Alert if authority locked!

**Comment by jbunce** [comment]
Heads up that our prod services are running on Parity now (from Samrong onwards).

**Comment by achiurizo** [comment]
Closing this and linking it up with our https://github.com/omisego/devops/issues/79 story.
