### ISSUE TITLE
Clean up configuration

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#560]
Currently, application configuration is duplicated (for omg):
```
env: [
        # we're using a shared (in `omg` app) config entry. The reason here is to minimize risk of Child Chain server's
        # and Watcher's configuration entries diverging (it would be bad, as they must share the same value of this).
        # However, this sharing isn't elegant, as this setting is never read in `:omg` app per se
        deposit_finality_margin: 10,
        ethereum_events_check_interval_ms: 500,
        coordinator_eth_height_check_interval_ms: 6_000
      ],
```

and later again in all `apps/omg/config/` files specific to the environment. An application developer might be confusing, where does application specific setting live - hence duplicating entries in both. Settings should be moved completely to config files.

The configuration that needs to be equal and shared between childchain and watcher needs to be addressed differently. 

Either we use a common app (like :omg) or we set an environment variable that gets baked into the modules at compile time. We can still check the values as prehooks at release creation time. But I doubt it's needed.

**Comment by pdobacz** [comment]
As someone pointed out - we don't have proper and consistently located docs on the config variables.

Let's fix that as part of this refactor!
