### ISSUE TITLE
Horizontally scale child chain servers

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#561]
I will convert this to an issue so that we can start the discussion.
Preliminary work for this is swapping out LevelDB (because of it's limitations).

1. How would the application react in terms of processes with state like `OMG.State` where two nodes would have different state at different point in time where a transaction is submitted first to node 1 and then to node 2? Is the KV store we use (xDB) the originating point of truth?
2. Is there shared state that would need to be shared? Basically, do we need to cluster the nodes?

**Comment by paulperegud** [comment]
Just a side-note - in terms of performance our bottleneck is the time needed to sync watcher on commodity hardware. So the context for horizontal scaling would be - reliability?

**Comment by InoMurko** [comment]
Exactly!

**Comment by jbunce** [comment]
In order to facilitate volume replication across zones a KV level lock would be beneficial. Then the two Childchain clusters would be independent and zone failures can be tolerated.

**Comment by InoMurko** [comment]
I think for the time being, what we could do is having sort of like:
```
                                         |---- watcher1 --------- |
Req. with id 44-->fanout|                                       |fanout------Ethereum client
                                        |---- watcher2  ---------|
```
Now this would partially solve scalability and availability. Certainly isn't optimal... basically both watchers would do everything, and by that, both would be able to take each other's place. Maybe that introduces problems with latency...
Just a thought.

**Comment by achiurizo** [comment]
Closing this in favor of https://github.com/omisego/elixir-omg/issues/710 which will contain this story.
