### ISSUE TITLE
Error handling for missing signature

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#568]
When trying to merge UTXOs, if a signature is not present within the transaction object, the error message to client is `submit:unauthorized_spent`, which gives an impression that a wrong private key is being used to sign the transaction. 

a better error message to return could be `submit:missing_signature` instead

**Comment by pdobacz** [comment]
THanks @Pongch. Can you dump the transaction object (e.g. as returned from the `transaction.create` call)? As far as I can tell, it should return `missing_signature`, if the tx had at least one non-zero input. (or maybe this just how my tidying-branch works :thinking:. I'm pretty sure I've recently seen code/tests that should make it `missing_signature`)

**Comment by Pongch** [comment]
Ah, this is a transaction object that was built, signed and encoded locally without `transaction.create` endpoint, the `submit:unauthorized_spent ` is what is returned as a response from the watcher.

TX that failed with submit:unauthorized_spent error message (2 utxos input, but only 1 signature provided)

`f90114f843b841cdd5e6bdfb2bd3a1ef6f7605d2b2c349dfdf35f9cf6c5afef1d3e16500a66326041722959e706acbe376228c9a11d2fe0d67f5bab5acad6831093cf99f2887c11bd8c78401098c788080c784010ce7d88080c3808080c3808080f8b4ed94fc00f6f822bbab5bb6540101170da7a7f9267347940000000000000000000000000000000000000000820320ed94fc00f6f822bbab5bb6540101170da7a7f92673479400000000000000000000000000000000000000008204ceeb94000000000000000000000000000000000000000094000000000000000000000000000000000000000080eb94000000000000000000000000000000000000000094000000000000000000000000000000000000000080`

TX that went through fine (2 utxos input, 2 signatures):

`f90157f886b841cdd5e6bdfb2bd3a1ef6f7605d2b2c349dfdf35f9cf6c5afef1d3e16500a66326041722959e706acbe376228c9a11d2fe0d67f5bab5acad6831093cf99f2887c11bb841cdd5e6bdfb2bd3a1ef6f7605d2b2c349dfdf35f9cf6c5afef1d3e16500a66326041722959e706acbe376228c9a11d2fe0d67f5bab5acad6831093cf99f2887c11bd8c78401098c788080c784010ce7d88080c3808080c3808080f8b4ed94fc00f6f822bbab5bb6540101170da7a7f9267347940000000000000000000000000000000000000000820320ed94fc00f6f822bbab5bb6540101170da7a7f92673479400000000000000000000000000000000000000008204ceeb94000000000000000000000000000000000000000094000000000000000000000000000000000000000080eb94000000000000000000000000000000000000000094000000000000000000000000000000000000000080`

This is on Ari btw, which might explained it. So if it's already included I can drop the issue

**Comment by pdobacz** [comment]
Yes, this is what `v0.2` brings. I ran a quick check and on `devel` your first transaction returns `missing_signature`. Feel free to close this, if all is clear.
