### ISSUE TITLE
Builds on master result in high CPU use for the Watcher

### ISSUE THREAD

**Issue by jbunce** [omisego/elixir-omg#572]
CPU utilisation is consistently around 1.5 vCPU (1574m)

**Comment by pdobacz** [comment]
Dropping a note for future reference here. After the reset of the `devel` child chain, the issue still persists in that environment, I've noticed it affects bee013a, 5602254 and 55abe27, load around 1.5 vCPU

At the same time, the Watcher idling consumes 0.05 CPU for me locally.

**Comment by InoMurko** [comment]
This was addressed in https://github.com/omisego/elixir-omg/commit/535552bc2e3d72591c0bbb320e93ab6490481acf
