### ISSUE TITLE
Allow to omit content-type header if no param sent in watcher API

### ISSUE THREAD

**Issue by mederic-p** [omisego/elixir-omg#590]

**Comment by pdobacz** [comment]
I take it #607 is the quick fix/workadound for `status.get`, which should be undone, when this is fixed properly, correct?

**Comment by T-Dnzt** [comment]
That is correct.

**Comment by pnowosie** [comment]
I'd like to try approach with single pipeline by not apply plug to particular action - kind of:
`plug(:enforce_json_content) when action not in [...]`
