### ISSUE TITLE
/status.get requires a `Content-Type` header while not requiring a body

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/elixir-omg#601]
In order to fix the Swagger documentation and avoid adding some hacks to it, the `/status.get` endpoint should not require a `Content-Type` to be set since no `body` needs to be sent. 

To expand on that, since most endpoints don't actually require a body (a lot of params are optional), the enforcing of the `Content-Type` header presence should not really be there if there's no body, but this issue only focuses on the status endpoint for the watcher (because it __never__ needs a body).

**Comment by pnowosie** [comment]
I'd like to try approach with single pipeline by not apply plug to particular action - kind of:
`plug(:enforce_json_content) when action not in [...]`

**Comment by pnowosie** [comment]
Should be closed as we :merged: referencing :pr:
