### ISSUE TITLE
Unsynced Ethereum client and get_root_deployment_height/0

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#619]
`OMG.Eth.RootChain` implements `get_root_deployment_height/0` which fails if the Ethereum client is not fully synced (*but responsive!*).
This means that the function call will be returning `{:error, :wrong_contract_address}` and throw the Monitored children into restart spree, until the Eth client responds with a correct height.

I propose we solve this by an early check and a raised alarm (before the system fully boots all children, or completely async and letting a few crashes occur). We would check whether we can get the deployment height, if we cannot and the call is returning `{:ok, nil}`, there's a possibility that the client is still syncing and we need to schedule the check for later.

The question that is open - how do we differentiate between a client still syncing and wrong config input for the `contract_addr` and `txhash_contract`?

**Comment by pdobacz** [comment]
I see a couple of items here:
1/ we can handle the `{:ok, nil}` response with sth less confusing than `:wrong_contract_address` for a good start
2/ note, we don't have to by _fully_ synced to work - it is enough to be "synced enough" to see the receipt of the contract deploying tx. Here we're so "unsynced" we don't even see the relevant contract yet. Unless this is of course the child chain, which is more stringent on that matter.



> how do we differentiate between a client still syncing and wrong config input for the `contract_addr` and `txhash_contract`?

If we have a way to not suffer from the pointless restarts, we can also treat these equally, assuming that not seeing the contract at all is sth like a fatal condition.

Btw, why are we actually having the restart spree at all - shouldn't it be done after a few attempts (I remember we bumped the `max_restarts`, but wasn't this obsoleted by proper geth connectivity handling?)

**Comment by InoMurko** [comment]
1. Handling on that level (the implementation of `get_root_deployment_height/0`) wouldn't be too beneficial really, because `EthereumEventListener`, `BlockGetter`, `BlockQueue` expect a tuple with an integer. 
2. Yes indeed, the client needs to be synced *up to* the contract deployment height. Still it can take quite a while before you're there when starting a clean watcher deployment, for example.

The new geth connectivity checks just that - whether the network and the client is responding (similar to a ping but we fetch last height).

`If we have a way to not suffer from the pointless restarts, we can also treat these equally, assuming that not seeing the contract at all is sth like a fatal condition.`
If the contract with the address specified in the config is really deployed, then it's not temporary fatal condition. Until the client syncs to the contract height. But if the contract doesn't even exists, then the condition would never recover. At best we can do probably is handle that (or integrate Etherscan to check validity?)

**Comment by pdobacz** [comment]
in (1.) I'm just suggesting getting rid of the misleading error message.

In general, I'm supportive of solving the problem fully and elegantly.

But the question remains - why is the restart spree happening at all, if it should give up after 3 attempts (the default)? If the application just refused to start, with an understandable error message and log, I think we would be much better off already.

It would perhaps be too strong for cases where we're just syncing, but it would at least be adequate for cases of misconfiguration. And telling these two cases apart is in fact hard, without tricks like etherscan etc.

**Comment by InoMurko** [comment]
The restart don't stop because the restart strategy was replaced by custom monitoring. The errors that are thrown (in this case all processes that call `get_root_deployment_height/0` throw can't match right hand side). This is not related to ethereum connectivity where we would gracefully handle the exits because there's an alarm raised. 

I suggest we do the following:
if `get_root_deployment_height/0` is unable to return a result we understand (`{:ok, <some number>}`, we raise an alarm that contains a general description, something like:
`Ethereum client syncing in progress or contract address miss configuration`. We then prevent restarts, but periodically check `get_root_deployment_height/0`. If we get an answer, we clear the alarm and restart all children. Wdyt?

**Comment by pdobacz** [comment]
>restart don't stop because the restart strategy was replaced by custom monitoring

oh, I thought the monitoring "inherited" the Supervisor's behavior. I'd assume that there are errors, on which we do want to stop after all.

> I suggest we do the following:...

sounds good. If it is a quick fix, we can just apply this, but if it's not - I still opt to amend the misleading error message & restart spree first.
