### ISSUE TITLE
Verification of network parameters during startup

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#621]
[EIP-712](https://github.com/omisego/elixir-omg/issues/551) introduces 2 parameters that should be verified against network application is working on.
These parameters are
* __contract address__ - passed in configuration item: `:omg, :eip712Domain, :verifying_contract`
* __chain_id__ - passed  in configuration item: `:omg, :eip712Domain, :chain_id`

These params are used to correctly compute structured hash & verify signature. To assert that config values are up-to-date, application (child chain & Watcher) should crash on startup.

Think also about automated deployment - how to ensure proper values are passed to configuration file.

**Comment by pnowosie** [comment]
I think we can safely remove EIP-155's `chainid` from EIP-712 structural hashing and signatures (:see: omisego/plasma-contracts#98)

**Comment by Pongch** [comment]
just for clarification, you basically need to pass the value of the `contract_address` for every deployment of child chain & watcher right ? Will this issue affect the deployment process of v0.2 ,ie we need to deploy contracts and elixir-omg manually ?

**Comment by pnowosie** [comment]
> need to pass the value of the contract_address for every deployment
Nice thing with `contract_address` is we already have this in both elixir & solidity. Just small changes required to make use of it in hashing.
