### ISSUE TITLE
Fix dialyzer wrong derived type from dependency

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#632]
[This commit](https://github.com/omisego/elixir-omg/blob/ec3694c8cce420a8855385f0540dadf46b4b68b7/apps/omg/lib/omg/typed_data_sign/config.ex#L16-L17) has suppressed dialyzer warnings regarding ABI dependency.

Maybe we could fix it?

**Comment by pnowosie** [comment]
This should help (kudos @InoMurko )
https://github.com/poanetwork/ex_abi/pull/18

**Comment by InoMurko** [comment]
Sorted: https://github.com/omisego/elixir-omg/pull/623
