### ISSUE TITLE
UTXOs consolidations for convenient exit

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#638]
**Story:** 
As a user, I would like to consolidate all my UTXOs into one so I can conveniently exit from my plasma chain

Let's define convenient + ideal way to do that, whether through Watcher endpoints or using plasma-cli/ omg-js/ js-starter-kit

- This is blocking the hard Ari upgrade https://github.com/omisego/elixir-omg/issues/637
- related, unconsolidated version of exit: https://github.com/omisego/elixir-omg/issues/615

@kasima @jbunce @kevsul

**Comment by Pongch** [comment]
In general the overall process would look like this:

1. User receives all available UTXOs to exit
2. User sign transaction(s) to merge
3. User call startStandardExit() and then processExit()

Option 1: Quick, easy but unsafe.
We enable a way for user to do chain merge transactions (the reverse of plasma-dog split transactions). Until there is one UTXO and then exit.

Option 2: Slower but safer.
We allow a user to gradually do merge transactions + get utxos on the watcher to ensure that transactions are included on the Rootchain. Then calling exit once there is only one available UTXO

**Comment by jbunce** [comment]
I think that process works with the assumption that the user wants to merge their UTXOs for an exit. What if they want to consolidate so they don't have to implement their own UTXO management? This would allow for lighter clients (like mobile) to hit the Childchain directly should they wish.

**Comment by kevsul** [comment]
Javascript implementation here:
https://github.com/omisego/omg-js-utxo-merge

Note that from v0.2 onwards the Watcher's `/transaction.create` API will provide this functionality

**Comment by pnowosie** [comment]
> Note that from v0.2 onwards the Watcher's `/transaction.create` API will provide this functionality

Well not exactly `this` - Watcher endpoint will suggest to merge just 4-highest utxo for merge if user tricks it to do so. 
For example if address owns 8 utxos, lets tag them `1, 2 ... 8` (and current transaction can merge MAX 4 of them at once), calling `transaction.create` with tuned input would suggest to just 1 merge tx with inputs `[1-4]`. Then user needs to wait until next block for Watcher to acknowledge the new (merge) utxo, e.g. 9. And then calling `transaction.create` again would suggest merge tx of `[9, 5-7]`

**Comment by Pongch** [comment]
The minimal version for this script is now here: https://github.com/omisego/plasma-upgrade-scripts. Still got a little bit of polishing to do.

Note that as Kevin said, the script for users to chain-merge transactions would eventually be deprecated  in favor for the convenient API

**Comment by achiurizo** [comment]
synced with @Pongch and good to close
