### ISSUE TITLE
Authority account unlocked on geth. Childchain reports locked

### ISSUE THREAD

**Issue by jbunce** [omisego/elixir-omg#662]
```
> personal.unlockAccount("0x7e56a10f5eb2578d4864e22da8cf30cec3f92d68", "<redacted>", 0)

true
```

This is definitely the account used by the Childchain:

```elixir-user@childchain-0:~$ cat config.exs
use Mix.Config
config :omg_eth,
  contract_addr: "0x5bb7f2492487556e380e0bf960510277cdafd680",
  txhash_contract: "0x67010a23dda28d0ba0df5b3c260d7d3f3a452ca22805dae05c6899559761fccc",
  authority_addr: "0x7e56a10f5eb2578d4864e22da8cf30cec3f92d68"```
```

Logs:

```
childchain-0 childchain 2019-05-03 07:36:39.724 [error] module=OMG.API.BlockQueue.Core function=process_submit_result/3 ⋅It seems that authority account is locked. Check README.md⋅
```

Killing the pod and restarting it enabled the Childchain to operate.

**Comment by InoMurko** [comment]
Hmm. Though the logs don’t show that authority account was indeed unlocked when childchain reported it is locked. It just didn’t recover from a locked account. (?)

**Comment by pdobacz** [comment]
Please provide more details here: which version/sha was that? which environment? what eth node? what steps led to this happening?

The log that you cited can only appear on a very specifically matched return from the eth node:

```
%{"code" => -32_000, "message" => "authentication needed: password or unlock"}
```

[source](https://github.com/omisego/elixir-omg/blob/master/apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex#L472)

Unless you're using the distillery releases machinery (which I'm guessing you're not), the config that drives the `authority_addr` is taken in during compilation and rather difficult to alter afterwards, so there's little options here to mis-configure.

**Comment by pdobacz** [comment]
It turned out that the account was locked, so there was no issue. For future reference:

To diagnose, we `remsh`d into `staging` and did:

```
Application.get_all_env(:omg_eth)
Ethereumex.HttpClient.request("personal_listWallets", [], [])
Ethereumex.HttpClient.request("admin_nodeInfo", [], [])
```

to check the `authority_addr`, `contract_addr` and the unlockedness and identity of the exact eth node that the failing instance was speaking too.

As a added benefit, more diagnostics were added to logging, to be able to diagnose more quickly #685
