### ISSUE TITLE
Update Swagger specs

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#690]
For `v0.1` @mederic-p has made excellent job to improve our swagger specs.
Cherry pick these changes and update to the current API state for `master` & `v0.2`.

Add ref to `v0.2` specs in [gh-pages](https://developer.omisego.co/elixir-omg/#introduction) (how :question: )

**Comment by achiurizo** [comment]
Followed up with @pnowosie and this is done via https://github.com/omisego/elixir-omg/pull/744
