### ISSUE TITLE
Allow very thin client transact on omg network

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#698]
Version `v0.2` delivers [EIP-712 signing support](https://github.com/omisego/elixir-omg/pull/623) and we have a few issues to extend apis regarding signatures (e.g. #526 , #693 ). These changes allows us to provide complete apis for `watcher` that simplest wallet could be build based only on `metamask` browser extension and `watcher` integration (without any other client libs).

## Vision
Main idea is to allow thin client (or inexperience developer) to send transaction without knowing much about transaction structure, RLP encoding & signatures.

EIP-712 introduces new `eth_signTypedData` RPC method which receives following __typed_data__ [request](http://eips.ethereum.org/EIPS/eip-712) (see: "Specification of the eth_signTypedData JSON RPC"). 

We can prepare :point_up: all data with the expected structure of typed_data request for the client, so (s)he could just pass it to the `eth_signTypedData` for signing.

Then we will expose endpoint allowing to submit transaction in the form of :point_up: typed_data along with signatures.

## Implementation

Above can be provided in 2 PRs:
__1.__ [:pr: #825] Extending `/transaction.create` response of 2 additional fields in [transaction structure](https://developer.omisego.co/elixir-omg/docs-ui/?url=master/informational_api_specs.yaml#/Transaction/createTransaction):
 * sign_hash - 32-bytes of structural hash,
* typed_data - containing data to perform `eth_signTypedData` (as :point_up:)

__2.__ [:pr: #813] New endpoint `/transaction.submit_typed` - that receives `typed_data` from above and `signatures` array validates `domain` translates transaction to its RLP form and submit with `/transaction.submit` to the ch-ch.

(CC @Pongch to be kept informed)

----
> Original message :point_down: 

## Building blocks

__1.__ Ethereum JSON-RPC's [eth_signTypedData](!missing) endpoint specifies a request schema that allows to sign arbitrary typed data.

__2.__ Watcher's `/transaction.info (better name needed)` endpoint  returns data needed to construct type definition to above `eth_signTypedData` call. Also we can return `eth_signTypedData` request from `/transaction.create`.

```javascript
            types: {
                EIP712Domain: /* EIP-712 domain spec */,
                Transaction: [
                    { name: "input0", type: "Input" }, 
                    /* ... */
                    { name: "output3", type: "Output" },
                    { name: "metadata", type: "bytes32" },
                ],
                Input: [
                     { name: "blknum", type: "uint256" }, /* txindex, oindex */
                ],
                Output: [
                     { name: "owner", type: "address" }, /* amount, currency */
                ],
            },
            domain: {
                name: "OMG Network", /*... verifyingContract, salt */
            },
            primaryType: "Transaction",
            message: { /* transaction data */ }
}
```

This info is needed for each transaction sign and can be fetched once and stored on client side.

__3.__ Watcher's `transaction.create` endpoint returned data adds empty fields so client would know how to fill requst data to metamask

```javascript
 "data": {
    "result": "complete",
    "transactions": [ 
        {
           "inputs": [...],
           "outputs": [...],
           "fee": {...},
           "metadata": "0x...",
           "typedData": {"types":{"EIP712Domain":...},
           "signHash": "0x..."
        }
    ]
```
The only difference from current version is that we extend it with empty inputs / outputs & metadata, to give client information what data need to be provided to metamask signing call.

__4.__ Client constructs `eth_signTypedData` request and call extension to sign a transaction.
__5.__ Client calls watcher's `transaction.submit` providing request's data
```javascript
{
    "transaction": typedData, // Returned from transaction.create
    "signatures": [
        "0xf8d083015ba98080808080940000..."
    ] 
}
``` 

(Edited json for conciseness & readability taking further discussion into account)

**Comment by kevsul** [comment]
In general, I like the idea. A couple of comments:

1. What are the inputs to the `transaction.info` call? Is it the output from `transaction.create`?
2. Another option is to just include this in the return from `transaction.create` e.g. replace the `txbytes` member with `typedData` (JSON stringified ?)
3. We should also return the `hashedTypedData` for clients that want to sign without Metamask.

**Comment by kevsul** [comment]
Also, can `transaction.submit` be modified to take the typed data instead of RPL encoded - as in #526

**Comment by pnowosie** [comment]
> can transaction.submit be modified to take the typed data instead of RPL encoded

Edited above. Absolutely RLP data makes no sense in this context. This means we can support both versions one that accepts RLP-encoded tx & sigs (as now) and the new one (as above)
 
> What are the inputs to the transaction.info call? Is it the output from transaction.create?

It could be new endpoint we accepts no input and returns just data common to all transactions signing. We can return this info also from `/status.get` or `/transaction.create` but it will not change for a particular network

> We should also return the hashedTypedData for clients that want to sign without Metamask.

:yes: `/transaction.create should return this instead of `txbytes`

**Comment by kevsul** [comment]
Ah, ok got it. I misread it the first time and thought that `transaction.info` contained the data, but now I see that it's only the data _specification_, which can be used to transform the actual transaction data into a format accepted by `eth_signTypedData`.

So the idea is make the client be responsible for formatting the data appropriately, right? 
This is the way it is now, except for the domainData and domainSpec is hard-coded into the client (except for the `verifyingContract` value).

I'm not sure that this qualifies as a 'thin' client though - it would be a lot thinner if `transaction.create` returned the transaction already formatted for `eth_signTypedData`

**Comment by pnowosie** [comment]
> it would be a lot thinner if transaction.create returned the transaction already formatted for eth_signTypedData

I'm reluctant to comply fully to format `eth_signTypedData` expects because `/transaction.create`:
* provides more information, e.g. owner, currency & amount for inputs
* provides info about fee which related to tx but useless for signing
also,
* immaturity of eip-712 - all these input0..3, output0..3 quirks imposed by lack of dynamic arrays support,
* could cause some confusion because of difference in presenting tx data in `/transaction.get` and eip-compliant `/transaction.submit`

Maybe it is good idea to have separate endpoint in Watcher which accepts transaction (rlp-encoded or json) and responds with all data required by `eth_signTypedData` ❓

**Comment by whoisjeremylam** [comment]
@T-Dnzt and @Pongch do you have requirements to support client signing that don't require client libraries?

If there aren't any immediate requirements, let's consider this for a future engineering cycle. @pnowosie let me know, and I can help you put in a story in Jira so we don't forget.

**Comment by kevsul** [comment]
> I'm reluctant to comply fully to format eth_signTypedData expects because /transaction.create:
> provides more information, e.g. owner, currency & amount for inputs
> provides info about fee which related to tx but useless for signing

Yes, I agree. I think we would have to provide the `eth_signTypedData` in addition to the other info.

I think it comes down to the choice that we've been discussing for a while now without really committing to a decision i.e. 'thin' vs 'thick' client libs.

1. **'Thick' client.** This is what we currently have, the server (watcher) sends back enough information to create a transaction, but the client needs to know EIP-712 and/or RLP encoding to be able to fully construct and submit that transaction. Any change to the signing process will necessitate a change to all the client libs. The current API can certainly be improved which I think is what you're proposing here, but it doesn't make the clients any thinner.

2. **'Thin' client.** With this model the server would have to send back more / differently formatted data, which the client can sign (via metamask or `ecsign`) and then submit the transaction without any further processing from the client. The advantage here is that the clients will not have to change in response to any update to the signing procedure, be it domain data, the structure of the transaction, or even a change to the EIP-712 standard itself.
I imagine `transaction.create` would return something like:
```
 "data": {
    "result": "complete",
    "transactions": [ {
  "inputs": [...],
  "outputs": [...],
  "fee": {...},
  "metadata": "0x...",
  "typedData": {"types":{"EIP712Domain":...},
  "signHash": "0x..."
}
]
```
And `transaction.submit` would take as input:
```
{
    "transaction": typedData, // Returned from transaction.create
    "signatures": [
        "0xf8d083015ba98080808080940000..."
    ] 
}
```

**Comment by pnowosie** [comment]
> ...to support client signing that don't require client libraries?

@whoisjeremylam - I see RLP encoding and EIP-712 as a additional complexity, very low-level complexity that any client lib has to consider. I'd like to remove these pain points from the Watcher's API that it could communicate with plain json that everybody understands.

Above in my opinion provides many benefits to the Watcher and client libraries as well. Watcher more easily can change its internals because they are hidden from clients. Client libraries don't need to understand all internal Watcher quirks to be able to send successful transaction.

I think it does not undermine the efforts with e.g. `omg-js`. Making client libs easier to implement contributes to broader adoption. 
`omg-js` provides higher level api that many people prefers to deal with. It also could focus on real value for its user that to satisfy watcher with eip & rlp.

**Comment by pnowosie** [comment]
@kevsul - I dared to improve json formatting in your `/transaction.create` output.
I like the idea besides the redundancy it makes it dumb simple to sign & submit tx ❗️

**Comment by Pongch** [comment]
@pnowosie great work 👍  I got some questions about the API.

1. it seems what is changed on `transaction.create` is the additional 2 fields, so its safe to believe things are still backward compatible with omg-js ?
2. Do we require `/transaction.submit_typed` to be a new endpoint ? 
3. Can the user use `ecsign()` to sign transaction as opposed to `eth_signTypedData ` ?

btw, I'm using this document as a reference to understand the flow of the transaction build/sign process: 
https://github.com/omisego/omg-js/blob/master/integration-docs/signing-methods.md
With this in mind I'm trying to come to terms with which exact process in the life cycle of the transaction will get replaced.

**Comment by pnowosie** [comment]
Answering @Pongch questions

1. __Yes__ `transaction.create` should be backward compatible if `omg-js` does not strictly validate response schema
2. __Yes__ , it will be easier to document. `/transaction.submit_typed` receives just json, so would provide much broader validation to help user investigate issues. There will be no issues if user pass typed_data created by `/transaction.create`
3. __Yes__ this would be and option too. User can `ecsign` transaction.create response's `sign_hash` to produce same signatures as `eth_signTypedData`

**Comment by pdobacz** [comment]
hopping on this to provide some help on this part:

> 1. Extending /transaction.create response of 2 additional fields in transaction structure:

 - rudimentary integration test to check the flow `transaction.create`->`EthRPC.eth_signTypedData`
 - getting out pieces to fill out the structure required by the latter out of our `elixir-omg` EIP712 module
