### ISSUE TITLE
Create scripts to setup the elixir-omg project

### ISSUE THREAD

**Issue by achiurizo** [omisego/elixir-omg#712]
:clipboard: [PLAN-244](https://omisego.atlassian.net/browse/PLAN-244)

As a developer of elixir-omg, I have easy set up scripts for my development environment, So that I can get started quickly

**Comment by jbunce** [comment]
From the root of the `elixir-omg` directory: `docker-compose -f docker-compose-full-services-mac.yml up` will start everything for you. If there's something that needs to be improved please let me know :)
