### ISSUE TITLE
Standalone Watcher deployment

### ISSUE THREAD

**Issue by achiurizo** [omisego/elixir-omg#713]
:clipboard: [PLAN-226](https://omisego.atlassian.net/browse/PLAN-226)

As a user, I would like to easily deploy a standalone Watcher, so that I can validate transactions myself without relying on 3rd party.

Business Benefit for OmiseGO

less load on the OmiseGO watcher service

Business Benefit for Users

No need to trust Operator’s watcher 

Business Risk

having too many Watcher maintaining multiple Child chain connections could crash our network, resulting in downtime 

Design Description

a one-click installation or multi-step but concise guide to deploying your own local watcher on your infrastructure 

Ideally a Docker container of some kind

This is for development/local deployment as opposed to production

**Comment by jbunce** [comment]
This is possible now with our existing tooling. Would you like a demo some time?

**Comment by achiurizo** [comment]
@jbunce awesome! A demo would be great 😄 Do you have a PR/doc on how to do this?

**Comment by Pongch** [comment]
That is great ! I did see that there is a Watcher specific Docker file now. Is the individual deployment process of that quite simple ? or is it still coupled with other services still

**Comment by jbunce** [comment]
@Pongch Ignore that Dockerfile. It's for releases. We're always coupled with the Postgres (at least for the informational Watcher service) and the Ethereum connectivity client.

@achiurizo No documentation yet but you can derive it from the `docker-compose`: 

1) Build the Dockerfile or grab it from the latest push.

```
docker run -d -p 7434:7434 --env MIX_ENV=prod --env ETHEREUM_NETWORK= RINKEBY --env RINKEBY_CONTRACT_ADDRESS=<snip> --env RINKEBY_TXHASH_CONTRACT=<snip> --env RINKEBY_AUTHORITY_ADDRESS=<snip> --env ELIXIR_SERVICE=WATCHER --env CHILD_CHAIN_URL=http://childchain.fqdn.net:80 --env DATABASE_URL=postgres://<snip> --env ETHEREUM_RPC_URL=http://geth:8545
```

**Comment by jbunce** [comment]
If it makes life easier I can create a Watcher specific `docker-compose` that stands up a local Postgres instance too to synchronise with an already running Childchain?

**Comment by Pongch** [comment]
I think a watcher specific `docker-compose` would be great for this story. Question RE: this setup, aside from the Postgres, do we also have to specify the Rootchain contract and Ethereum client endpoint ? would a remote RPC such as infura work fine for informational watcher ?

**Comment by jbunce** [comment]
I think PR736 means we can close this now?

**Comment by jbunce** [comment]
For completeness:

> do we also have to specify the Rootchain contract and Ethereum client endpoint

@Pongch There isn't a way around this. Who knows which Childchain the user wants to connect with? Maybe they want to use a mainnet instance. Maybe they want to use a Rinkeby instance.

**Comment by Pongch** [comment]
ah yes, my question was actually around how that was done. ie, is it put in as an optional flag ? or as a field inside YAML file. But that's alright, I just doubled checked and there's fields for RPC client and Childchain. We can close this 👍 great job !

**Comment by pdobacz** [comment]
taking the liberty to close, done in #736 with later fixes
