### ISSUE TITLE
Revise websocket API for notifications

### ISSUE THREAD

**Issue by achiurizo** [omisego/elixir-omg#716]
:clipboard: [PLAN-192](https://omisego.atlassian.net/browse/PLAN-192)

As a venue connected to the DEX or an eWallet
I can subscribe by a websocket
So I can receive notifications when payments are made to or received by the wallets that I manage

As both eWallet and an Exchange, I would like to be able to replay the transactions from a certain number of blocks,
so that in case my connections have dropped off- I can retrieve the past transactions I’ve missed and maintained consistent state.

**Comment by Pongch** [comment]
Question: How do we handle sequencing for clients when they disconnect/get lost
Ans: when the clients get disconnected, they will need to reopen a socket connection with a topic that details which blocknumber to resubscribe from ie, `transfer:ADDRESS:BLKNUM`

Question How do we connect? (authentication?)
Ans: No authentication needed

Question: What do the messages look like ?
Ans: Messages should still look similar to the current implementation. (I have linked a copy of what the message payload will look like below)

Question: How ‘old’ of information do we send to users?
Ans: Financial systems usually gather activities per cycles and once they’re done a cut off occurs where they get pushed into the back office. That can also happen on a per transaction basis when transaction processing is submitted. For our use case, a client should be able to specify how old this data we want is. It is totally okay for the data requested to be tool old and for the server to return an error response
