### ISSUE TITLE
Etherscan: developer can interact with the root chain contract to find out parameters

### ISSUE THREAD

**Issue by achiurizo** [omisego/elixir-omg#717]
:clipboard: [PLAN-208](https://omisego.atlassian.net/browse/PLAN-208)

As a developer building on OMG network, I would like to be able to go on Etherscan and interact with Plasma Chain’s contract directly, so that I can know what’s going on with my transactions.

- [x] Document this process

**Comment by pthomalla** [comment]
@jbunce @achiurizo, 
documentation of process:
https://docs.google.com/document/d/1fiWp3ZkPARymgKjrsOYez5F_w-5mQ1WHzg_s-vEZeF8/edit?usp=sharing

**Comment by pnowosie** [comment]
Thanks @pthomalla 
:point_up: we were unable to publish contracts code for **samrong** - it might be due to different compiler settings used during deployment or the other commit was used than it's now HEAD of v0.2.

Following these steps on fresh deployments should work.

**Comment by pthomalla** [comment]
we were able to attach the contract code to the **samron**

**Comment by pdobacz** [comment]
Hey, bumping the thread here @achiurizo @Pongch how does this look? Samrong is verified at https://rinkeby.etherscan.io/address/0x740ecec4c0ee99c285945de8b44e9f5bfb71eea7#contracts, the manual process seems documented (see one comment below).

Are we ticking this off as completed (it is in review now), or still in RFC phase?

Next question: are we calling it a day here, or shall we do a follow-up story and try to leverage e.g. [etherscan's API](https://etherscan.io/apis#contracts) (disclaimer: I haven't checked whether it is feasible at all, the docs just say that this is beta but possible)?

(comment on the manual process: did you do the commenting/removing of `import` statements by a bash script, like the concatenation @pthomalla? if yes then let's include the command/script in the doc, this seems like a pain step)

**Comment by pnowosie** [comment]
If I recall it (from status meeting), the only left off was to put this document into our confluence. @pthomalla is up to find where it should fit in confluence and close this then.

**Comment by pnowosie** [comment]
> (comment on the manual process: did you do the commenting/removing of import statements by a bash script

No of course we used VS Code :joy:
