### ISSUE TITLE
Find Transaction by Metadata hash

### ISSUE THREAD

**Issue by achiurizo** [omisego/elixir-omg#722]
:clipboard: [PLAN-257](https://omisego.atlassian.net/browse/PLAN-257)

As an end user who uses metadata field as a receipt, I would like to be able to retrieve the information about my transaction based on the hash of the metadata 

- [ ] may already be implemented
- [ ] add documentation

**Comment by pnowosie** [comment]
Already implemented. Tested on `samrong` env.
[API spec](https://developer.omisego.co/elixir-omg/docs-ui/?url=informational_api_swagger.json#/Transaction/transactions_all) recently updated.
