### ISSUE TITLE
Add transaction.all pagination

### ISSUE THREAD

**Issue by kasima** [omisego/elixir-omg#725]
As a consumer of the transction.all API
I can get paginated results
So I can potentially get all the results instead of just the first 200 matches

**Comment by pnowosie** [comment]
ewallet Paginator seems to verbose for our needs.
• Request in addition to existing `limit` adds `page` (defaults to 0)
• Response will contain additional field sibling to `data`
```data_paging: { 
      limit: number,
      page: number
}
```

Appreciate any input guys @kevsul @Pongch @jarindr

**Comment by Pongch** [comment]
Looks good, I've used similar pagination style in the past. As long as we default empty `page` field value to 1. Whats the error returned on the page number that doesn't exist ? would this be empty result as you said ?

**Comment by kevsul** [comment]
Looks fine to me @pnowosie
