### ISSUE TITLE
Decouple the smart contract deployment mechanism from the Childchain

### ISSUE THREAD

**Issue by jbunce** [omisego/elixir-omg#734]
For all deployments of the Childchain we use `dev_helpers()` to deploy the rootchain contract to Ethereum. This makes automated service deployment difficult as `dev_helpers()` is only available with `MIX_ENV=dev`. 

We need to:

- Define the process for deploying the contracts outside of the application
- Select tooling to use for contract deployment

Some discussion points:

- @InoMurko suggested abstracting `dev_helpers()` into a separate tool
- Sync up with the research guys on https://github.com/omisego/plasma-contracts/issues/103
- I've flattened the contracts and tried to deploy via Remix (with no success so far)
- The Childchain authority address is required to be a "fresh" account due to the nonces problem (@pdobacz could you add a bit more on this please?)

**Comment by pdobacz** [comment]
> The Childchain authority address is required to be a "fresh" account due to the nonces problem (@pdobacz could you add a bit more on this please?)

with pleasure: see https://github.com/omisego/elixir-omg/pull/737. This question gets asked from time to time so I decided to put that in the docs.

**Comment by kevsul** [comment]
I think this should be fairly easy with Truffle. As a quick test, I've been able to deploy the contracts with this Truffle snippet:
```
var PriorityQueueLib = artifacts.require('./PriorityQueueLib.sol')
var PriorityQueueFactory = artifacts.require('./PriorityQueueFactory.sol')
var RootChain = artifacts.require('./RootChain.sol')

module.exports = function (deployer, network, accounts) {
  deployer.deploy(PriorityQueueLib)

  deployer.link(PriorityQueueLib, PriorityQueueFactory)
  deployer.deploy(PriorityQueueFactory)

  deployer.link(PriorityQueueFactory, RootChain)
  deployer.deploy(RootChain)
}
```
That doesn't do the `init()` call by the authority address, but that should be easy to add, either by
creating and funding a new address here or by passing one in via config.

**Comment by jbunce** [comment]
Nice one, thanks @kevsul! Reckon it's best to separate the creation and funding the authority address, then calling of `init()`? Or write all in the same module?

Also how build the project and get the contracts? `truffle init` then copy the contracts to `./contracts`?

**Comment by kevsul** [comment]
> Nice one, thanks @kevsul! Reckon it's best to separate the creation and funding the authority address, then calling of `init()`? Or write all in the same module?

I would separate it. I imagine that at some point we'll need to get more careful about the authority private key (e.g. put it in a HSM or something), so let's plan for that.

> Also how build the project and get the contracts? `truffle init` then copy the contracts to `./contracts`?

Yeah, `truffle init` will create a `truffle.js` config file which may need tweaking. The contracts are already in `./contracts`. Give me a shout offline and I'll walk you through the process

**Comment by boolafish** [comment]
[Note] In our truffle meeting call, we make the decision to move forward using truffle for deployment.

**Comment by InoMurko** [comment]
Issue https://github.com/omisego/plasma-contracts/issues/115
