### ISSUE TITLE
Watcher not reporting `byzantine_events` after detecting unchallenged_exit

### ISSUE THREAD

**Issue by kasima** [omisego/elixir-omg#784]
From the [Samrong availability incident](https://github.com/omisego/devops/issues/100), the watcher returned an empty `byzantine_events` array, even after logging:

```
2019-06-13 12:56:32.656 [warn] module=OMG.Watcher.BlockGetter.Core function=consider_exits/2 ⋅Chain invalid when taking exits into account, because of {:error, :unchallenged_exit}`
```

The `byzantine_events` array did get populated after a restart of the watcher. 

Additionally, the `:error` in the log was empty after restart:

```
2019-06-17 05:09:53.686 [warn] module=OMG.Watcher.BlockGetter function=do_sync/1 ⋅Chain invalid when trying to sync, because of {:error, []}, won't try again⋅
```

**Comment by pdobacz** [comment]
For completeness, the reported empty (as far as byz.-events go) response from the Watcher, in its entirety:

```
{"data":{"byzantine_events":[],"contract_addr":"0x740ecec4c0ee99c285945de8b44e9f5bfb71eea7","eth_syncing":false,"in_flight_exits":[],"last_mined_child_block_number":246000,"last_mined_child_block_timestamp":1560670156,"last_seen_eth_block_number":4573892,"last_seen_eth_block_timestamp":1560738154,"last_validated_child_block_number":238000,"last_validated_child_block_timestamp":1560430586,"services_synced_heights":[{"height":4553388,"service":"block_getter"},{"height":4573879,"service":"challenges_responds_processor"},{"height":4573879,"service":"competitor_processor"},{"height":4573881,"service":"convenience_deposit_processor"},{"height":4553388,"service":"convenience_exit_processor"},{"height":4573881,"service":"depositor"},{"height":4573879,"service":"exit_challenger"},{"height":4553388,"service":"exit_finalizer"},{"height":4573879,"service":"exit_processor"},{"height":4553388,"service":"ife_exit_finalizer"},{"height":4573879,"service":"in_flight_exit_processor"},{"height":4573879,"service":"piggyback_challenges_processor"},{"height":4573879,"service":"piggyback_processor"},{"height":4573891,"service":"root_chain_height"}]},"success":true,"version":"1.0"}'

```

Also, I think it was block #239000 from eth height 4553417 that had the invalidating tx, which seems to not had yet been applied according to the full response provided:

> `"services_synced_heights":[{"height":4553388,"service":"block_getter"}, ...`

I am however unable to find the log report from June 13th in datadog, it would be very helpful to have the context of that log to investigate further.

**Comment by pdobacz** [comment]
After investigation (details in the incident cited), turns out that the absence of the event was due to fact that the event was challenged after Watcher logging/halting and before us calling `status.get`.

The "empty error" in the log is confusing but unrelated to the suspected issue at hand (these would be additional information shown in some other halting conditions).

Closing and deferring to #811 to improve the responses to give better and more complete picture of the byzantine events at hand.
