### ISSUE TITLE
expose root chain exit transactions in api

### ISSUE THREAD

**Issue by jrhite** [omisego/elixir-omg#801]
Needed to support omisego/omg-block-explorer#14

**Comment by Nikodemek18** [comment]
@jrhite let's split it into smaller parts. Let's consult with Piotr

**Comment by jrhite** [comment]
@Przemyslaw Mirowski <slava@omisego.co>  I'm on it. I'll break it up and
put references to it in our project board. -- but you we need to discuss
with thibault as well if we're going to just create a shared MW/BE project
board.

**Comment by Nikodemek18** [comment]
@jrhite as far as we gonna keep there all things related to backend and frontend stuff for MW/BE - I'm in favor of one board. 

Let me know when we have this issues split .

**Comment by jrhite** [comment]
Closing this in favor of smaller issues...

https://github.com/omisego/elixir-omg/issues/1088
https://github.com/omisego/elixir-omg/issues/1089
https://github.com/omisego/elixir-omg/issues/1090
https://github.com/omisego/elixir-omg/issues/1091
