### ISSUE TITLE
Watcher does not sync with Eth node

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#802]
Observed locally and on development env.

__To reproduce:__ Run Watcher, call `/status.get` and remember `last_seen_eth_block_number`
Call endpoint again, notice the value does not change.

After Watcher restart it will sync until the current block and won't get newer. 

Suspected culprit #772

**Comment by pnowosie** [comment]
Issue caused by inappropriate `parity` configuration. It was run with `--no-ws` but EthereumClientMonitor listens to web socket events.
After removing above flag, there was log message in parity `Blocked connection to WebSockets server with untrusted host: Some("localhost")`
It was solved by adding `--ws-hosts=all` optition.

**Comment by pdobacz** [comment]
note after discussions: issue seems 2-fold at first glance:
1/ improve docs/`geth` & `parity` invocations/scripts what not to always sport the required flags
2/ figure out why did the inability to open the websocket conn fail tacitly
