### ISSUE TITLE
Path to OMG.DB location does not respect configuration

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#803]
Location of OMG.DB files seems to be hardcoded.

__To reproduce:__
1. Create folder if not exits `~/.omg/my_folder`
2. Configure `:omg_db, leveldb_path: "~/.other_omg/data"`
3. Run init: `mix run --no-start -e 'OMG.DB.init()' --config <path_to_config_file.exs>`

Above should fail with error: `module=OMG.DB.LevelDB function=do_init/2 ⋅Unable to init: {:error, :leveldb_not_empty}⋅`

When you empty default location `~/.omg`, database will be initiated there despite configuration value.

**Comment by pdobacz** [comment]
this looks quite outdated now - neither config names nor `LevelDB` exist anymore. The configuration machinery has been revamped since then. I'd say close and use different issues if problem persists.
