### ISSUE TITLE
High Watcher Database Writes & Phoenix 500s

### ISSUE THREAD

**Issue by jbunce** [omisego/elixir-omg#809]
During a resync of Ari's Watcher (drop tables & leveldb, sync to Ari Childchain) high database write operations were observed:

```
watcher-0 watcher 2019-06-25 15:46:35.951 [info] module=OMG.Watcher.DB.Transaction function=update_with/1 ⋅Block #17607000 persisted in DB done in 38857.486ms⋅
```

During high write operation times the Phoenix API returns HTTP 500 codes on URI path `/status.get` (called by the Blockexplorer):

```
watcher-0 watcher 2019-06-25 16:02:36.274 [info] module=OMG.Watcher.DB.Transaction function=update_with/1 ⋅Block #25440000 persisted in DB done in 15096.791ms⋅
watcher-0 watcher 2019-06-25 16:02:36.320 [info] module=Phoenix.Logger function=phoenix_error_render/3 request_id=2mlnou1773gja5444k010a61 ⋅Converted exit {:timeout, {GenServer, :call, [OMG.Watcher.BlockGetter, :get_events, 5000]}} to 500 response⋅
watcher-0 watcher 2019-06-25 16:02:36.321 [error] module=OMG.Watcher.Web.View.ErrorView function=template_not_found/2 request_id=2mlnou1773gja5444k010a61 ⋅Unhandled error occurred most likely in controller / API layer: %{__phx_template_not_found__: OMG.Watcher.Web.View.ErrorView, conn: %Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{kind: :exit, layout: false, reason: {:timeout, {GenServer, :call, [OMG.Watcher.BlockGetter, :get_events, 5000]}}, stack: [{GenServer, :call, 3, [file: 'lib/gen_server.ex', line: 989]}, {OMG.Watcher.API.Status, :get_status, 0, [file: 'lib/api/status.ex', line: 47]}, {OMG.Watcher.Web.Controller.Status, :get_status, 2, [file: 'lib/web/controllers/status.ex', line: 29]}, {OMG.Watcher.Web.Controller.Status, :action, 2, [file: 'lib/web/controllers/status.ex', line: 15]}, {OMG.Watcher.Web.Controller.Status, :phoenix_controller_pipeline, 2, [file: 'lib/web/controllers/status.ex', line: 15]}, {OMG.Watcher.Web.Endpoint, :instrument, 4, [file: 'lib/web/endpoint.ex', line: 15]}, {Phoenix.Router, :__call__, 1, [file: 'lib/phoenix/router.ex', line: 275]}, {OMG.Watcher.Web.Endpoint, :plug_builder_call, 2, [file: 'lib/web/endpoint.ex', line: 15]}]}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "watcher.ari.omg.network", method: "POST", owner: #PID<0.11742.2>, params: %{}, path_info: ["status.get"], path_params: %{}, port: 80, private: %{phoenix_endpoint: OMG.Watcher.Web.Endpoint, phoenix_format: "json", phoenix_layout: false, phoenix_template: "500.json", phoenix_view: OMG.Watcher.Web.View.ErrorView}, query_params: %{}, query_string: "", remote_ip: {0, 0, 0, 0, 0, 65535, 2708, 62}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "watcher.ari.omg.network"}, {"accept-encoding", "gzip"}, {"cf-ipcountry", "US"}, {"cf-ray", "4ec82a918c98d990-SIN"}, {"content-length", "0"}, {"x-forwarded-proto", "http"}, {"cf-visitor", "{\"scheme\":\"https\"}"}, {"accept", "application/json, text/plain, */*"}, {"content-type", "application/json"}, {"user-agent", "axios/0.18.0"}, {"cf-connecting-ip", "35.247.140.201"}, {"cdn-loop", "cloudflare"}, {"x-cloud-trace-context", "3b4db478cf0483c815cbac0b1166fabd/14347548258714057383"}, {"x-goog-cloud-trace-parent", "00-3b4db478cf0483c815cbac0b1166fabd-c71cbb1fee6cfaa7-00"}, {"via", "1.1 google"}, {"x-forwarded-for", "35.247.140.201, 172.68.146.226, 35.201.85.215"}, {"connection", "Keep-Alive"}], request_path: "/status.get", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: 500}, kind: :exit, reason: {:timeout, {GenServer, :call, [OMG.Watcher.BlockGetter, :get_events, 5000]}}, stack: [{GenServer, :call, 3, [file: 'lib/gen_server.ex', line: 989]}, {OMG.Watcher.API.Status, :get_status, 0, [file: 'lib/api/status.ex', line: 47]}, {OMG.Watcher.Web.Controller.Status, :get_status, 2, [file: 'lib/web/controllers/status.ex', line: 29]}, {OMG.Watcher.Web.Controller.Status, :action, 2, [file: 'lib/web/controllers/status.ex', line: 15]}, {OMG.Watcher.Web.Controller.Status, :phoenix_controller_pipeline, 2, [file: 'lib/web/controllers/status.ex', line: 15]}, {OMG.Watcher.Web.Endpoint, :instrument, 4, [file: 'lib/web/endpoint.ex', line: 15]}, {Phoenix.Router, :__call__, 1, [file: 'lib/phoenix/router.ex', line: 275]}, {OMG.Watcher.Web.Endpoint, :plug_builder_call, 2, [file: 'lib/web/endpoint.ex', line: 15]}], view_module: OMG.Watcher.Web.View.ErrorView, view_template: "500.json"}⋅
watcher-0 watcher 2019-06-25 16:02:36.323 [error] ⋅#PID<0.11742.2> running OMG.Watcher.Web.Endpoint (cowboy_protocol) terminated
```

The database resource utilisation metrics do not provide anything indicative of constraints to fulfil these options.

For further investigation I'd suggest:

- Profiling the full path of getting a block from the Childchain, Ethereum calls, verification, and writing it to Postgres
- Verification of the order of operations: is the database write bound to an Ethereum RPC call or another operation?
- Checking if Elixir has its own TCP/IP stack like Rust and monitoring options
- Monitoring TCP RST/session drops from the database connection

**Comment by kasima** [comment]
> Verification of the order of operations: is the database write bound to an Ethereum RPC call or another operation?

Do we have any visibility on the state of geth at the time?

**Comment by jbunce** [comment]
We are limited as to my knowledge there isn't the RPC logging with Geth like there is Parity. If there were a problem with Ethereum connectivity I'd expect there to be alarms raised, like @InoMurko implemented previously.

I think it's worth checking that processes aren't bound together - not just Ethereum, but BlockGetter actions et. al. too.

**Comment by pnowosie** [comment]
I believe it was resolved in #745 
`/status.get` called BlockGetter, which was on heavy load.
Please confirm @pdobacz

**Comment by jbunce** [comment]
@pnowosie @pdobacz were any other APIs checked if a child process needs to be implemented too?

**Comment by kasima** [comment]
If this is fixed in Samrong, I don't think this needs to be back ported to support the Hoard event.

**Comment by jbunce** [comment]
The Hoard event will be on Samrong. So as long as it's included and if @pdobacz can confirm this the resolution is in v0.2 we are safe. I can test this before too.

**Comment by pdobacz** [comment]
the `status.get` unavailability during sync should have been resolved in https://github.com/omisego/elixir-omg/pull/701 and ported over to `master`/`v0.2` in https://github.com/omisego/elixir-omg/pull/705.

as for the Postgres activity - known issue.

there's a series of >10K tx blocks on Ari around that height

Some picking around optimizing the inserts were done, but still they take a long time - that's why we have the security critical vs informational API design on the table

> @pnowosie @pdobacz were any other APIs checked if a child process needs to be implemented too?

I spent some time analyzing, and it turned out `BlockGetter` is the only blocker (pun intended) and it was only called to get what `status.get` was getting, which is now resolved. The other processes should be much more responsive even when working on syncing.

**Comment by jbunce** [comment]
> as for the Postgres activity - known issue.

What's the issue? Is it documented somewhere? How much is this going to bite us when we get hit with load soon?

**Comment by pdobacz** [comment]
> What's the issue? Is it documented somewhere?

it was in pivotal tracker somewhere. 

Also note that officially, our tps target for watcher syncs is more or less met (300tps on the child chain). That the postgres inserts make Watcher sync @ ~1000tps has been mulled over many times. Tuning sync throughput/performance has been explicitly put on low priority.

**Comment by kasima** [comment]
I believe @whoisjeremylam migrated all the PT stories to Jira – can we hunt it down?

**Comment by jbunce** [comment]
Confirmed that the `v0.2` Watcher is not susceptible to this condition.

**Comment by whoisjeremylam** [comment]
If we need to hunt down the story, @Pongch should be able to find it.

**Comment by Pongch** [comment]
As long as this is not a concern on v0.2 then we are safe, but for completeness, I will try to hunt for this PT/Jira issue.

**Comment by Pongch** [comment]
I found the issue, I believe this is `OMG-321 - Optimize postgres INSERTS` which is what happened during Devcon. Although it appears to be more or less resolved.

**Comment by pdobacz** [comment]
Hm... in terms of the larger picture-story there was one more, one sec... ah there it is `OMG-295 - Minimize sync/catch-up time for Watcher` - details therein (taken from PT):

> Story: wallet provider - wants to catch up with Watching of the child chain as fast as possible after downtime of the Watcher.
> 
> This probably should leverage the following:
> 1/ #161280323/#161808704 - to have the Watcher and Postgres separate and filterable, to be able to limit the heavy data keeping
> 2/ security critical functionality should be baked by OMG.DB data then stop writing to Postgres database in security-critical mode
> 3/ #156034783 - to have a quick OMG.DB (probably not relevant)
> 4/ #161743983 Check out COPY FROM Postgres feature to possibly continue to use brute-force or speed up bulk inserts. There are articles on using COPY FROM with Ecto. Also other low-hanging optimizations in postgres (in --conenience mode)
> 
> includes figuring out the requirements for the catch up - how fast do we want this to happen and and what kind of hardware? how does one configure the filtering?

**Comment by pnowosie** [comment]
:notebook: regarding pg optimization, there is work already done #723 further improvement can based on.
