### ISSUE TITLE
Unify use of hex encoders, drop unneccesary

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#816]
Align with other hex values validation which accepts "0x"-prepended mixed case hex string.
https://github.com/omisego/elixir-omg/blob/53dc46f80eca374c64983aacd37bd6851ec794f4/apps/omg/lib/omg/fees.ex#L117

**Comment by pdobacz** [comment]
when at it, we could groom the hex encodings. All RPC-related codecs are somewhere at `OMG.Utils.RPC.Encoding` I think (or similar, can't remember), all `Eth`-related codecs are in `OMG.Eth.Encoding` (effectively the same impl, just elsewhere for separation of concerns).

The fee json stuff (and possibly other remaining, which are neither of the above) - not sure what about them, it depends on where and how many are there.

**Comment by pnowosie** [comment]
I'm up to leave only these two RPC & Eth related and ditch the rest... Too many hex formatters :smirk_cat:
