### ISSUE TITLE
Watcher can't subscribe to `newHeads` to pull new blocks

### ISSUE THREAD

**Issue by pdobacz** [omisego/elixir-omg#817]
Spotted by @jbunce on `development` - after making the failure to subscribe loud in #807, it started telling us it can't `2019-06-26 08:51:49.716 [warn] module=OMG.EthereumClientMonitor function=handle_continue/2 ⋅Ethereum client monitor failed at WS newHeads subscription. Health check in 4500⋅`

Before #807 and after #772 `development` was likely not syncing (behavior observed by @pnowosie).

`parity` invocation used appears to be correct:

```
parity -l rpc --ws-hosts=all --ws-interface=all --ws-origins=all --chain=rinkeby.json --jsonrpc-apis personal,eth,web3,parity_accounts --jsonrpc-hosts=* --jsonrpc-interface=all
```

It has been confirmed that one can subscribe to `logs` using `wscat`: https://gist.github.com/jbunce/1ae88e2a4bb3a620839b66f6e337aaee

@pnowosie has been able to sync a local watcher to one of our deployments, after amending the `parity` invocation.

**Comment by InoMurko** [comment]
Of it couldn’t subscribe- wasn’t an alarm raised all the time?

**Comment by pdobacz** [comment]
this was an issue with the configuration.

`ETHEREUM_WS_RPC_URL` was missing entirely or missing a `/ws` suffix which worked fine when running things locally, using the default value:

https://github.com/omisego/elixir-omg/blob/2b203604e1a115fd3fa7a42045a717d6d1a6aff5/apps/omg_eth/config/config.exs#L21

Fixing the config fixed the issue
