### ISSUE TITLE
supporting tool to be ready to handle new tx data structs

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#845]
As a OmiseGO developer and integrator, I would like to use my dev tools that support the new tx data. So that I can keep up with the changes introduced in abstract layer

**Risk**

- breaking changes that are non-backward compatible with older client libs

**Value**

- integrators can easily integrate with abstract layer design feature

**Comment by achiurizo** [comment]
@Pongch What dev tools are we looking for here? In terms of interacting with the protocol transaction format and sending it to the contracts, we have https://github.com/omisego/ex_plasma which is client library to the plasma contracts.

**Comment by Pongch** [comment]
oh, this issue is probably solved way back from the looks of it 👍 this is referring omg-js and the likes. I will close it
