### ISSUE TITLE
Operator key management & production contract deployment

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#854]
NET-84

As an network operator, I would like to make sure my authority wallet is well protected, so that the security of the network will not get compromised.

**Value**
- No key is hosted on Ethereum nodes
- Encrypted key material in a secure enclave
- Authenticated access from the Operator to submit blocks

**Comment by jbunce** [comment]
I don't think this is an `elixir-omg` story. Let's chat tomorrow.

**Comment by boolafish** [comment]
probably related or not, but do we want the ability to rotate our key for operator?
