### ISSUE TITLE
Complete security critical watcher under high load

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#855]
NET-83

As a security-concerned application provider, I would like to ensure the security critical watcher will work on DOS condition, so that I know my funds are secured

**Value**
- ensure security functionalities are completed
- validate security-critical functionality of the watcher works under load

**Comment by pnowosie** [comment]
I had an impression this task is about producing high number of exits on rootchain and test we were warned by watcher and could exit.
@Pongch, @pdobacz  can we refine requirement a little. Thanks.

**Comment by pdobacz** [comment]
That was my understanding - how do the security functionalities behave when there are:
1/ lots of exits in general
2/ big blocks
3/ lots of invalid standard exits
4/ lots of valid/invalid IFEs, in all possible flavors

(1/) alone has been tested in `v0.1` times, now lets go for the (1/-4/). @Pongch's description is more general, but I think this boils down to that. If anything else is required, lets has it out.

**Comment by Pongch** [comment]
⬆️  Yes, let's define all the cases together, feel free to add more if any is missing. Afterwards, we can coordinate and create tasks that would invoke the different conditions.

**Comment by pthomalla** [comment]
steps to check how security-critical watcher will behavior on large number on different exits
1. generate history on chilld_chain (using performance test)
2. run workers that will generate different byzantine event and correct various types of exits

workers:
- generate proper exit: using watcher api to check available utxo
- generate invalid exit: random download block from child_chain, and use some transaction to generate exit (we can specify which utxo is speeded by size of value or using information from the correct exit)
- unchallenged exit: don't challenge part of invalid exit and check after sla margin if all appeared
- non canonical ife: random download block from child_chain
    randomly change trancaction (use mutation: change input/output order, remove ouput/input/metadata, add output/input/metadata, change value of utxo)
- piggyback available: make canonical ife  
- invalid piggyback: make canonical ife that output was spended and piggyback it

**Comment by pdobacz** [comment]
@pthomalla Thanks, looking good! Just jumping in with a quick comment:

> unchallenged exit:

I think you can forget about this (or put it very last on the list, as optional). I anticipate no effects on performance/availability of the security critical features under that condition.

OTOH, make sure please include checking:
 - ability to generate proper IFE under load
 - invalid input piggybacking

**Comment by pdobacz** [comment]
Closing as the work here done has become stale, considering the directions taken with the perf testing effort.
