### ISSUE TITLE
Add alerts for when values are too high/low

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#856]
NET-64

As a child chain operator, I would like to have alerts when certain metrics are too high/low, so that I can rely on automation to fix the problem.

*UPDATE*
punt automation into separate issues.

**Comment by InoMurko** [comment]
Blocked at the moment with DD issues.

**Comment by Pongch** [comment]
Could you point to the blocking issue @InoMurko  ?

**Comment by InoMurko** [comment]
Ehmmm no. But ping me on slack.

**Comment by Pongch** [comment]
Update: We already have a duplicated GH issue, will remove this in favor of tracking the other one from `devops`
