### ISSUE TITLE
Tidy logging and alert on events that require action

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#857]
NET-65

As a child chain operator, I would like to tidy up application logging and alerts so that I can use less computing resources

**Comment by InoMurko** [comment]
hey @Pongch is there a specific log causing this issue?

**Comment by Pongch** [comment]
I thought I forgot to put the extra details, but turns out I put them in the wrong GH issue...whoops. 

Updating now. This story first surfaced from DevOps side, I will see if I can get a more defined description to this

**Comment by Pongch** [comment]
Update: We already have a duplicated GH issue, will remove this in favor of tracking the other one from `devops`
