### ISSUE TITLE
OMG.DB.Init() requires now to populate deffered config

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#862]
or we should prepare Mix.Task for it as @pdobacz suggested
> maybe it's easier to patch the Mix.Task together for the `OMG.DB.init()`? hm, but one would then have to DRY the code with respect to code that exists already for the distillery-based command to do the `OMG.DB.init()`

**Comment by InoMurko** [comment]
I don't think this is an issue TBH. What did you try to do? There are reasonable _paths_ of development but we absolutely cannot support every single way a developer would like to use the codebase.
If your intention was to start `watcher` or `child chain` there are two ways of doing it. One is via `launcher.py` that still works but it'll get deprecated eventually and the docker container way, which should still work. Is there a problem in these two methods?

**Comment by InoMurko** [comment]
Aha! Looked at the `launcher.py` and the way the KB db is initialized is 
```
    def initialise_childchain_database(self) -> bool:
        ''' Initialise the childchian database (chain data store)
        '''
        result = subprocess.run(
            "mix run --no-start -e 'OMG.DB.init()'",
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            shell=True
        )
        if result.returncode == 0:
            logging.info('Childchain database initialised')
            return True
        logging.critical(
            'Could not initialise the database. Error: {}'.format(
                result.stdout
            )
        )
        return False
``` 

so yeah, until we move to releases, this deserved to be fixed (even though `mix run ...` is a bad practice)

**Comment by pnowosie** [comment]
Note: OMG.DB.Init() is also step in [manual startup doc](https://github.com/omisego/elixir-omg/blob/master/docs/manual_service_startup.md)

**Comment by pdobacz** [comment]
just a note on:

> cannot support every single way a developer would like to

I think operating a bare-metal chch/watcher via `mix` is very very useful, and I'd absolutely like to support that and have an option avoiding both docker and python.

Besides, `mix run ...` was an interim solution. I think having a `mix command` that eventually calls into the same thing as the release-based command (if one exists) is reasonable.  Writing from memory, I think we're looking into ~3 commands now: `OMG.DB.init`, perf test ones and prepare dev env. The 4th one is already there: `start`

**Comment by pnowosie** [comment]
@InoMurko is it fixed?

**Comment by InoMurko** [comment]
I’m not allowed to merge #884 yet. But this ought to work there...

**Comment by InoMurko** [comment]
Hopefully tomorrow!
