### ISSUE TITLE
fix ecto.gen.migration task mix task

### ISSUE THREAD

**Issue by jrhite** [omisego/elixir-omg#867]
Currently this task does is broken.

1. If `mix ecto.gen.migration add_eth_txn_hash_column -r OMG.Watcher.Repo` is run from the base dir `elixir_omg` the following error will occur:

```
** (Mix) Cannot run task "ecto.gen.migration" from umbrella application
```

2. If run from `elixir-omg/apps/omg_watcher` then you will see an error about `OMG.Umbrella.MixProject.umbrella_version()` not existing. To hack/fix this you will need to go into the following child apps and hard-code the umbrella version to some random version...eg: '0.0.0'

```
apps/omg/mix.exs
apps/omg_child_chain/mix.exs
apps/omg_db/mix.exs
apps/omg_eth/mix.exs
apps/omg_status/mix.exs
apps/omg_utils/mix.exs
```

Finally, after doing this you'll be a bit closer, but when running `mix ecto.gen.migration add_eth_txn_hash_column` again from the `elixir-omg/apps/omg_watcher` dir you will see:

```
elixir-omg/apps/omg_watcher$ mix ecto.gen.migration add_eth_txn_hash_column
==> omg_eth
Compiling 19 files (.ex)
Generated omg_eth app
==> omg
Compiling 47 files (.ex)
Generated omg app
==> omg_watcher
** (Mix) The task "compile.phoenix" could not be found. Did you mean "compile.elixir"?
```

**Comment by InoMurko** [comment]
Yeah, so I tried quickly figuring out what's with this ... this sorts it somewhat https://github.com/omisego/elixir-omg/pull/868

**Comment by InoMurko** [comment]
The right command though would be `mix ecto.gen.migration <your migration file> -r OMG.Watcher.DB.Repo`

**Comment by InoMurko** [comment]
Sorted in #868
