### ISSUE TITLE
Geth 1.9.x incompatibility

### ISSUE THREAD

**Issue by pdobacz** [omisego/elixir-omg#879]
As of ef460128305490828e9b4f10987facbafd8aec37, we're not compatible with geth 1.9.x for a number of reasons:

**NOTE** `geth --dev` leaks memory on 1.9.0, make sure to use >=1.9.1

1. [ ] `geth` now requires a flag to be able to unlock via HTTP (used in integration tests)
2. [ ] there's some timing/race cond issue in the integration tests (found by @chrishunt):
```
1) test get the blocks from child chain after sending a transaction and start exit (OMG.Watcher.Integration.BlockGetterTest)
test/omg_watcher/integration/block_getter_test.exs:50
match (=) failed     The following variables were pinned:       deposit_blknum = 1       token_deposit_blknum = 2
token_addr = "0x10778cbaf134b9a32f505db993b3b6a6d6b5ef05"
code:  assert [%{"blknum" => ^deposit_blknum}, %{"blknum" => ^token_deposit_blknum, "currency" => ^token_addr}] = TestHelper.get_utxos(alice.addr())
right: []
stacktrace:
test/omg_watcher/integration/block_getter_test.exs:59: (test)
```
Not sure could be causing this, requires investigation. Hint: if one `Process.sleep(5000)` just before this failing assertion - the test will progress till next similar error. Something must be time-dependant where it shouldn't or?

3. [ ] as of 04539755afc2fc55df809a651fc79ea52f4abff3, if I use 
```
image: ethereum/client-go:v1.9.10
```
in `docker-compose.yml` and `docker-compose up geth childchain`, it seems to have an `ethereum_connection_alarm` raised all the time. As far as I managed to debug this, the geth returns a frame `websockex` doesn't understand:
```
{:EXIT, #PID<0.1407.0>,
 {%MatchError{
    term: "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",\"difficulty\":\"0x2\",\"number\":\"0x1340\",\"gasLimit\":\"0x1d0fe37\",\"gasUsed\":\"0x0\",\"timestamp\":\"0x5e25c76d\",\"extraData\":\"0xd88301090a846765746888676f312e31332e36856c696e75780000000000000091e1f181b047bcee86424d46baf0d1ab91512278251e3cc27fd7f1e1fcb493d50ddbc0cd0c6383c1ca1d59105f8a209f96b3150358825d44383ad766d3bf109e00\",\"mixHash\":\"0x00000000000"
  },
  [
    {WebSockex.Frame, :parse_frame, 1,
     [file: 'lib/websockex/frame.ex', line: 201]},
    {WebSockex, :websocket_loop, 3, [file: 'lib/websockex.ex', line: 622]},
    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
  ]}}
```

**Comment by InoMurko** [comment]
we're using infura's geths in production so this might be very valid work!

**Comment by pdobacz** [comment]
yeah I was pondering this as a blocker, but thought infura should make it transparent for us. But you're right, I think it's better to be safe in this aspect. And not having to maintain 1.8 is all the more reason. And this should be rather easy, once someone gets to focus on it

**Comment by pdobacz** [comment]
added one more thing to the list of stuffs requiring attention :point_up:
