### ISSUE TITLE
Things needs to be fix on v0.2

### ISSUE THREAD

**Issue by pnowosie** [omisego/elixir-omg#887]
Recently we spotted not all things planed landed in `v0.2` branch. E.g.
1. :exclamation: Watcher RPC don't listen on dev https://github.com/omisego/elixir-omg/pull/799
2. Version says 1.0 instead of 0.2 https://github.com/omisego/elixir-omg/pull/810
3. :question: anything else?

**Comment by Pongch** [comment]
Last I checked on Swagger docs, `tx.create` support for 712 is not in v0.2 
https://github.com/omisego/elixir-omg/pull/825

**Comment by pdobacz** [comment]
#852 

all the metrics/dd stuff? #812 #842 #775

docker compose stuff? #796 #826 #807 #793 

tx create is two PRs: #825 #813

(optional: fix performance drop #818 and the preceeding #764)

#799 doesn't make sense without #772 

#783 maybe too? (cors)

**Comment by pdobacz** [comment]
closing this, as no `v0.2` envs are alive now and I don't think back-porting is on the todo list.
