### ISSUE TITLE
watcher api to change rootchain contract

### ISSUE THREAD

**Issue by jrhite** [omisego/elixir-omg#897]
As someone who runs watcher, I'd like the ability to change which rootchain contract (and possibly new childchain ip address) my watcher points to, so that if OMG redeploys a new roothchain contract I can smoothly transition to the new contract.

**Comment by InoMurko** [comment]
@Pongch is this a product requirement?

**Comment by pdobacz** [comment]
note that theres https://github.com/omisego/elixir-omg/issues/846, maybe that story covers what you've meant @jrhite ?

**Comment by unnawut** [comment]
Concur that this should first be considered in bigger picture in #846. There's also a bit more content there so I'm closing this one.
