### ISSUE TITLE
Efficient calculation of business metrics

### ISSUE THREAD

**Issue by pdobacz** [omisego/elixir-omg#936]
Larger history of the child chain leads the expensive recalculation of the metrics (`balance` and `unique_users`) to block the components processing transactions and requests for too long.

We need either a way to do the calculations much lighter or non-blocking.

Spotted in https://github.com/omisego/devops/issues/142

**Comment by pdobacz** [comment]
First suggestion from @InoMurko :

> What I would propose is to:
> 
> 1. extract OMG.State storage (the one currently held in process state) into a behavior (look at OMG.DB). That would allow us to swap storage drivers.
> 2. Implement ETS storage on top of 1.
> 3. Keep the ETS table protected (writes are only permitted to ETS owner (omg.state) and let reads happen separately in a process just for metrics.

**Comment by paulperegud** [comment]
Just a word of warning on moving things to ETS. It does not support atomic writes for more than one entry at a time. Thus it would expose intermediate states of UTXO set to readers (other than the privileged writer). Analyze carefully if this is acceptable.

**Comment by InoMurko** [comment]
Thanks @paulperegud. I think that if we’re limiting ourselves to metrics in this particular use case we should be fine. The question is... are we seeing the whole picture?

**Comment by InoMurko** [comment]
As discussed, there are two other options proposed by @paulperegud and @pdobacz:
Quote:

@pdobacz 
`
there were 2 quick fixes (that don't involve architecture digging) that we discussed briefly with @pepesza - 1) was to fire a Task.async to calculate,  sending the entire utxos Map (presumably better than calculation in OMG.State process) - 2) was... I don't remember :disappointed: @pepesza? that was your pitch
if not, I'm proposing a more subtle switch off: 3) if size(utxos)>threshold, dont: calculate_metrics()
`


I've tried the following experiment. I've created a map with 1M UTXOs and calculated the amount of copying between processes (using http://erlang.org/doc/efficiency_guide/processes.html#id67714):
:erts_debug.flat_size/1

```
:erts_debug.flat_size(large_map)
40720868
```

the problem I think is that process heap of (task is sort of a spawn/1) needs to constantly grow until it fits the large term. which is quite a lot.

`
The default initial heap size of 233 words is quite conservative to support Erlang systems with hundreds of thousands or even millions of processes. The garbage collector grows and shrinks the heap as needed.
`

**Comment by pthomalla** [comment]
Enum.uniq is quite inefficiently written, 
We can still improve it a bit, which should speed up the counting of metrics.

```
defmodule Uniq do
    def uniq([a,a | list]), do: uniq([a|list])
    def uniq([a,b | list]), do: [ a | uniq([b|list])]
    def uniq([a]), do: [a]
    def uniq([]), do: []

    def calc(list, acc \\ 0)
    def calc([a,a | list], acc), do: calc([a|list], acc)
    def calc([_,b | list], acc), do:  calc([b|list], acc+1)  
    def calc([_], acc), do: acc+1
    def calc([], acc), do: acc

end
```

testy:

```list = Enum.map(1..1_000_000, fn _ -> :rand.uniform(10_000_000) end)```
798353  ```:timer.tc(& Enum.uniq(&1), [list])```
341475  ```:timer.tc( fn list -> Enum.sort(list) |> Uniq.uniq end , [list])```
320554  ```:timer.tc( fn list -> Enum.sort(list) |> Uniq.calc end , [list])```

```list = Enum.map(1..10_000_000, fn _ -> :rand.uniform(10_000_000) end)```
9898708  ```:timer.tc(& Enum.uniq(&1), [list])```
4075973  ```:timer.tc( fn list -> Enum.sort(list) |> Uniq.uniq end , [list])```
4066232  ```:timer.tc( fn list -> Enum.sort(list) |> Uniq.calc end , [list])```

**Comment by pdobacz** [comment]
this might've become irrelevant after https://github.com/omisego/elixir-omg/issues/1148 or at least blocked by figuring that out first.

**Comment by InoMurko** [comment]
Closing in fav of https://github.com/omisego/elixir-omg/issues/1148
