### ISSUE TITLE
Raised and cleared alarms need to be sent to Datadog as events

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#937]
Each raised alarms (system and application) needs to be sent to Datadog and Slack with
- git sha
- environment
so that we're able to properly react.
https://docs.datadoghq.com/api/?lang=python#post-an-event

**Comment by InoMurko** [comment]
We should expand this with events and service checks:
- byzantine events could be sent to datadog
- alarms, already mentioned (system - disk, ethereum client connectivity, invalid fee file)
- service checks for watcher -> child chain

Currently we use Statix (https://github.com/lexmag/statix) that lacks support for both of the above (https://github.com/lexmag/statix/pull/26).

**Comment by InoMurko** [comment]
I suggest we fork `statix` and maintain a mix of 
https://github.com/bleacherreport/statix/commits/otp-21.3.8.4-support 
and https://github.com/lexmag/statix/commits/master
they diverge after https://github.com/lexmag/statix/commit/2245dfbe869d6e266401ba7f89d8097ff8f7180b.

**Comment by InoMurko** [comment]
- [ ] expose watcher and child chain configurational values (contract sha and finality margin)
- [ ] change devops values for APP_ENV, propose the domain naming change to fix metrics filtering in datadog
- [ ] alarms and byzatnine events into datadog

**Comment by jrhite** [comment]
See slack discussion for additional info.

Would be good to tighten up the scope and definition of this issue, or change the title of it, depending on how we decide to split up and/or coordinate the work and requirements.

cc: @achiurizo @kevsul @InoMurko

**Comment by kevsul** [comment]
To follow up after various conversations:

We agreed that most of what performance testing needs are metrics and can use the existing telemetry system. 

If stress tests break the system by hitting its limits, then we may be able to identify some events that should have been fired. Depending on the progress of the this issue, we can add them here or create new issues.
