### ISSUE TITLE
Return each transaction's inputs and outputs in /transaction.all

### ISSUE THREAD

**Issue by jrhite** [omisego/elixir-omg#954]
Watcher `transaction.all` endpoint has incorrect output. Given that a UTXO can several outputs the results of a transaction can not be resolved to the field `value`.

The output of  `transaction.all` should reflect similar output to `transaction.get`

Here is output of `transaction.all`:
```
{
    "data": [
        {
            "block": {
                "blknum": 6834000,
                "eth_height": 5063400,
                "hash": "0x4042ad9db42a62c0af2277350b56122dc445abd8f7d12962a158b15cab244118",
                "timestamp": 1568089732
            },
            "metadata": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "results": [
                {
                    "currency": "0x874ad6217760bb782405a77caf71a4c101d6c98c",
                    "value": 11860
                }
            ],
            "txhash": "0x67e997e16a5e6c5b21e230c46c60935dcf517940ec459cfd64aecc5ec99232c9",
            "txindex": 0
        },
<snip>
}
```

Here is the output of `transaction.get`:
```
{
    "data": {
        "block": {
            "blknum": 6834000,
            "eth_height": 5063400,
            "hash": "0x4042ad9db42a62c0af2277350b56122dc445abd8f7d12962a158b15cab244118",
            "timestamp": 1568089732
        },
        "inputs": [
            {
                "amount": 11860,
                "blknum": 6827000,
                "currency": "0x874ad6217760bb782405a77caf71a4c101d6c98c",
                "oindex": 1,
                "owner": "0xea5bdd40496515694ff54c6559a493723e1421c4",
                "txindex": 4,
                "utxo_pos": 6827000000040001
            }
        ],
        "metadata": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "outputs": [
            {
                "amount": 1,
                "blknum": 6834000,
                "currency": "0x874ad6217760bb782405a77caf71a4c101d6c98c",
                "oindex": 0,
                "owner": "0x12dd9e9d34dcb30c9622e77e5c0bf658e3380dac",
                "txindex": 0,
                "utxo_pos": 6834000000000000
            },
            {
                "amount": 11859,
                "blknum": 6834000,
                "currency": "0x874ad6217760bb782405a77caf71a4c101d6c98c",
                "oindex": 1,
                "owner": "0xea5bdd40496515694ff54c6559a493723e1421c4",
                "txindex": 0,
                "utxo_pos": 6834000000000001
            }
        ],
<snip>
}
```

**Comment by pnowosie** [comment]
Hey @pdobacz @jrhite - if I recall correctly the `results.value` is a balance of particular `currency` that transaction transfers / creates (the outputs). So if all UTXOs has the same currency there will be just one item in `results`.
The reason for presenting data this way was to:
1. reduce the amount of data sent
2. reduce number of joins - we can get outputs just decoding tx from rlp, no need to join with txoutputs...

I think (2.) isn't valid anymore as we can filter `transaction.all` by owner address...
Also as we introduced pagination of data also (1.) isn't so important...

**Comment by Nikodemek18** [comment]
Hi guys, when do we plan to finish this part? What's the timeline? @Pongch

**Comment by Pongch** [comment]
@Nikodemek18 none, lets identify what exactly it is the API consumer is trying to achieve first. For most cases:

>On the other spectrum is that in order to get the details you need, you ping transaction.get and we keep the API as is.

should suffice

**Comment by ripzery** [comment]
Here is the valid use-case for this issue. 

The application wants to display a list of transactions where it is grouped by the transaction direction (`sent` or `received`). If this API doesn't provide any clue about the address, then the only way to implement this is to call `transaction.get` for every transaction which is not ideal.

**Comment by unnawut** [comment]
To expand on @ripzery a bit...

- Consider a transaction list view displaying 10 transactions, filtered by a given account. 

- A project's current requirement is to indicate for each transaction in the list if it's incoming or outgoing.

- To do that now is an N+1 query (1x `/transaction.all` + 10x `/transaction.get`). Hence the reason we want to have it as part of `/transaction.all`.

- Future requirements may include showing the sender & recipient in the transaction list.

- And since the utxos set can get more complex in future iterations, giving the raw transaction outputs and let the client decide on them will give us the most consistent API from the start.

@Pongch Wdyt?

**Comment by Pongch** [comment]
i'm in favor of showing both in/outputs in 'transactions.all' based on @unnawut's points, reducing amount of queries to the Watcher is also a win. I'd still like to get a better understanding on the implementation details, I know pagination is introduced so the downside is capped, are there any other potential issues for Watcher if we enable this ?

**Comment by unnawut** [comment]
The main impact is the added join to the DB query, but this simple join should be very performant on postgres.

Also given `/transaction.all` is in informational watcher, the impact should be strictly limited to the informational API.

**Comment by Pongch** [comment]
got it, if the change in performance is negligible and the need from client is there, lets have it :)

**Comment by unnawut** [comment]
I'm going with this API design...

---

**Scope:** Informational API

**Endpoint:** `/transaction.all` (existing)

**Request format (unchanged):**

```json
# /transaction.all

{
  "address": "0xb3256026863eb6ae5b06fa396ab09069784ea8ea",
  "blknum": 6834000,
  "metadata": "0x5df13a6bf9...",
  "txindex": 0,
  "limit": 10,
  "page": 1
}
```

**Response format:**

- Adding "inputs" array
- Adding "outputs" array
- Keeping "results" to avoid breaking changes

```json
# /transaction.all

{
  "data": [
    {
      "block": {
        "blknum": 6834000,
        "eth_height": 5063400,
        "hash": "0x4042ad9db4...",
        "timestamp": 1568089732
      },
      "metadata": "0x5df13a6bf9...",
      "inputs": [
        {
          "amount": 11860,
          "blknum": 6827000,
          "currency": "0x874ad621...",
          "oindex": 1,
          "owner": "0xea5bdd40...",
          "txindex": 4,
          "utxo_pos": 6827000000040001
        }
      ],
      "outputs": [
        {
          "amount": 1,
          "blknum": 6834000,
          "currency": "0x874ad621...",
          "oindex": 0,
          "owner": "0x12dd9e9d...",
          "txindex": 0,
          "utxo_pos": 6834000000000000
        },
        {
          "amount": 11859,
          "blknum": 6834000,
          "currency": "0x874ad621...",
          "oindex": 1,
          "owner": "0xea5bdd40...",
          "txindex": 0,
          "utxo_pos": 6834000000000001
        }
      ],
      "results": [
        {
          "currency": "0x874ad621...",
          "value": 11860
        }
      ],
      "txhash": "0x67e997e...",
      "txindex": 0
    }
  ]
}
```

**Performance impact:**

1. `"inputs"` requires 1 sideload query between `transactions.txhash` and `txoutputs.spending_txhash`
2. `"outputs"` requires 1 sideload query between `transactions.txhash` and `txoutputs.creating_txhash`
3. Larger response payload (`limit` x 8 txoutputs i.e. 4 inputs, 4 outputs)

Both DB impacts are on Informational DB so they are minimal.

**Comment by jrhite** [comment]
I don't know of anything using `results`...is there something? If not I'd rather us just delete it. It will cause confusion later.

**Comment by unnawut** [comment]
> I don't know of anything using results...is there something? If not I'd rather us just delete it. It will cause confusion later.
>
> If there is some ODP-team using it that we don't know about, they shouldn't be using it.

`"results"` removed in #1178
