### ISSUE TITLE
Cannot submit a transaction on staging

### ISSUE THREAD

**Issue by ripzery** [omisego/elixir-omg#973]
`WATCHER_STAGING_URL/transaction.submit` returns 500 with the following command:
```
curl -v -X POST "WATCHER_STAGING_URL/transaction.submit" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"transaction\":\"0xf90185f886b841625ce19b4a2060499debb06035bd85e772eea78d94eaae86a1801d3c97da7e2c710b2d5dc17b5590957eb7e545eacb70ef5eb0887fb7ac9ebe7a90f57e3f06c91bb841625ce19b4a2060499debb06035bd85e772eea78d94eaae86a1801d3c97da7e2c710b2d5dc17b5590957eb7e545eacb70ef5eb0887fb7ac9ebe7a90f57e3f06c91bd0c3028080c3038080c3808080c3808080f8c9f394f1deff59da938e31673da1300b479896c743d9689450b390a7c935680a2529052d1e526886b3e3db22884563918244f40000f3944522fb44c2ab359e76ecc75c22c9409690f122419400000000000000000000000000000000000000008802c68aee67081c00f4944522fb44c2ab359e76ecc75c22c9409690f122419450b390a7c935680a2529052d1e526886b3e3db22890ffdf28905e43c0000eb94000000000000000000000000000000000000000094000000000000000000000000000000000000000080a00000000000000000000000000000000000000000000000000000000000000000\"}" 
```

**Comment by InoMurko** [comment]
Thanks for reporting this! Can you try transacting on development environment?

**Comment by ripzery** [comment]
Ok, will try soon.

**Comment by ripzery** [comment]
Hmm, I'm unable to deposit to the Childchain on development. I mean I can submit a transaction to the plasma contract, but I'm unable to get any utxos from `/account.get_utxos`

**Comment by InoMurko** [comment]
@ripzery can you post curls of each step and responses, so that we’re able to replicate?

**Comment by InoMurko** [comment]
@ripzery development has recently been wiped and redeployed, can you try again?

**Comment by pnowosie** [comment]
I decoded provided transaction it seems to be well formed. Also I checked the existence of the UTXO on staging - all good.

I replayed the transaction using staging Watcher `/transaction.submit`  and got `HTTP 500` response.

**Comment by pnowosie** [comment]
OK, it seems `staging` has some issues (ask @InoMurko ) leaving it in peace...

**Comment by InoMurko** [comment]
Development cluster is affected by the same issue, devops already informed. cc @kendricktan 
```
2019-09-17 21:07:25.577 [warn] module=OMG.Watcher.HttpRPC.Adapter function=rpc_post/3 request_id=FcVV20V-OSISqOcABQLB trace_id=3083452299226973338 span_id=5268991005123396369 ⋅Child chain rpc post "http://childchain-samrong:80/transaction.submit" failed with {:error, %HTTPoison.Error{id: nil, reason: :nxdomain}}⋅```
