### ISSUE TITLE
Add inserted_at and updated_at columns to transactions and blocks

### ISSUE THREAD

**Issue by jrhite** [omisego/elixir-omg#978]

**Comment by InoMurko** [comment]
@jrhite re-open if you think you need it still. Closing for now.

**Comment by jrhite** [comment]
Actively being worked on as we speak

**Comment by jrhite** [comment]
@InoMurko sorry for the noise, my bad here. This is actually just a dupe of another ticket we're actively working. Closing again.

Dupe of: https://github.com/omisego/elixir-omg/pull/1008

**Comment by unnawut** [comment]
This one is the issue though. #1008 is the PR to address this issue. 

Afaik, an issue is closed after its PR is merged. But no big deal here, just FYI.

**Comment by jrhite** [comment]
Argh...yes. Thanks for the heads up. Doh.

For consistency since we usually keep issues on our board that link to PRs rather than having PRs directly on the board, and for accuracy I'll reopen this, add back to our board and remove the PR from the board.

**Comment by unnawut** [comment]
Closed by #1322
