### ISSUE TITLE
update doc for `standard_vs_in_flight_exits_interaction.md`

### ISSUE THREAD

**Issue by boolafish** [omisego/elixir-omg#981]
### Note
We are implementing new mechanism of protection on that in ALD. Should upgrade the doc accordingly. Instead of cross-checking during exit starts or piggybacks, we flag output as spent and ignore that output if already spent during `processExit`

https://github.com/omisego/elixir-omg/blob/master/docs/standard_vs_in_flight_exits_interaction.md#possible-scenarios

**Comment by pdobacz** [comment]
@boolafish fixed in https://github.com/omisego/elixir-omg/pull/1174?

**Comment by boolafish** [comment]
Yup, updated
