### ISSUE TITLE
Custom monitors need supervision strategy capability

### ISSUE THREAD

**Issue by InoMurko** [omisego/elixir-omg#999]
Two of our Monitors were designed so that they prevent complete failure of Watcher and Child Chain if or when Ethereum client connectivity fails. There have now been occurrences of process failures when there was no problems with Ethereum clients and that resulted in massive spikes in logging. This should be mitigated by either including restart strategy in the the monitor or add a Supervisor layer after Monitor. And Monitor keeps an eye only on the Supervisior, but let's the error propagate if there are no relevant alarms raised.

**Comment by pdobacz** [comment]
If this would prevent the infinite restart sprees, I'm a huge fan :)

**Comment by InoMurko** [comment]
Yep thats it! 😅

**Comment by InoMurko** [comment]
We should introduce a new alarm type, an alarm that is a direct reflection if the supervisor still has it's children alive.

Monitor will not restart children if Ethereum client connectivity is functional, but that does not cover all the possibilities why the children might not be alive (configuration issues or bugs).
